# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description: "This view compares non-valuated unrestricted stock levels against relevant sales orders with deliveries details. The granularity is Client(System), material number, plant, storage location and language key."
fields:
  - name: "Client_MANDT"
    description: "Client (Mandant), PK"
  - name: "MaterialNumber_MATNR"
    description: "Material Number, PK"
  - name: "StorageLocation_LGORT"
    description: "Storage Location, PK"
  - name: "Plant_WERKS"
    description: "Plant, PK"
  - name: "Language_SPRAS"
    description: "Language Key, PK"
  - name: "MaterialText_MAKTX"
    description: "Description of Material"
  - name: "Plant_Name"
    description: "Name of Plant"
  - name: "BaseUnitOfMeasure_MEINS"
    description: "Base Unit of Measure"
  - name: "ProductHierarchy_PRDHA"
    description: "Product Hierarchy"
  - name: "Plant_Region"
    description: "Plant Region"
  - name: "Plant_Country"
    description: "Plant Country"
  - name: "UnrestrictedStock"
    description: "Unrestricted Stock"
  - name: "SalesQty"
    description: "Sales Quantity"
  - name: "DeliveredQty"
    description: "Delivered Quantity"
  - name: "DeliveredUoM_MEINS"
    description: "Delivered Base Unit of Measure"
  - name: "PendingDelivery"
    description: "Pending Delivery"
