/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "company_code_bukrs",
    "vendor_lifnr",
    "special_gl_transaction_type_umsks",
    "special_gl_indicator_umskz",
    "clearing_date_augdt",
    "clearing_document_augbl",
    "assignment_zuonr",
    "fiscal_year_gjahr",
    "document_number_belnr",
    "line_item_buzei"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  bsik.mandt AS client_mandt,
  bsik.bukrs AS company_code_bukrs,
  bsik.lifnr AS vendor_lifnr,
  bsik.umsks AS special_gl_transaction_type_umsks,
  bsik.umskz AS special_gl_indicator_umskz,
  bsik.augdt AS clearing_date_augdt,
  bsik.augbl AS clearing_document_augbl,
  bsik.zuonr AS assignment_zuonr,
  bsik.gjahr AS fiscal_year_gjahr,
  bsik.belnr AS document_number_belnr,
  bsik.buzei AS line_item_buzei,
  bsik.budat AS posting_date_budat,
  bsik.bldat AS document_date_bldat,
  bsik.cpudt AS entry_date_cpudt,
  bsik.waers AS currency_waers,
  bsik.xblnr AS reference_xblnr,
  bsik.blart AS document_type_blart,
  bsik.monat AS posting_period_monat,
  bsik.bschl AS posting_key_bschl,
  bsik.zumsk AS target_special_gl_indicator_zumsk,
  bsik.shkzg AS debit_credit_indicator_shkzg,
  bsik.gsber AS business_area_gsber,
  bsik.mwskz AS tax_code_mwskz,
  bsik.dmbtr AS amount_in_local_currency_dmbtr,
  bsik.wrbtr AS amount_wrbtr,
  bsik.mwsts AS local_currency_tax_amount_mwsts,
  bsik.wmwst AS tax_amount_wmwst,
  bsik.bdiff AS valuation_difference_bdiff,
  bsik.bdif2 AS valuation_difference_2_bdif2,
  bsik.sgtxt AS text_sgtxt,
  bsik.projn AS not_in_use_projn,
  bsik.aufnr AS order_aufnr,
  bsik.anln1 AS asset_anln1,
  bsik.anln2 AS sub_number_anln2,
  bsik.ebeln AS purchasing_document_ebeln,
  bsik.ebelp AS item_ebelp,
  bsik.saknr AS gl_account_saknr,
  bsik.hkont AS gl_account_hkont,
  bsik.fkont AS financial_budget_fkont,
  bsik.filkd AS branch_account_filkd,
  bsik.zfbdt AS baseline_payment_date_zfbdt,
  bsik.zterm AS terms_of_payment_zterm,
  bsik.zbd1t AS days_1_zbd1t,
  bsik.zbd2t AS days_2_zbd2t,
  bsik.zbd3t AS days_net_zbd3t,
  bsik.zbd1p AS cash_discount_percent_1_zbd1p,
  bsik.zbd2p AS cash_discount_percent_2_zbd2p,
  bsik.skfbt AS cash_discount_base_skfbt,
  bsik.sknto AS cash_discount_amount_sknto,
  bsik.wskto AS cash_discount_amount_wskto,
  bsik.zlsch AS payment_method_zlsch,
  bsik.zlspr AS payment_block_zlspr,
  bsik.zbfix AS fixed_zbfix,
  bsik.hbkid AS house_bank_hbkid,
  bsik.bvtyp AS part_bank_type_bvtyp,
  bsik.rebzg AS invoice_reference_rebzg,
  bsik.rebzj AS fiscal_year_rebzj,
  bsik.rebzz AS line_item_rebzz,
  bsik.samnr AS collective_invoice_samnr,
  bsik.zollt AS customs_tariff_number_zollt,
  bsik.zolld AS customs_date_zolld,
  bsik.lzbkz AS scb_indicator_lzbkz,
  bsik.landl AS supplying_country_landl,
  bsik.diekz AS service_indicator_diekz,
  bsik.mansp AS dunning_block_mansp,
  bsik.mschl AS dunning_key_mschl,
  bsik.madat AS last_dunned_madat,
  bsik.manst AS dunning_level_manst,
  bsik.maber AS dunning_area_maber,
  bsik.xnetb AS net_document_type_xnetb,
  bsik.xanet AS indicator_down_payment_in_net_procedure_xanet,
  bsik.xcpdd AS individ_set_xcpdd,
  bsik.xzahl AS payment_transaction_xzahl,
  bsik.mwsk1 AS tax_code_mwsk1,
  bsik.dmbt1 AS amount_dmbt1,
  bsik.wrbt1 AS amount_wrbt1,
  bsik.mwsk2 AS tax_code_mwsk2,
  bsik.dmbt2 AS amount_dmbt2,
  bsik.wrbt2 AS amount_wrbt2,
  bsik.mwsk3 AS tax_code_mwsk3,
  bsik.dmbt3 AS amount_dmbt3,
  bsik.wrbt3 AS amount_wrbt3,
  bsik.qsskz AS withholding_tax_code_qsskz,
  bsik.qsshb AS withholding_tax_base_qsshb,
  bsik.qbshb AS withholding_tax_amnt_qbshb,
  bsik.bstat AS document_status_bstat,
  bsik.anfbn AS bill_of_exchange_payment_request_anfbn,
  bsik.anfbj AS fiscal_year_of_the_bill_of_exchange_payment_request_document_anfbj,
  bsik.anfbu AS company_code_anfbu,
  bsik.vbund AS trading_partner_vbund,
  bsik.rebzt AS follow_on_document_type_rebzt,
  bsik.stceg AS vat_registration_number_stceg,
  bsik.egbld AS country_of_destinat_egbld,
  bsik.eglld AS supplying_country_eglld,
  bsik.qsznr AS exemption_number_qsznr,
  bsik.qsfbt AS w_tax_exempt_amount_qsfbt,
  bsik.xinve AS investment_id_xinve,
  bsik.projk AS wbs_element_projk,
  bsik.fipos AS commitment_item_fipos,
  bsik.nplnr AS network_nplnr,
  bsik.aufpl AS operation_task_list_number_aufpl,
  bsik.aplzl AS counter_aplzl,
  bsik.xegdr AS eu_triangular_deal_xegdr,
  bsik.dmbe2 AS lc2_amount_dmbe2,
  bsik.dmbe3 AS lc3_amount_dmbe3,
  bsik.dmb21 AS amount_dmb21,
  bsik.dmb22 AS amount_dmb22,
  bsik.dmb23 AS amount_dmb23,
  bsik.dmb31 AS amount_dmb31,
  bsik.dmb32 AS amount_dmb32,
  bsik.dmb33 AS amount_dmb33,
  bsik.mwst2 AS lc2_tax_amount_mwst2,
  bsik.mwst3 AS lc3_tax_amount_mwst3,
  bsik.sknt2 AS lc2_cash_discount_amnt_sknt2,
  bsik.sknt3 AS lc3_cash_discount_amnt_sknt3,
  bsik.bdif3 AS valuation_difference_3_bdif3,
  bsik.xragl AS reverse_clearing_xragl,
  bsik.rstgr AS reason_code_rstgr,
  bsik.uzawe AS payment_meth_supplement_uzawe,
  bsik.kostl AS cost_center_kostl,
  bsik.lnran AS sequence_number_lnran,
  bsik.xstov AS reversal_flag_xstov,
  bsik.kzbtr AS orig_reduction_amnt_kzbtr,
  bsik.xref1 AS reference_key_1_xref1,
  bsik.xref2 AS reference_key_2_xref2,
  bsik.xarch AS archived_xarch,
  bsik.pswsl AS general_ledger_currency_pswsl,
  bsik.pswbt AS general_ledger_amount_pswbt,
  bsik.imkey AS real_estate_key_imkey,
  bsik.zekkn AS seq_number_of_account_assgt_zekkn,
  bsik.fistl AS funds_center_fistl,
  bsik.geber AS fund_geber,
  bsik.dabrz AS reference_date_dabrz,
  bsik.xnegp AS negative_posting_xnegp,
  bsik.empfb AS payee_empfb,
  bsik.prctr AS profit_center_prctr,
  bsik.xref3 AS reference_key_3_xref3,
  bsik.dtws1 AS instruction_1_dtws1,
  bsik.dtws2 AS instruction_2_dtws2,
  bsik.dtws3 AS instruction_3_dtws3,
  bsik.dtws4 AS instruction_4_dtws4,
  bsik.xpypr AS payment_sent_xpypr,
  bsik.kidno AS payment_reference_kidno,
  bsik.pycur AS payment_currency_pycur,
  bsik.pyamt AS payment_curr_amnt_pyamt,
  bsik.bupla AS business_place_bupla,
  bsik.secco AS section_code_secco,
  bsik.ppdiff AS difference_realized_ppdiff,
  bsik.ppdif2 AS difference_realized_ppdif2,
  bsik.ppdif3 AS difference_realized_ppdif3,
  bsik.penlc1 AS penalty_chge_in_local_currency_penlc1,
  bsik.penlc2 AS pen_charge_in_lc2_penlc2,
  bsik.penlc3 AS pen_charge_in_lc3_penlc3,
  bsik.penfc AS penalty_charge_penfc,
  bsik.pendays AS days_in_arrears_pendays,
  bsik.penrc AS reason_for_late_payment_penrc,
  bsik.vertt AS contract_type_vertt,
  bsik.vertn AS contract_number_vertn,
  bsik.vbewa AS flow_type_vbewa,
  bsik.kblnr AS earmarked_funds_kblnr,
  bsik.kblpos AS document_item_kblpos,
  bsik.grant_nbr AS grant_nbr,
  bsik.gmvkz AS transfer_to_execution_gmvkz,
  bsik.srtype AS type_of_addtnl_recvabl_srtype,
  bsik.lotkz AS request_number_lotkz,
  bsik.zinkz AS interest_block_zinkz,
  bsik.fkber AS functional_area_fkber,
  bsik.intreno AS real_estate_code_intreno,
  bsik.pprct AS partner_profit_center_pprct,
  bsik.buzid AS line_item_id_buzid,
  bsik.auggj AS clearing_fiscal_year_auggj,
  bsik.hktid AS account_id_hktid,
  bsik.budget_pd AS budget_period_budget_pd,
  bsik.kontt AS account_assignment_cat_kontt,
  bsik.kontl AS account_assignment_kontl,
  bsik.uebgdat AS transfer_date_to_legal_dunning_proc_uebgdat,
  bsik.vname AS joint_venture_vname,
  bsik.egrup AS equity_group_egrup,
  bsik.btype AS billing_indicator_btype,
  bsik.propmano AS mandate_propmano,
  IFNULL(bsik.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bsik")} AS bsik
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["bsik"])
])}
`
);
