/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "company_code_bukrs",
    "vendor_lifnr",
    "special_gl_transaction_type_umsks",
    "special_gl_indicator_umskz",
    "clearing_date_augdt",
    "clearing_document_augbl",
    "assignment_zuonr",
    "fiscal_year_gjahr",
    "document_number_belnr",
    "line_item_buzei"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  bsak.mandt AS client_mandt,
  bsak.bukrs AS company_code_bukrs,
  bsak.lifnr AS vendor_lifnr,
  bsak.umsks AS special_gl_transaction_type_umsks,
  bsak.umskz AS special_gl_indicator_umskz,
  bsak.augdt AS clearing_date_augdt,
  bsak.augbl AS clearing_document_augbl,
  bsak.zuonr AS assignment_zuonr,
  bsak.gjahr AS fiscal_year_gjahr,
  bsak.belnr AS document_number_belnr,
  bsak.buzei AS line_item_buzei,
  bsak.budat AS posting_date_budat,
  bsak.bldat AS document_date_bldat,
  bsak.cpudt AS entry_date_cpudt,
  bsak.waers AS currency_waers,
  bsak.xblnr AS reference_xblnr,
  bsak.blart AS document_type_blart,
  bsak.monat AS posting_period_monat,
  bsak.bschl AS posting_key_bschl,
  bsak.zumsk AS target_special_gl_indicator_zumsk,
  bsak.shkzg AS debit_credit_indicator_shkzg,
  bsak.gsber AS business_area_gsber,
  bsak.mwskz AS tax_code_mwskz,
  bsak.dmbtr AS amount_in_local_currency_dmbtr,
  bsak.wrbtr AS amount_wrbtr,
  bsak.mwsts AS local_currency_tax_amount_mwsts,
  bsak.wmwst AS tax_amount_wmwst,
  bsak.bdiff AS valuation_difference_bdiff,
  bsak.bdif2 AS valuation_difference_2_bdif2,
  bsak.sgtxt AS text_sgtxt,
  bsak.projn AS not_in_use_projn,
  bsak.aufnr AS order_aufnr,
  bsak.anln1 AS asset_anln1,
  bsak.anln2 AS sub_number_anln2,
  bsak.ebeln AS purchasing_document_ebeln,
  bsak.ebelp AS item_ebelp,
  bsak.saknr AS gl_account_saknr,
  bsak.hkont AS gl_account_hkont,
  bsak.fkont AS financial_budget_fkont,
  bsak.filkd AS branch_account_filkd,
  bsak.zfbdt AS baseline_payment_date_zfbdt,
  bsak.zterm AS terms_of_payment_zterm,
  bsak.zbd1t AS days_1_zbd1t,
  bsak.zbd2t AS days_2_zbd2t,
  bsak.zbd3t AS days_net_zbd3t,
  bsak.zbd1p AS cash_discount_percent_1_zbd1p,
  bsak.zbd2p AS cash_discount_percent_2_zbd2p,
  bsak.skfbt AS cash_discount_base_skfbt,
  bsak.sknto AS cash_discount_amount_sknto,
  bsak.wskto AS cash_discount_amount_wskto,
  bsak.zlsch AS payment_method_zlsch,
  bsak.zlspr AS payment_block_zlspr,
  bsak.zbfix AS fixed_zbfix,
  bsak.hbkid AS house_bank_hbkid,
  bsak.bvtyp AS part_bank_type_bvtyp,
  bsak.rebzg AS invoice_reference_rebzg,
  bsak.rebzj AS fiscal_year_rebzj,
  bsak.rebzz AS line_item_rebzz,
  bsak.samnr AS collective_invoice_samnr,
  bsak.zollt AS customs_tariff_number_zollt,
  bsak.zolld AS customs_date_zolld,
  bsak.lzbkz AS scb_indicator_lzbkz,
  bsak.landl AS supplying_country_landl,
  bsak.diekz AS service_indicator_diekz,
  bsak.mansp AS dunning_block_mansp,
  bsak.mschl AS dunning_key_mschl,
  bsak.madat AS last_dunned_madat,
  bsak.manst AS dunning_level_manst,
  bsak.maber AS dunning_area_maber,
  bsak.xnetb AS net_document_type_xnetb,
  bsak.xanet AS indicator_down_payment_in_net_procedure_xanet,
  bsak.xcpdd AS individ_set_xcpdd,
  bsak.xzahl AS payment_transaction_xzahl,
  bsak.mwsk1 AS tax_code_mwsk1,
  bsak.dmbt1 AS amount_dmbt1,
  bsak.wrbt1 AS amount_wrbt1,
  bsak.mwsk2 AS tax_code_mwsk2,
  bsak.dmbt2 AS amount_dmbt2,
  bsak.wrbt2 AS amount_wrbt2,
  bsak.mwsk3 AS tax_code_mwsk3,
  bsak.dmbt3 AS amount_dmbt3,
  bsak.wrbt3 AS amount_wrbt3,
  bsak.qsskz AS withholding_tax_code_qsskz,
  bsak.qsshb AS withholding_tax_base_qsshb,
  bsak.qbshb AS withholding_tax_amnt_qbshb,
  bsak.bstat AS document_status_bstat,
  bsak.anfbn AS bill_of_exchange_payment_request_anfbn,
  bsak.anfbj AS fiscal_year_of_the_bill_of_exchange_payment_request_document_anfbj,
  bsak.anfbu AS company_code_anfbu,
  bsak.vbund AS trading_partner_vbund,
  bsak.rebzt AS follow_on_document_type_rebzt,
  bsak.stceg AS vat_registration_number_stceg,
  bsak.egbld AS country_of_destinat_egbld,
  bsak.eglld AS supplying_country_eglld,
  bsak.qsznr AS exemption_number_qsznr,
  bsak.qsfbt AS w_tax_exempt_amount_qsfbt,
  bsak.xinve AS investment_id_xinve,
  bsak.projk AS wbs_element_projk,
  bsak.fipos AS commitment_item_fipos,
  bsak.nplnr AS network_nplnr,
  bsak.aufpl AS operation_task_list_number_aufpl,
  bsak.aplzl AS counter_aplzl,
  bsak.xegdr AS eu_triangular_deal_xegdr,
  bsak.dmbe2 AS lc2_amount_dmbe2,
  bsak.dmbe3 AS lc3_amount_dmbe3,
  bsak.dmb21 AS amount_dmb21,
  bsak.dmb22 AS amount_dmb22,
  bsak.dmb23 AS amount_dmb23,
  bsak.dmb31 AS amount_dmb31,
  bsak.dmb32 AS amount_dmb32,
  bsak.dmb33 AS amount_dmb33,
  bsak.mwst2 AS lc2_tax_amount_mwst2,
  bsak.mwst3 AS lc3_tax_amount_mwst3,
  bsak.sknt2 AS lc2_cash_discount_amnt_sknt2,
  bsak.sknt3 AS lc3_cash_discount_amnt_sknt3,
  bsak.bdif3 AS valuation_difference_3_bdif3,
  bsak.xragl AS reverse_clearing_xragl,
  bsak.rstgr AS reason_code_rstgr,
  bsak.uzawe AS payment_meth_supplement_uzawe,
  bsak.kostl AS cost_center_kostl,
  bsak.lnran AS sequence_number_lnran,
  bsak.xstov AS reversal_flag_xstov,
  bsak.kzbtr AS orig_reduction_amnt_kzbtr,
  bsak.xref1 AS reference_key_1_xref1,
  bsak.xref2 AS reference_key_2_xref2,
  bsak.xarch AS archived_xarch,
  bsak.pswsl AS general_ledger_currency_pswsl,
  bsak.pswbt AS general_ledger_amount_pswbt,
  bsak.imkey AS real_estate_key_imkey,
  bsak.zekkn AS seq_number_of_account_assgt_zekkn,
  bsak.fistl AS funds_center_fistl,
  bsak.geber AS fund_geber,
  bsak.dabrz AS reference_date_dabrz,
  bsak.xnegp AS negative_posting_xnegp,
  bsak.empfb AS payee_empfb,
  bsak.prctr AS profit_center_prctr,
  bsak.xref3 AS reference_key_3_xref3,
  bsak.dtws1 AS instruction_1_dtws1,
  bsak.dtws2 AS instruction_2_dtws2,
  bsak.dtws3 AS instruction_3_dtws3,
  bsak.dtws4 AS instruction_4_dtws4,
  bsak.xpypr AS payment_sent_xpypr,
  bsak.kidno AS payment_reference_kidno,
  bsak.pycur AS payment_currency_pycur,
  bsak.pyamt AS payment_curr_amnt_pyamt,
  bsak.bupla AS business_place_bupla,
  bsak.secco AS section_code_secco,
  bsak.ppdiff AS difference_realized_ppdiff,
  bsak.ppdif2 AS difference_realized_ppdif2,
  bsak.ppdif3 AS difference_realized_ppdif3,
  bsak.penlc1 AS penalty_chge_in_local_currency_penlc1,
  bsak.penlc2 AS pen_charge_in_lc2_penlc2,
  bsak.penlc3 AS pen_charge_in_lc3_penlc3,
  bsak.penfc AS penalty_charge_penfc,
  bsak.pendays AS days_in_arrears_pendays,
  bsak.penrc AS reason_for_late_payment_penrc,
  bsak.vertt AS contract_type_vertt,
  bsak.vertn AS contract_number_vertn,
  bsak.vbewa AS flow_type_vbewa,
  bsak.kblnr AS earmarked_funds_kblnr,
  bsak.kblpos AS document_item_kblpos,
  bsak.grant_nbr AS grant_nbr,
  bsak.gmvkz AS transfer_to_execution_gmvkz,
  bsak.srtype AS type_of_addtnl_recvabl_srtype,
  bsak.lotkz AS request_number_lotkz,
  bsak.zinkz AS interest_block_zinkz,
  bsak.fkber AS functional_area_fkber,
  bsak.intreno AS real_estate_code_intreno,
  bsak.pprct AS partner_profit_center_pprct,
  bsak.buzid AS line_item_id_buzid,
  bsak.auggj AS clearing_fiscal_year_auggj,
  bsak.hktid AS account_id_hktid,
  bsak.budget_pd AS budget_period_budget_pd,
  bsak.kontt AS account_assignment_cat_kontt,
  bsak.kontl AS account_assignment_kontl,
  bsak.uebgdat AS transfer_date_to_legal_dunning_proc_uebgdat,
  bsak.vname AS joint_venture_vname,
  bsak.egrup AS equity_group_egrup,
  bsak.btype AS billing_indicator_btype,
  bsak.propmano AS mandate_propmano,
  IFNULL(bsak.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bsak")} AS bsak
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["bsak"])
])}
`
);
