# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "cortex"
version = "7.0.2"
description = "Cortex Framework"
requires-python = ">=3.13,<3.14"
dependencies = [
    "google-cloud-bigquery>=3.40.1",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
    "google-cloud-dataform>=0.9.0",
    "google-cloud-resource-manager>=1.16.0",
    "google-cloud-service-usage>=1.15.0",
    "jinja2>=3.1.6",
    "google-auth>=2.48.0",
    "keyrings-google-artifactregistry-auth>=1.1.2",
    "google-cloud-storage>=3.10.1",
    "google-cloud-bigquery-reservation>=1.25.0",
    "google-cloud-dataplex>=2.20.0",
]

[project.scripts]
cortex-build = "tools.build:main"
cortex-deploy = "tools.deploy:main"
cortex-build-and-deploy = "tools.run_all:main"
cortex-demo = "tools.demo:main"
cortex-kc-sync = "tools.kc_sync:main"
cortex-config = "tools.config:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/common", "src/tools", "src/data_foundation", "src/data_product"]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
    "pytest>=8.0.0",
    "pytest-mock>=3.14.0",
    "mypy>=1.19.1",
    "types-PyYAML>=6.0.2",
    "types-protobuf>=6.32.1.20260221",
    "pytest-bigquery-mock>=0.1.2",
    "zetasql>=0.1.5",
    "pandas>=2.2.0",
    "keyrings-google-artifactregistry-auth>=1.1.2",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "SIM",# flake8-simplify
]
ignore = []

[tool.pytest.ini_options]
pythonpath = [
    "src"]

[tool.mypy]
plugins = ["pydantic.mypy"]
mypy_path = "src"
explicit_package_bases = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

