# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ecc:
  sales_order_stock:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, sap_sd, source_aligned_product, 
        transactional, hourly]
  sales_order_stock_with_vendor:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, sap_sd, source_aligned_product, 
        transactional, hourly]
  special_stocks_from_vendor:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, sap_sd, source_aligned_product, 
        transactional, hourly]
  special_stocks_with_vendor:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, sap_sd, source_aligned_product, 
        transactional, hourly]
  special_stocks_with_customer:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, sap_sd, source_aligned_product, 
        transactional, hourly]
