# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ecc:
  fiscal_year_variants:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: finance
    - key: sap_module
      value: sap_fi
    - key: data_class
      value: masterdata
    dataformTags: [sap, finance, sap_fi, source_aligned_product, masterdata, 
        monthly]
  fiscal_year_variant_periods:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: finance
    - key: sap_module
      value: sap_fi
    - key: data_class
      value: masterdata
    dataformTags: [sap, finance, sap_fi, source_aligned_product, masterdata, 
        monthly]
s4:
  fiscal_year_variants:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: finance
    - key: sap_module
      value: sap_fi
    - key: data_class
      value: masterdata
    dataformTags: [sap, finance, sap_fi, source_aligned_product, masterdata, 
        monthly]
  fiscal_year_variant_periods:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: finance
    - key: sap_module
      value: sap_fi
    - key: data_class
      value: masterdata
    dataformTags: [sap, finance, sap_fi, source_aligned_product, masterdata, 
        monthly]
