/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "company_code_bukrs",
    "document_number_belnr",
    "fiscal_year_gjahr",
    "line_item_buzei"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
),
currency_decimal AS (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  bseg.mandt AS client_mandt,
  bseg.bukrs AS company_code_bukrs,
  bseg.belnr AS document_number_belnr,
  bseg.gjahr AS fiscal_year_gjahr,
  bseg.buzei AS line_item_buzei,
  bseg.buzid AS line_item_id_buzid,
  bseg.augdt AS clearing_date_augdt,
  bseg.augcp AS clearing_entry_date_augcp,
  bseg.augbl AS clearing_document_augbl,
  bseg.bschl AS posting_key_bschl,
  bseg.koart AS account_type_koart,
  bseg.umskz AS special_g_l_ind_umskz,
  bseg.umsks AS sp_g_l_trans_type_umsks,
  bseg.zumsk AS target_sp_g_l_ind_zumsk,
  bseg.shkzg AS debit_credit_indicator_shkzg,
  bseg.gsber AS business_area_gsber,
  bseg.pargb AS trading_part_ba_pargb,
  bseg.tax_country AS tax_country,
  bseg.mwskz AS tax_code_mwskz,
  bseg.txdat_from AS tax_rate_valid_from_txdat_from,
  bseg.qsskz AS withholding_tax_code_qsskz,
  ${currency.amountWithDecimalShift("bseg.dmbtr", "currency_decimal_h_hwaer")} AS amount_in_local_currency_dmbtr,
  ${currency.amountWithDecimalShift("bseg.wrbtr", "currency_decimal_h_waers")} AS amount_in_document_currency_wrbtr,
  ${currency.amountWithDecimalShift("bseg.kzbtr", "currency_decimal_h_hwaer")} AS orig_reduction_amt_kzbtr,
  ${currency.amountWithDecimalShift("bseg.pswbt", "currency_decimal_pswsl")} AS general_ledger_amount_pswbt,
  bseg.pswsl AS general_ledger_currency_pswsl,
  ${currency.amountWithDecimalShift("bseg.txbhw", "currency_decimal_h_hwaer")} AS original_tax_base_amount_txbhw,
  ${currency.amountWithDecimalShift("bseg.txbfw", "currency_decimal_h_waers")} AS original_tax_base_amount_txbfw,
  ${currency.amountWithDecimalShift("bseg.mwsts", "currency_decimal_h_hwaer")} AS lc_tax_amount_mwsts,
  ${currency.amountWithDecimalShift("bseg.wmwst", "currency_decimal_h_waers")} AS tax_amount_wmwst,
  ${currency.amountWithDecimalShift("bseg.lwsts", "currency_decimal_country_waers")} AS tax_in_country_crcy_lwsts,
  ${currency.amountWithDecimalShift("bseg.lwbtr", "currency_decimal_country_waers")} AS amount_in_country_currency_lwbtr,
  ${currency.amountWithDecimalShift("bseg.hwbas", "currency_decimal_h_hwaer")} AS lc_tax_base_hwbas,
  ${currency.amountWithDecimalShift("bseg.fwbas", "currency_decimal_h_waers")} AS tax_base_amount_fwbas,
  ${currency.amountWithDecimalShift("bseg.hwzuz", "currency_decimal_h_hwaer")} AS lc_provision_hwzuz,
  ${currency.amountWithDecimalShift("bseg.fwzuz", "currency_decimal_h_waers")} AS additional_tax_fwzuz,
  bseg.shzuz AS cash_discount_shzuz,
  bseg.stekz AS component_of_the_version_number_stekz,
  bseg.mwart AS tax_type_mwart,
  bseg.txgrp AS group_indicator_txgrp,
  bseg.ktosl AS transaction_ktosl,
  ${currency.amountWithDecimalShift("bseg.qsshb", "currency_decimal_h_waers")} AS withholding_tax_base_qsshb,
  bseg.kursr AS hedged_exchange_rate_kursr,
  ${currency.amountWithDecimalShift("bseg.gbetr", "currency_decimal_h_waers")} AS hedged_amount_gbetr,
  ${currency.amountWithDecimalShift("bseg.bdiff", "currency_decimal_h_hwaer")} AS valuation_difference_bdiff,
  ${currency.amountWithDecimalShift("bseg.bdif2", "currency_decimal_h_hwae2")} AS valuation_difference_2_bdif2,
  bseg.valut AS value_date_valut,
  bseg.zuonr AS assignment_number_zuonr,
  bseg.sgtxt AS item_text_sgtxt,
  bseg.zinkz AS interest_block_zinkz,
  bseg.vbund AS trading_partner_vbund,
  bseg.bewar AS transaction_type_bewar,
  bseg.altkt AS group_account_number_altkt,
  bseg.vorgn AS g_l_transaction_type_vorgn,
  bseg.fdlev AS planning_level_fdlev,
  bseg.fdgrp AS planning_group_fdgrp,
  ${currency.amountWithDecimalShift("bseg.fdwbt", "currency_decimal_h_waers")} AS planned_amount_fdwbt,
  bseg.fdtag AS planning_date_fdtag,
  bseg.fkont AS financial_budget_fkont,
  bseg.kokrs AS controlling_area_kokrs,
  bseg.kostl AS cost_center_kostl,
  bseg.projn AS not_in_use_projn,
  bseg.aufnr AS order_number_aufnr,
  bseg.vbeln AS billing_document_vbeln,
  bseg.vbel2 AS sales_document_vbel2,
  bseg.posn2 AS sales_document_item_posn2,
  bseg.eten2 AS schedule_line_number_eten2,
  bseg.service_doc_type AS service_document_type_service_doc_type,
  bseg.service_doc_id AS service_document_service_doc_id,
  bseg.service_doc_item_id AS service_document_item_service_doc_item_id,
  bseg.anln1 AS asset_anln1,
  bseg.anln2 AS sub_number_anln2,
  bseg.anbwa AS asset_transaction_type_anbwa,
  bseg.bzdat AS asset_value_date_bzdat,
  bseg.pernr AS personnel_number_pernr,
  bseg.xumsw AS sales_related_xumsw,
  bseg.xhres AS indicator_resident_g_l_account_xhres,
  bseg.xkres AS line_item_display_xkres,
  bseg.xopvw AS open_item_management_xopvw,
  bseg.xcpdd AS individ_set_xcpdd,
  bseg.xskst AS cctrpostingstatist_xskst,
  bseg.xsauf AS order_post_statist_xsauf,
  bseg.xspro AS proj_posting_stat_xspro,
  bseg.xserg AS pa_posting_stat_xserg,
  bseg.xfakt AS indicator_billing_document_update_successful_xfakt,
  bseg.xuman AS indicator_transfer_posting_from_down_payment_xuman,
  bseg.xanet AS indicator_down_payment_in_net_procedure_xanet,
  bseg.xskrl AS w_o_cash_dscnt_xskrl,
  bseg.xinve AS investment_id_xinve,
  bseg.xpanz AS display_item_xpanz,
  bseg.xauto AS line_item_automatically_created_xauto,
  bseg.xncop AS indicator_items_cannot_be_copied_xncop,
  bseg.xzahl AS payment_transaction_xzahl,
  bseg.saknr AS gl_account_saknr,
  bseg.hkont AS gl_account_hkont,
  bseg.kunnr AS customer_number_kunnr,
  bseg.lifnr AS vendor_number_lifnr,
  bseg.filkd AS branch_account_filkd,
  bseg.xbilk AS balance_sheet_account_xbilk,
  bseg.gvtyp AS p_l_statmt_acct_type_gvtyp,
  bseg.hzuon AS specl_g_l_assgt_hzuon,
  bseg.zfbdt AS baseline_payment_dte_zfbdt,
  bseg.zterm AS payment_terms_zterm,
  bseg.zbd1t AS days_1_zbd1t,
  bseg.zbd2t AS days_2_zbd2t,
  bseg.zbd3t AS days_net_zbd3t,
  bseg.zbd1p AS disc_percent_1_zbd1p,
  bseg.zbd2p AS disc_percent_2_zbd2p,
  ${currency.amountWithDecimalShift("bseg.skfbt", "currency_decimal_h_waers")} AS cd_base_skfbt,
  ${currency.amountWithDecimalShift("bseg.sknto", "currency_decimal_h_hwaer")} AS cash_discount_amount_sknto,
  ${currency.amountWithDecimalShift("bseg.wskto", "currency_decimal_h_waers")} AS cd_amount_wskto,
  bseg.zlsch AS payment_method_zlsch,
  bseg.zlspr AS payment_block_zlspr,
  bseg.zbfix AS fixed_zbfix,
  bseg.hbkid AS house_bank_hbkid,
  bseg.bvtyp AS part_bank_type_bvtyp,
  ${currency.amountWithDecimalShift("bseg.nebtr", "currency_decimal_h_waers")} AS payment_amount_nebtr,
  bseg.mwsk1 AS tax_code_mwsk1,
  bseg.txdat_from1 AS tax_rate_valid_from_tax_backpack_txdat_from1,
  bseg.tax_country1 AS tax_country_for_tax_breakdown_tax_country1,
  ${currency.amountWithDecimalShift("bseg.dmbt1", "currency_decimal_h_hwaer")} AS amount_dmbt1,
  ${currency.amountWithDecimalShift("bseg.wrbt1", "currency_decimal_h_waers")} AS amount_wrbt1,
  bseg.hist_tax_factor1 AS hist_factor_for_taxamt_hist_tax_factor1,
  bseg.mwsk2 AS tax_code_mwsk2,
  bseg.txdat_from2 AS tax_rate_valid_from_tax_backpack_txdat_from2,
  bseg.tax_country2 AS tax_country_for_tax_breakdown_tax_country2,
  ${currency.amountWithDecimalShift("bseg.dmbt2", "currency_decimal_h_hwae2")} AS amount_dmbt2,
  ${currency.amountWithDecimalShift("bseg.wrbt2", "currency_decimal_h_waers")} AS amount_wrbt2,
  bseg.hist_tax_factor2 AS hist_factor_for_taxamt_hist_tax_factor2,
  bseg.mwsk3 AS tax_code_mwsk3,
  bseg.txdat_from3 AS tax_rate_valid_from_tax_backpack_txdat_from3,
  bseg.tax_country3 AS tax_country_for_tax_breakdown_tax_country3,
  ${currency.amountWithDecimalShift("bseg.dmbt3", "currency_decimal_h_hwae3")} AS amount_dmbt3,
  ${currency.amountWithDecimalShift("bseg.wrbt3", "currency_decimal_h_waers")} AS amount_wrbt3,
  bseg.hist_tax_factor3 AS hist_factor_for_taxamt_hist_tax_factor3,
  bseg.hist_tax_factor AS hist_factor_for_taxamt_hist_tax_factor,
  bseg.rebzg AS invoice_reference_rebzg,
  bseg.rebzj AS fiscal_year_rebzj,
  bseg.rebzz AS item_rebzz,
  bseg.rebzt AS follow_on_doc_type_rebzt,
  bseg.zollt AS customs_tariff_no_zollt,
  bseg.zolld AS cust_date_zolld,
  bseg.lzbkz AS scb_indicator_lzbkz,
  bseg.landl AS supplying_cntry_landl,
  bseg.diekz AS service_indicator_diekz,
  bseg.samnr AS collective_invoice_samnr,
  bseg.abper AS settlmnt_period_abper,
  bseg.vrskz AS insurance_indicator_vrskz,
  bseg.vrsdt AS insurance_date_vrsdt,
  bseg.disbn AS usage_document_disbn,
  bseg.disbj AS year_disbj,
  bseg.disbz AS discount_lne_iem_disbz,
  bseg.wverw AS bill_ex_usage_wverw,
  bseg.anfbn AS boe_payment_request_anfbn,
  bseg.anfbj AS fiscal_year_of_the_bill_of_exchange_payment_request_document_anfbj,
  bseg.anfbu AS company_code_anfbu,
  bseg.anfae AS return_before_anfae,
  ${currency.amountWithDecimalShift("bseg.blnbt", "currency_decimal_h_hwaer")} AS preference_amount_blnbt,
  bseg.blnkz AS subsidy_indicator_blnkz,
  bseg.blnpz AS pref_percentage_rate_blnpz,
  bseg.mschl AS dunning_key_mschl,
  bseg.mansp AS dunning_block_mansp,
  bseg.madat AS last_dunned_madat,
  bseg.manst AS dunning_level_manst,
  bseg.maber AS dunning_area_maber,
  bseg.esrnr AS pbc_isr_number_esrnr,
  bseg.esrre AS isr_qr_reference_no_esrre,
  bseg.esrpz AS check_digit_esrpz,
  ${currency.amountWithDecimalShift("bseg.klibt", "currency_decimal_h_waers")} AS credit_control_amt_klibt,
  bseg.qsznr AS exemption_number_qsznr,
  ${currency.amountWithDecimalShift("bseg.qbshb", "currency_decimal_h_waers")} AS withholding_tax_amt_qbshb,
  ${currency.amountWithDecimalShift("bseg.qsfbt", "currency_decimal_h_waers")} AS wtax_exempt_amount_qsfbt,
  ${currency.amountWithDecimalShift("bseg.navhw", "currency_decimal_h_hwaer")} AS non_deductible_navhw,
  ${currency.amountWithDecimalShift("bseg.navfw", "currency_decimal_h_waers")} AS non_deductible_navfw,
  bseg.matnr AS material_matnr,
  bseg.werks AS plant_werks,
  bseg.menge AS quantity_menge,
  bseg.meins AS base_unit_of_measure_meins,
  bseg.erfmg AS qty_in_unit_of_entry_erfmg,
  bseg.erfme AS unit_of_entry_erfme,
  bseg.bpmng AS qty_in_opun_bpmng,
  bseg.bprme AS order_price_unit_bprme,
  bseg.ebeln_logsys AS logical_system_of_purchasing_document_ebeln_logsys,
  bseg.ebeln AS purchasing_document_ebeln,
  bseg.ebelp AS purchasing_document_item_ebelp,
  bseg.zekkn AS seq_no_of_account_assgt_zekkn,
  bseg.elikz AS delivery_completed_elikz,
  bseg.vprsv AS price_control_vprsv,
  bseg.peinh AS price_unit_peinh,
  bseg.bwkey AS valuation_area_bwkey,
  bseg.bwtar AS valuation_type_bwtar,
  bseg.bustw AS value_string_bustw,
  ${currency.amountWithDecimalShift("bseg.rewrt", "currency_decimal_h_hwaer")} AS invoice_value_rewrt,
  ${currency.amountWithDecimalShift("bseg.rewwr", "currency_decimal_h_waers")} AS fc_invoice_amount_rewwr,
  ${currency.amountWithDecimalShift("bseg.bonfb", "currency_decimal_h_hwaer")} AS amount_bonfb,
  ${currency.amountWithDecimalShift("bseg.bualt", "currency_decimal_h_waers")} AS amount_bualt,
  bseg.psalt AS alt_price_control_psalt,
  ${currency.amountWithDecimalShift("bseg.nprei", "currency_decimal_h_hwaer")} AS new_price_nprei,
  bseg.tbtkz AS subseq_debit_credit_tbtkz,
  bseg.spgrp AS blocking_reas_price_spgrp,
  bseg.spgrm AS blocking_reason_qty_spgrm,
  bseg.spgrt AS block_reason_date_spgrt,
  bseg.spgrg AS blocking_reason_opq_spgrg,
  bseg.spgrv AS blocking_reas_proj_spgrv,
  bseg.spgrq AS manual_block_reason_spgrq,
  bseg.stceg AS vat_registration_no_stceg,
  bseg.egbld AS destination_country_egbld,
  bseg.eglld AS supplying_country_eglld,
  bseg.rstgr AS reason_code_rstgr,
  bseg.ryacq AS year_of_acquisition_ryacq,
  bseg.rpacq AS per_of_acquisition_rpacq,
  ${currency.amountWithDecimalShift("bseg.rdiff", "currency_decimal_h_hwaer")} AS difference_realized_rdiff,
  ${currency.amountWithDecimalShift("bseg.rdif2", "currency_decimal_h_hwae2")} AS difference_realized_2_rdif2,
  bseg.prctr AS profit_center_prctr,
  bseg.xhkom AS manual_g_l_account_xhkom,
  bseg.vname AS joint_venture_vname,
  bseg.recid AS recovery_indicator_recid,
  bseg.egrup AS equity_group_egrup,
  bseg.vptnr AS partner_vptnr,
  bseg.vertt AS contract_type_vertt,
  bseg.vertn AS contract_number_vertn,
  bseg.vbewa AS flow_type_vbewa,
  bseg.depot AS securities_account_depot,
  bseg.txjcd AS tax_jurisdiction_txjcd,
  bseg.imkey AS real_estate_key_imkey,
  bseg.dabrz AS reference_date_dabrz,
  bseg.popts AS option_rate_popts,
  bseg.fipos AS commitment_item_fipos,
  bseg.kstrg AS cost_object_kstrg,
  bseg.nplnr AS network_nplnr,
  bseg.aufpl AS task_list_no_oper_aufpl,
  bseg.aplzl AS counter_aplzl,
  bseg.projk AS wbs_element_projk,
  bseg.paobjnr AS profitab_segmt_no_paobjnr,
  bseg.pasubnr AS subnumber_pasubnr,
  bseg.spgrs AS blkg_reason_item_amount_spgrs,
  bseg.spgrc AS blockreason_quality_spgrc,
  bseg.btype AS billing_indicator_btype,
  bseg.etype AS equity_type_etype,
  bseg.xegdr AS eu_triangular_deal_xegdr,
  bseg.lnran AS sequence_number_lnran,
  bseg.hrkft AS origin_group_hrkft,
  ${currency.amountWithDecimalShift("bseg.dmbe2", "currency_decimal_h_hwae2")} AS lc2_amount_dmbe2,
  ${currency.amountWithDecimalShift("bseg.dmbe3", "currency_decimal_h_hwae3")} AS lc3_amount_dmbe3,
  ${currency.amountWithDecimalShift("bseg.dmb21", "currency_decimal_h_hwae2")} AS amount_dmb21,
  ${currency.amountWithDecimalShift("bseg.dmb22", "currency_decimal_h_hwae2")} AS amount_dmb22,
  ${currency.amountWithDecimalShift("bseg.dmb23", "currency_decimal_h_hwae2")} AS amount_dmb23,
  ${currency.amountWithDecimalShift("bseg.dmb31", "currency_decimal_h_hwae3")} AS amount_dmb31,
  ${currency.amountWithDecimalShift("bseg.dmb32", "currency_decimal_h_hwae2")} AS amount_dmb32,
  ${currency.amountWithDecimalShift("bseg.dmb33", "currency_decimal_h_hwae3")} AS amount_dmb33,
  ${currency.amountWithDecimalShift("bseg.mwst2", "currency_decimal_h_hwae2")} AS lc2_tax_amount_mwst2,
  ${currency.amountWithDecimalShift("bseg.mwst3", "currency_decimal_h_hwae3")} AS lc3_tax_amount_mwst3,
  ${currency.amountWithDecimalShift("bseg.navh2", "currency_decimal_h_hwae2")} AS lc2_non_deductible_navh2,
  ${currency.amountWithDecimalShift("bseg.navh3", "currency_decimal_h_hwae3")} AS lc3_non_deductible_navh3,
  ${currency.amountWithDecimalShift("bseg.sknt2", "currency_decimal_h_hwae2")} AS cd_amount_in_lc2_sknt2,
  ${currency.amountWithDecimalShift("bseg.sknt3", "currency_decimal_h_hwae3")} AS cd_amount_in_lc3_sknt3,
  ${currency.amountWithDecimalShift("bseg.bdif3", "currency_decimal_h_hwae3")} AS valuation_difference_3_bdif3,
  ${currency.amountWithDecimalShift("bseg.rdif3", "currency_decimal_h_hwae3")} AS difference_realized_3_rdif3,
  bseg.hwmet AS method_with_which_the_local_currency_amount_was_determined_hwmet,
  bseg.glupm AS update_method_glupm,
  bseg.xragl AS reverse_clearing_xragl,
  bseg.uzawe AS pmt_meth_supplement_uzawe,
  bseg.lokkt AS alternative_account_no_lokkt,
  bseg.fistl AS funds_center_fistl,
  bseg.geber AS fund_geber,
  bseg.stbuk AS tax_company_code_stbuk,
  ${currency.amountWithDecimalShift("bseg.txbh2", "currency_decimal_h_hwae2")} AS lc2_tax_base_amount_txbh2,
  ${currency.amountWithDecimalShift("bseg.txbh3", "currency_decimal_h_hwae3")} AS lc3_tax_base_amount_txbh3,
  bseg.pprct AS partner_profit_ctr_pprct,
  bseg.xref1 AS reference_key_1_xref1,
  bseg.xref2 AS reference_key_2_xref2,
  bseg.kblnr AS earmarked_funds_kblnr,
  bseg.kblpos AS document_item_kblpos,
  ${currency.amountWithDecimalShift("bseg.sttax", "currency_decimal_h_waers")} AS statistical_tax_amount_in_document_crcy_sttax,
  bseg.fkber AS functional_area_fkber,
  bseg.obzei AS original_item_obzei,
  bseg.xnegp AS negative_posting_xnegp,
  bseg.rfzei AS payment_card_item_rfzei,
  bseg.ccbtc AS settlement_run_ccbtc,
  bseg.kkber AS credit_control_area_kkber,
  bseg.empfb AS payee_empfb,
  bseg.xref3 AS reference_key_3_xref3,
  bseg.dtws1 AS instruction_key_1_dtws1,
  bseg.dtws2 AS instruction_key_2_dtws2,
  bseg.dtws3 AS instruction_key_3_dtws3,
  bseg.dtws4 AS instruction_key_4_dtws4,
  bseg.gricd AS activity_code_gi_tax_gricd,
  bseg.grirg AS region_grirg,
  bseg.gityp AS distribution_type_gityp,
  bseg.xpypr AS payment_sent_xpypr,
  bseg.kidno AS payment_reference_kidno,
  ${currency.amountWithDecimalShift("bseg.absbt", "currency_decimal_h_waers")} AS hedged_amount_absbt,
  bseg.idxsp AS inflation_index_idxsp,
  bseg.linfv AS last_adjustment_date_linfv,
  bseg.kontt AS acct_assignment_cat_kontt,
  bseg.kontl AS account_assignment_kontl,
  bseg.uebgdat AS transfer_date_to_legal_dunning_proc_uebgdat,
  bseg.txdat AS tax_date_txdat,
  bseg.agzei AS clearing_item_agzei,
  bseg.pycur AS pmnt_currency_pycur,
  ${currency.amountWithDecimalShift("bseg.pyamt", "currency_decimal_pycur")} AS pmnt_curr_amnt_pyamt,
  bseg.bupla AS business_place_bupla,
  bseg.secco AS section_code_secco,
  bseg.lstar AS activity_type_lstar,
  bseg.cession_kz AS ar_pledging_ind_cession_kz,
  bseg.prznr AS business_process_prznr,
  ${currency.amountWithDecimalShift("bseg.ppdiff", "currency_decimal_h_hwaer")} AS difference_realized_ppdiff,
  ${currency.amountWithDecimalShift("bseg.ppdif2", "currency_decimal_h_hwae2")} AS difference_realized_ppdif2,
  ${currency.amountWithDecimalShift("bseg.ppdif3", "currency_decimal_h_hwae3")} AS difference_realized_ppdif3,
  ${currency.amountWithDecimalShift("bseg.penlc1", "currency_decimal_h_hwaer")} AS penalty_chge_in_lc_penlc1,
  ${currency.amountWithDecimalShift("bseg.penlc2", "currency_decimal_h_hwae2")} AS pen_charge_in_lc2_penlc2,
  ${currency.amountWithDecimalShift("bseg.penlc3", "currency_decimal_h_hwae3")} AS pen_charge_in_lc3_penlc3,
  ${currency.amountWithDecimalShift("bseg.penfc", "currency_decimal_h_waers")} AS penalty_charge_penfc,
  bseg.pendays AS days_in_arrears_pendays,
  bseg.penrc AS reason_for_late_pmnt_penrc,
  bseg.grant_nbr AS grant_grant_nbr,
  ${currency.amountWithDecimalShift("bseg.sctax", "currency_decimal_h_waers")} AS tax_portion_fi_ca_local_currency_sctax,
  bseg.fkber_long AS functional_area_fkber_long,
  bseg.gmvkz AS transfer_to_execution_gmvkz,
  bseg.srtype AS type_of_addtnl_recvabl_srtype,
  bseg.intreno AS real_estate_code_intreno,
  bseg.measure AS funded_program_measure,
  bseg.auggj AS clearing_fiscal_year_auggj,
  bseg.ppa_ex_ind AS ppa_exclude_ind_ppa_ex_ind,
  bseg.docln AS line_item_docln,
  bseg.segment AS segment,
  bseg.psegment AS partner_segment_psegment,
  bseg.pfkber AS partner_func_area_pfkber,
  bseg.hktid AS account_id_hktid,
  bseg.kstar AS cost_element_kstar,
  bseg.xlgclr AS ledger_group_specific_clearing_xlgclr,
  bseg.taxps AS document_item_number_for_tax_document_taxps,
  bseg.pays_prov AS payment_service_provider_pays_prov,
  bseg.pays_tran AS payment_ref_of_payment_service_provider_pays_tran,
  bseg.mndid AS mandate_reference_mndid,
  bseg.xfrge_bseg AS payment_is_released_xfrge_bseg,
  bseg.awtyp AS reference_procedure_awtyp,
  bseg.awkey AS object_key_awkey,
  bseg.awsys AS log_system_source_awsys,
  bseg.posnr AS position_posnr,
  bseg.buzei_sender AS item_in_sender_system_buzei_sender,
  bseg.h_monat AS posting_period_h_monat,
  bseg.h_bstat AS document_status_h_bstat,
  bseg.h_budat AS posting_date_h_budat,
  bseg.h_bldat AS document_date_h_bldat,
  bseg.h_waers AS currency_h_waers,
  bseg.h_blart AS document_type_h_blart,
  bseg.h_hwaer AS local_currency_h_hwaer,
  bseg.h_hwae2 AS local_currency_2_h_hwae2,
  bseg.h_hwae3 AS local_currency_3_h_hwae3,
  bseg.sk1dt AS cash_disc_1_due_date_sk1dt,
  bseg.sk2dt AS cash_disc_2_due_date_sk2dt,
  bseg.prctr_drvtn_source_type AS profit_center_drvtn_srce_type_prctr_drvtn_source_type,
  bseg.fqftype AS flow_type_fqftype,
  bseg.lqitem AS liquidity_item_lqitem,
  bseg.gkont AS offsetting_account_gkont,
  bseg.gkart AS offsetting_account_type_gkart,
  bseg.ghkon AS offsetting_account_in_general_ledger_ghkon,
  bseg.squan AS quantity_sign_squan,
  bseg.anln2_pn AS sub_number_anln2_pn,
  bseg.bwasl_pn AS transaction_type_bwasl_pn,
  bseg.bzdat_pn AS asset_value_date_bzdat_pn,
  bseg.xvabg_pn AS complete_retirement_xvabg_pn,
  ${currency.amountWithDecimalShift("bseg.anbtr_pn", "currency_decimal_h_waers")} AS amount_posted_anbtr_pn,
  bseg.prozs_pn AS percentage_rate_prozs_pn,
  bseg.acdoc_eew_dummy AS dummy_acdoc_eew_dummy,
  bseg.dummy_incl_eew_cobl AS dummy_dummy_incl_eew_cobl,
  bseg.acrobjtype AS accrual_object_type_acrobjtype,
  bseg.acrlogsys AS logical_system_of_accrual_object_acrlogsys,
  bseg.acrobj_id AS accrual_object_acrobj_id,
  bseg.acrsobj_id AS accrual_subobject_acrsobj_id,
  bseg.acritmtype AS accrual_item_type_acritmtype,
  bseg.acrvaldat AS accrual_value_date_acrvaldat,
  bseg.valobjtype AS type_of_the_financial_valuation_object_valobjtype,
  bseg.valobj_id AS financial_valuation_object_valobj_id,
  bseg.valsobj_id AS financial_valuation_subobject_valsobj_id,
  bseg.netdt AS net_due_date_netdt,
  bseg.risk_class AS risk_class,
  bseg.sdm_version AS sdm_versioning_sdm_version,
  bseg.glo_ref1 AS country_specific_reference_1_glo_ref1,
  bseg.re_bukrs AS company_code_re_bukrs,
  bseg.re_account AS expense_or_revenue_account_in_cl_re_account,
  bseg.pgeber AS partner_fund_pgeber,
  bseg.pgrant_nbr AS partner_grant_pgrant_nbr,
  bseg.budget_pd AS budget_period_budget_pd,
  bseg.pbudget_pd AS par_budget_per_pbudget_pd,
  bseg.j_1tpbupl AS branch_code_j_1tpbupl,
  bseg.perop_beg AS billing_period_of_performance_start_date_perop_beg,
  bseg.perop_end AS billing_period_of_performance_end_date_perop_end,
  bseg.fastpay AS fast_pay_indicator_fastpay,
  bseg.ignr_ivref AS ignore_invoice_reference_ignr_ivref,
  bseg.fmfgus_key AS us_government_fields_fmfgus_key,
  bseg.fmxdocnr AS fm_reference_document_number_fmxdocnr,
  bseg.fmxyear AS fm_reference_year_fmxyear,
  bseg.fmxdocln AS fm_reference_line_item_fmxdocln,
  bseg.fmxzekkn AS fm_reference_sequence_account_assignment_fmxzekkn,
  bseg.prodper AS production_month_prodper,
  bseg.gst_part AS gst_partner_gst_part,
  bseg.plc_sup AS place_of_supply_plc_sup,
  bseg.hsn_sac AS hsn_sac_code_hsn_sac,
  bseg.irn AS invoice_reference_number_irn,
  bseg.recrf AS st_recredit_flag_recrf,
  bseg.bdgt_account AS budget_account_bdgt_account,
  bseg.bdgt_account_cocode AS company_code_for_budget_account_bdgt_account_cocode,
  bseg.inward_no AS incoming_doc_nmbr_inward_no,
  bseg.inward_dt AS incoming_doc_date_inward_dt,
  bseg.ground_no AS payt_ground_no,
  bseg.ground_dt AS payt_ground_date_ground_dt,
  bseg.ground_typ AS payt_against_ground_typ,
  bseg.pymtkey AS payment_proposal_key_pymtkey,
  dimensional_date_augdt.cal_year AS year_of_clearing_date_augdt,
  dimensional_date_augdt.cal_month AS month_of_clearing_date_augdt,
  dimensional_date_augdt.cal_quarter AS quarter_of_clearing_date_augdt,
  dimensional_date_augdt.cal_week AS week_of_clearing_date_augdt,
  dimensional_date_valut.cal_year AS year_of_value_date_valut,
  dimensional_date_valut.cal_month AS month_of_value_date_valut,
  dimensional_date_valut.cal_quarter AS quarter_of_value_date_valut,
  dimensional_date_valut.cal_week AS week_of_value_date_valut,
  GREATEST(
    IFNULL(bseg.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
    IFNULL(bkpf.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00'))
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bseg")} AS bseg
LEFT JOIN ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bkpf")} AS bkpf
  ON bseg.mandt = bkpf.mandt
  AND bseg.bukrs = bkpf.bukrs
  AND bseg.belnr = bkpf.belnr
  AND bseg.gjahr = bkpf.gjahr
LEFT JOIN currency_decimal AS currency_decimal_h_waers
  ON bseg.h_waers = currency_decimal_h_waers.currkey
LEFT JOIN ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "t005")} AS t005
  ON bseg.mandt = t005.mandt
  AND bseg.tax_country = t005.land1
LEFT JOIN currency_decimal AS currency_decimal_country_waers
  ON t005.waers = currency_decimal_country_waers.currkey
LEFT JOIN currency_decimal AS currency_decimal_h_hwaer
  ON bseg.h_hwaer = currency_decimal_h_hwaer.currkey
LEFT JOIN currency_decimal AS currency_decimal_h_hwae2
  ON bseg.h_hwae2 = currency_decimal_h_hwae2.currkey
LEFT JOIN currency_decimal AS currency_decimal_h_hwae3
  ON bseg.h_hwae3 = currency_decimal_h_hwae3.currkey
LEFT JOIN currency_decimal AS currency_decimal_pswsl
  ON bseg.pswsl = currency_decimal_pswsl.currkey
LEFT JOIN currency_decimal AS currency_decimal_pycur
  ON bseg.pycur = currency_decimal_pycur.currkey
LEFT JOIN date_dimension AS dimensional_date_augdt
  ON bseg.augdt = dimensional_date_augdt.date
LEFT JOIN date_dimension AS dimensional_date_valut
  ON bseg.valut = dimensional_date_valut.date
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["bseg", "bkpf"])
])}
`
);
