# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ecc:
  agency_settlement_document_headers:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    dataformTags: [sap, sales, sap_sd, sap_mm, source_aligned_product, 
        transactional, daily]
  agency_settlement_document_items:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    dataformTags: [sap, sales, sap_sd, sap_mm, source_aligned_product, 
        transactional, daily]
s4:
  agency_settlement_document_headers:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    dataformTags: [sap, sales, sap_sd, sap_mm, source_aligned_product, 
        transactional, daily]
  agency_settlement_document_items:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    dataformTags: [sap, sales, sap_sd, sap_mm, source_aligned_product, 
        transactional, daily]
