/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "document_number_vbeln",
    "item_number_posnr"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
), currency_decimal AS (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  vbap.mandt AS client_mandt,
  vbap.vbeln AS document_number_vbeln,
  vbap.posnr AS item_number_posnr,
  vbap.matnr AS material_number_matnr,
  vbap.matwa AS material_entered_matwa,
  vbap.pmatn AS pricing_reference_material_pmatn,
  vbap.charg AS batch_number_charg,
  vbap.matkl AS material_group_matkl,
  vbap.arktx AS short_text_arktx,
  vbap.pstyv AS item_category_pstyv,
  vbap.posar AS item_type_posar,
  vbap.lfrel AS relevant_for_delivery_lfrel,
  vbap.fkrel AS relevant_for_billing_fkrel,
  vbap.uepos AS bom_item_level_uepos,
  vbap.grpos AS alternative_for_item_grpos,
  vbap.abgru AS rejection_reason_abgru,
  vbap.prodh AS product_hierarchy_prodh,
  vbap.zwert AS target_value_zwert,
  vbap.zmeng AS target_quantity_uo_m_zmeng,
  vbap.zieme AS target_quantity_uo_m_zieme,
  vbap.umziz AS base_target_conversion_factor_umziz,
  vbap.umzin AS conversion_factor_umzin,
  vbap.meins AS base_unit_of_measure_meins,
  vbap.smeng AS scale_quantity_smeng,
  vbap.ablfz AS rounding_quantity_for_delivery_ablfz,
  vbap.abdat AS reconciliation_date_abdat,
  vbap.absfz AS allowed_deviation_absfz,
  vbap.posex AS item_number_of_the_underlying_purchase_order_posex,
  vbap.kdmat AS customer_material_number_kdmat,
  vbap.kbver AS allowed_deviation_percent_kbver,
  vbap.kever AS days_by_which_the_quantity_can_be_shifted_kever,
  vbap.vkgru AS repair_processing_vkgru,
  vbap.vkaus AS usage_indicator_vkaus,
  vbap.grkor AS delivery_group_grkor,
  vbap.fmeng AS quantity_is_fixed_fmeng,
  vbap.uebtk AS unlimited_over_delivery_allowed_uebtk,
  vbap.uebto AS over_delivery_tolerance_limit_uebto,
  vbap.untto AS under_delivery_tolerance_limit_untto,
  vbap.faksp AS billing_block_for_item_faksp,
  vbap.atpkz AS replacement_part_atpkz,
  vbap.rkfkf AS form_of_billing_for_co_rkfkf,
  vbap.spart AS division_spart,
  vbap.gsber AS business_area_gsber,
  ${currency.amountWithDecimalShift("vbap.netwr", "currency_decimal")} AS net_value_of_the_sales_document_item_in_document_currency_netwr,
  vbap.waerk AS document_currency_waerk,
  vbap.antlf AS maximum_partial_deliveries_antlf,
  vbap.kztlf AS partial_delivery_at_item_level_kztlf,
  vbap.chspl AS batch_split_allowed_chspl,
  vbap.kwmeng AS cumulative_order_quantity_kwmeng,
  vbap.lsmeng AS cumulative_target_delivery_qty_lsmeng,
  vbap.kbmeng AS cumulative_confirmed_quantity_kbmeng,
  vbap.klmeng AS cumulative_confirmed_quantity_in_ba_se_uo_m_klmeng,
  vbap.vrkme AS sales_unit_vrkme,
  vbap.umvkz AS numerator_qty_umvkz,
  vbap.umvkn AS denominator_qty_umvkn,
  vbap.brgew AS gross_weight_of_item_brgew,
  vbap.ntgew AS net_weight_of_item_ntgew,
  vbap.gewei AS weight_unit_gewei,
  vbap.volum AS volume_of_the_item_volum,
  vbap.voleh AS volume_unit_voleh,
  vbap.vbelv AS originating_document_vbelv,
  vbap.posnv AS originating_item_posnv,
  vbap.vgbel AS reference_document_vgbel,
  vbap.vgpos AS reference_item_vgpos,
  vbap.voref AS reference_indicator_voref,
  vbap.upflu AS update_indicator_upflu,
  vbap.erlre AS completion_rule_for_quotation_erlre,
  vbap.lprio AS delivery_priority_lprio,
  vbap.werks AS plant_werks,
  vbap.lgort AS storage_location_lgort,
  vbap.vstel AS shipping_receiving_point_vstel,
  vbap.route AS route_route,
  vbap.stkey AS bom_origin_stkey,
  vbap.stdat AS bom_date_stdat,
  vbap.stlnr AS bom_stlnr,
  vbap.awahr AS order_probability_of_the_item_awahr,
  vbap.erdat AS creation_date_erdat,
  vbap.ernam AS created_by_ernam,
  vbap.erzet AS creation_time_erzet,
  vbap.taxm1 AS tax_classification1_taxm1,
  vbap.taxm2 AS tax_classification2_taxm2,
  vbap.taxm3 AS tax_classification3_taxm3,
  vbap.taxm4 AS tax_classification4_taxm4,
  vbap.taxm5 AS tax_classification5_taxm5,
  vbap.taxm6 AS tax_classification6_taxm6,
  vbap.taxm7 AS tax_classification7_taxm7,
  vbap.taxm8 AS tax_classification8_taxm8,
  vbap.taxm9 AS tax_classification9_taxm9,
  vbap.vbeaf AS fixed_shipping_processing_time_in_days_vbeaf,
  vbap.vbeav AS variable_shipping_processing_time_in_days_vbeav,
  vbap.vgref AS preceding_document_has_resulted_from_reference_vgref,
  ${currency.amountWithDecimalShift("vbap.netpr", "currency_decimal")} AS net_price_netpr,
  vbap.kpein AS condition_pricing_unit_kpein,
  vbap.kmein AS condition_unit_kmein,
  vbap.shkzg AS returns_item_shkzg,
  vbap.sktof AS cash_discount_indicator_sktof,
  vbap.mtvfp AS checking_group_for_availability_check_mtvfp,
  vbap.sumbd AS summing_up_of_requirements_sumbd,
  vbap.kondm AS material_pricing_group_kondm,
  vbap.ktgrm AS account_assignment_group_for_this_material_ktgrm,
  vbap.bonus AS volume_rebate_group_bonus,
  vbap.provg AS commission_group_provg,
  vbap.prsok AS pricing_is_ok_prsok,
  vbap.bwtar AS valuation_type_bwtar,
  vbap.bwtex AS separate_valuation_bwtex,
  vbap.xchpf AS batch_management_requirement_indicator_xchpf,
  vbap.xchar AS batch_management_indicator_xchar,
  vbap.lfmng AS minimum_delivery_quantity_in_delivery_note_processing_lfmng,
  vbap.stafo AS update_group_for_statistics_update_stafo,
  ${currency.amountWithDecimalShift("vbap.wavwr", "currency_decimal")} AS cost_in_document_currency_wavwr,
  vbap.kzwi1 AS sub_total1_from_pricing_procedure_for_condition_kzwi1,
  vbap.kzwi2 AS sub_total2_from_pricing_procedure_for_condition_kzwi2,
  vbap.kzwi3 AS sub_total3_from_pricing_procedure_for_condition_kzwi3,
  vbap.kzwi4 AS sub_total4_from_pricing_procedure_for_condition_kzwi4,
  vbap.kzwi5 AS sub_total5_from_pricing_procedure_for_condition_kzwi5,
  vbap.kzwi6 AS sub_total6_from_pricing_procedure_for_condition_kzwi6,
  vbap.stcur AS exchange_rate_for_statistics_stcur,
  vbap.aedat AS last_changed_on_aedat,
  vbap.ean11 AS international_article_number_ean11,
  vbap.fixmg AS delivery_date_and_quantity_fixed_fixmg,
  vbap.prctr AS profit_center_prctr,
  vbap.mvgr1 AS material_group1_mvgr1,
  vbap.mvgr2 AS material_group2_mvgr2,
  vbap.mvgr3 AS material_group3_mvgr3,
  vbap.mvgr4 AS material_group4_mvgr4,
  vbap.mvgr5 AS material_group5_mvgr5,
  vbap.kmpmg AS component_quantity_kmpmg,
  vbap.sugrd AS reason_for_material_substitution_sugrd,
  vbap.sobkz AS special_stock_indicator_sobkz,
  vbap.vpzuo AS allocation_indicator_vpzuo,
  vbap.paobjnr AS profitability_segment_number_paobjnr,
  vbap.ps_psp_pnr AS wbs_element_ps_psp_pnr,
  vbap.aufnr AS order_number_aufnr,
  vbap.vpmat AS planning_material_vpmat,
  vbap.vpwrk AS planning_plant_vpwrk,
  vbap.prbme AS base_unit_of_measure_for_product_group_prbme,
  vbap.umref AS conversion_factor_quantities_umref,
  vbap.knttp AS account_assignment_category_knttp,
  vbap.kzvbr AS consumption_posting_kzvbr,
  vbap.sernr AS bom_explosion_number_sernr,
  vbap.objnr AS object_number_at_item_level_objnr,
  vbap.abgrs AS results_analysis_key_abgrs,
  vbap.bedae AS requirements_type_bedae,
  vbap.cmpre AS item_credit_price_cmpre,
  vbap.cmtfg AS credit_block_cmtfg,
  vbap.cmpnt AS relevant_for_credit_cmpnt,
  vbap.cuobj AS configuration_cuobj,
  vbap.cuobj_ch AS internal_object_number_of_the_batch_classification_cuobj_ch,
  vbap.cepok AS status_expected_price_cepok,
  vbap.koupd AS condition_update_koupd,
  vbap.serail AS serial_number_profile_serail,
  vbap.anzsn AS number_of_serial_numbers_anzsn,
  vbap.nachl AS customer_has_not_posted_goods_receipt_nachl,
  vbap.magrv AS packaging_materials_magrv,
  vbap.mprok AS status_manual_price_change_mprok,
  vbap.vgtyp AS preceding_doc_category_vgtyp,
  vbap.prosa AS id_for_material_determination_prosa,
  vbap.uepvw AS id_for_higher_level_item_usage_uepvw,
  vbap.kalnr AS cost_estimate_number_kalnr,
  vbap.klvar AS costing_variant_klvar,
  vbap.sposn AS bom_item_number_sposn,
  vbap.kowrr AS statistical_values_kowrr,
  vbap.stadat AS statistics_date_stadat,
  vbap.exart AS business_transaction_type_for_foreign_trade_exart,
  vbap.prefe AS import_export_flag_prefe,
  vbap.knumh AS number_of_condition_record_knumh,
  vbap.clint AS internal_class_number_clint,
  vbap.stlty AS bom_category_stlty,
  vbap.stlkn AS bom_item_node_number_stlkn,
  vbap.stpoz AS internal_counter_stpoz,
  vbap.stman AS inconsistent_configuration_stman,
  vbap.zschl_k AS over_head_key_zschl_k,
  vbap.kalsm_k AS costing_sheet_kalsm_k,
  vbap.kalvar AS costing_variant_kalvar,
  vbap.kosch AS product_allocation_kosch,
  vbap.upmat AS pricing_reference_material_upmat,
  vbap.ukonm AS material_pricing_group_ukonm,
  vbap.mfrgr AS material_freight_group_mfrgr,
  vbap.plavo AS planning_release_regulation_plavo,
  vbap.kannr AS kanban_kannr,
  vbap.cmpre_flt AS item_credit_price_cmpre_flt,
  vbap.abfor AS form_of_payment_guarantee_abfor,
  vbap.abges AS guaranteed_factor_abges,
  vbap.wktnr AS value_contract_no_wktnr,
  vbap.wktps AS value_contract_item_wktps,
  vbap.skopf AS assortment_module_skopf,
  vbap.kzbws AS valuationof_special_stock_kzbws,
  vbap.wgru1 AS material_group_hierarchy1_wgru1,
  vbap.wgru2 AS material_group_hierarchy2_wgru2,
  vbap.knuma_pi AS promotion_knuma_pi,
  vbap.knuma_ag AS sales_deal_knuma_ag,
  vbap.kzfme AS leading_uo_m_kzfme,
  vbap.lstanr AS free_goods_delivery_control_lstanr,
  vbap.techs AS parameter_variant_techs,
  ${currency.amountWithDecimalShift("vbap.mwsbp", "currency_decimal")} AS tax_amount_in_document_currency_mwsbp,
  vbap.berid AS mrp_area_berid,
  vbap.pctrf AS profit_center_for_billing_pctrf,
  vbap.stockloc AS managing_location_stockloc,
  vbap.sloctype AS type_of_first_inventory_sloctype,
  vbap.msr_ret_reason AS return_reason_msr_ret_reason,
  vbap.msr_refund_code AS returns_refund_code_msr_refund_code,
  vbap.msr_approv_block AS approval_block_msr_approv_block,
  vbap.nrab_knumh AS condition_record_number_nrab_knumh,
  vbap.trmrisk_relevant AS risk_relevancy_in_sales_trmrisk_relevant,
  vbap.handoverloc AS location_for_a_physical_hand_over_of_goods_handoverloc,
  vbap.handoverdate AS hand_over_date_at_the_hand_over_location_handoverdate,
  vbap.handovertime AS hand_over_time_at_the_hand_over_location_handovertime,
  vbap.tc_aut_det AS tax_code_automatically_determined_tc_aut_det,
  vbap.manual_tc_reason AS manual_tax_code_re_a_son_manual_tc_reason,
  vbap.fiscal_incentive AS tax_incentive_type_fiscal_incentive,
  vbap.fiscal_incentive_id AS incentive_id_fiscal_incentive_id,
  vbap.spcsto AS not_a_fiscal_special_case_for_cfop_determination_spcsto,
  vbap.kostl AS cost_center_kostl,
  vbap.fonds AS fund_fonds,
  vbap.fistl AS funds_center_fistl,
  vbap.fkber AS functional_area_fkber,
  dimensional_date_erdat.cal_year AS year_of_creation_date_erdat,
  dimensional_date_erdat.cal_month AS month_of_creation_date_erdat,
  dimensional_date_erdat.cal_week AS week_of_creation_date_erdat,
  dimensional_date_erdat.day_of_month AS day_of_month_of_creation_date_erdat,
  dimensional_date_erdat.cal_quarter AS quarter_of_creation_date_erdat,
  IFNULL(
    vbap.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "vbap")} AS vbap
LEFT JOIN currency_decimal
  ON vbap.waerk = currency_decimal.currkey
LEFT JOIN date_dimension AS dimensional_date_erdat
  ON vbap.erdat = dimensional_date_erdat.date
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["vbap"])
])}
`,
);
