/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "company_code_bukrs",
    "customer_kunnr",
    "special_gl_transaction_type_umsks",
    "special_gl_indicator_umskz",
    "clearing_date_augdt",
    "clearing_document_augbl",
    "assignment_zuonr",
    "fiscal_year_gjahr",
    "document_number_belnr",
    "line_item_buzei"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  bsid.mandt AS client_mandt,
  bsid.bukrs AS company_code_bukrs,
  bsid.kunnr AS customer_kunnr,
  bsid.umsks AS special_gl_transaction_type_umsks,
  bsid.umskz AS special_gl_indicator_umskz,
  bsid.augdt AS clearing_date_augdt,
  bsid.augbl AS clearing_document_augbl,
  bsid.zuonr AS assignment_zuonr,
  bsid.gjahr AS fiscal_year_gjahr,
  bsid.belnr AS document_number_belnr,
  bsid.buzei AS line_item_buzei,
  bsid.budat AS posting_date_budat,
  bsid.bldat AS document_date_bldat,
  bsid.cpudt AS entry_date_cpudt,
  bsid.waers AS currency_waers,
  bsid.xblnr AS reference_xblnr,
  bsid.blart AS document_type_blart,
  bsid.monat AS posting_period_monat,
  bsid.bschl AS posting_key_bschl,
  bsid.zumsk AS target_special_gl_indicator_zumsk,
  bsid.shkzg AS debit_credit_indicator_shkzg,
  bsid.gsber AS business_area_gsber,
  bsid.mwskz AS tax_code_mwskz,
  bsid.dmbtr AS amount_in_local_currency_dmbtr,
  bsid.wrbtr AS amount_wrbtr,
  bsid.mwsts AS local_currency_tax_amount_mwsts,
  bsid.wmwst AS tax_amount_wmwst,
  bsid.bdiff AS valuation_difference_bdiff,
  bsid.bdif2 AS valuation_difference_2_bdif2,
  bsid.sgtxt AS text_sgtxt,
  bsid.projn AS not_in_use_projn,
  bsid.aufnr AS order_aufnr,
  bsid.anln1 AS asset_anln1,
  bsid.anln2 AS sub_number_anln2,
  bsid.saknr AS gl_account_saknr,
  bsid.hkont AS gl_account_hkont,
  bsid.fkont AS financial_budget_fkont,
  bsid.filkd AS branch_account_filkd,
  bsid.zfbdt AS baseline_payment_date_zfbdt,
  bsid.zterm AS terms_of_payment_zterm,
  bsid.zbd1t AS days_1_zbd1t,
  bsid.zbd2t AS days_2_zbd2t,
  bsid.zbd3t AS days_net_zbd3t,
  bsid.zbd1p AS cash_discount_percent_1_zbd1p,
  bsid.zbd2p AS cash_discount_percent_2_zbd2p,
  bsid.skfbt AS cash_discount_base_skfbt,
  bsid.sknto AS cash_discount_amount_sknto,
  bsid.wskto AS cash_discount_amount_wskto,
  bsid.zlsch AS payment_method_zlsch,
  bsid.zlspr AS payment_block_zlspr,
  bsid.zbfix AS fixed_zbfix,
  bsid.hbkid AS house_bank_hbkid,
  bsid.bvtyp AS part_bank_type_bvtyp,
  bsid.rebzg AS invoice_reference_rebzg,
  bsid.rebzj AS fiscal_year_rebzj,
  bsid.rebzz AS line_item_rebzz,
  bsid.samnr AS collective_invoice_samnr,
  bsid.anfbn AS bill_of_exchange_payment_request_anfbn,
  bsid.anfbj AS fiscal_year_of_the_bill_of_exchange_payment_request_document_anfbj,
  bsid.anfbu AS company_code_anfbu,
  bsid.mansp AS dunning_block_mansp,
  bsid.mschl AS dunning_key_mschl,
  bsid.madat AS last_dunned_madat,
  bsid.manst AS dunning_level_manst,
  bsid.maber AS dunning_area_maber,
  bsid.xnetb AS net_document_type_xnetb,
  bsid.xanet AS indicator_down_payment_in_net_procedure_xanet,
  bsid.xcpdd AS individ_set_xcpdd,
  bsid.xinve AS investment_id_xinve,
  bsid.xzahl AS payment_transaction_xzahl,
  bsid.mwsk1 AS tax_code_mwsk1,
  bsid.dmbt1 AS amount_dmbt1,
  bsid.wrbt1 AS amount_wrbt1,
  bsid.mwsk2 AS tax_code_mwsk2,
  bsid.dmbt2 AS amount_dmbt2,
  bsid.wrbt2 AS amount_wrbt2,
  bsid.mwsk3 AS tax_code_mwsk3,
  bsid.dmbt3 AS amount_dmbt3,
  bsid.wrbt3 AS amount_wrbt3,
  bsid.bstat AS document_status_bstat,
  bsid.vbund AS trading_partner_vbund,
  bsid.vbeln AS billing_document_vbeln,
  bsid.rebzt AS follow_on_document_type_rebzt,
  bsid.stceg AS vat_registration_number_stceg,
  bsid.egbld AS country_of_destinat_egbld,
  bsid.eglld AS supplying_country_eglld,
  bsid.rstgr AS reason_code_rstgr,
  bsid.vertt AS contract_type_vertt,
  bsid.vertn AS contract_number_vertn,
  bsid.vbewa AS flow_type_vbewa,
  bsid.wverw AS bill_of_exchange_usage_type_wverw,
  bsid.projk AS wbs_element_projk,
  bsid.fipos AS commitment_item_fipos,
  bsid.nplnr AS network_nplnr,
  bsid.aufpl AS operation_task_list_number_aufpl,
  bsid.aplzl AS counter_aplzl,
  bsid.xegdr AS eu_triangular_deal_xegdr,
  bsid.dmbe2 AS lc2_amount_dmbe2,
  bsid.dmbe3 AS lc3_amount_dmbe3,
  bsid.dmb21 AS amount_dmb21,
  bsid.dmb22 AS amount_dmb22,
  bsid.dmb23 AS amount_dmb23,
  bsid.dmb31 AS amount_dmb31,
  bsid.dmb32 AS amount_dmb32,
  bsid.dmb33 AS amount_dmb33,
  bsid.bdif3 AS valuation_difference_3_bdif3,
  bsid.xragl AS reverse_clearing_xragl,
  bsid.uzawe AS payment_meth_supplement_uzawe,
  bsid.xstov AS reversal_flag_xstov,
  bsid.mwst2 AS lc2_tax_amount_mwst2,
  bsid.mwst3 AS lc3_tax_amount_mwst3,
  bsid.sknt2 AS lc2_cash_discount_amnt_sknt2,
  bsid.sknt3 AS lc3_cash_discount_amnt_sknt3,
  bsid.xref1 AS reference_key_1_xref1,
  bsid.xref2 AS reference_key_2_xref2,
  bsid.xarch AS archived_xarch,
  bsid.pswsl AS general_ledger_currency_pswsl,
  bsid.pswbt AS general_ledger_amount_pswbt,
  bsid.lzbkz AS scb_indicator_lzbkz,
  bsid.landl AS supplying_country_landl,
  bsid.imkey AS real_estate_key_imkey,
  bsid.vbel2 AS sales_document_vbel2,
  bsid.posn2 AS sales_document_item_posn2,
  bsid.eten2 AS schedule_line_number_eten2,
  bsid.fistl AS funds_center_fistl,
  bsid.geber AS fund_geber,
  bsid.dabrz AS reference_date_dabrz,
  bsid.xnegp AS negative_posting_xnegp,
  bsid.kostl AS cost_center_kostl,
  bsid.rfzei AS payment_card_item_rfzei,
  bsid.kkber AS credit_control_area_kkber,
  bsid.empfb AS payee_empfb,
  bsid.prctr AS profit_center_prctr,
  bsid.xref3 AS reference_key_3_xref3,
  bsid.qsskz AS withholding_tax_code_qsskz,
  bsid.zinkz AS interest_block_zinkz,
  bsid.dtws1 AS instruction_1_dtws1,
  bsid.dtws2 AS instruction_2_dtws2,
  bsid.dtws3 AS instruction_3_dtws3,
  bsid.dtws4 AS instruction_4_dtws4,
  bsid.xpypr AS payment_sent_xpypr,
  bsid.kidno AS payment_reference_kidno,
  bsid.absbt AS credit_management_hedged_amount_absbt,
  bsid.ccbtc AS payment_cards_settlement_run_ccbtc,
  bsid.pycur AS payment_currency_pycur,
  bsid.pyamt AS payment_curr_amnt_pyamt,
  bsid.bupla AS business_place_bupla,
  bsid.secco AS section_code_secco,
  bsid.cession_kz AS accounts_receivable_pledging_indicator_cession_kz,
  bsid.ppdiff AS difference_realized_ppdiff,
  bsid.ppdif2 AS difference_realized_ppdif2,
  bsid.ppdif3 AS difference_realized_ppdif3,
  bsid.kblnr AS earmarked_funds_kblnr,
  bsid.kblpos AS document_item_kblpos,
  bsid.grant_nbr AS grant_nbr,
  bsid.gmvkz AS transfer_to_execution_gmvkz,
  bsid.srtype AS type_of_addtnl_recvabl_srtype,
  bsid.lotkz AS request_number_lotkz,
  bsid.fkber AS functional_area_fkber,
  bsid.intreno AS real_estate_code_intreno,
  bsid.pprct AS partner_profit_center_pprct,
  bsid.buzid AS line_item_id_buzid,
  bsid.auggj AS clearing_fiscal_year_auggj,
  bsid.hktid AS account_id_hktid,
  bsid.budget_pd AS budget_period_budget_pd,
  bsid.kontt AS account_assignment_cat_kontt,
  bsid.kontl AS account_assignment_kontl,
  bsid.uebgdat AS transfer_date_to_legal_dunning_proc_uebgdat,
  bsid.vname AS joint_venture_vname,
  bsid.egrup AS equity_group_egrup,
  bsid.btype AS billing_indicator_btype,
  bsid.propmano AS mandate_propmano,
  IFNULL(bsid.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bsid")} AS bsid
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["bsid"])
])}
`
);
