/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "company_code_bukrs",
    "customer_kunnr",
    "special_gl_transaction_type_umsks",
    "special_gl_indicator_umskz",
    "clearing_date_augdt",
    "clearing_document_augbl",
    "assignment_zuonr",
    "fiscal_year_gjahr",
    "document_number_belnr",
    "line_item_buzei"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  bsad.mandt AS client_mandt,
  bsad.bukrs AS company_code_bukrs,
  bsad.kunnr AS customer_kunnr,
  bsad.umsks AS special_gl_transaction_type_umsks,
  bsad.umskz AS special_gl_indicator_umskz,
  bsad.augdt AS clearing_date_augdt,
  bsad.augbl AS clearing_document_augbl,
  bsad.zuonr AS assignment_zuonr,
  bsad.gjahr AS fiscal_year_gjahr,
  bsad.belnr AS document_number_belnr,
  bsad.buzei AS line_item_buzei,
  bsad.budat AS posting_date_budat,
  bsad.bldat AS document_date_bldat,
  bsad.cpudt AS entry_date_cpudt,
  bsad.waers AS currency_waers,
  bsad.xblnr AS reference_xblnr,
  bsad.blart AS document_type_blart,
  bsad.monat AS posting_period_monat,
  bsad.bschl AS posting_key_bschl,
  bsad.zumsk AS target_special_gl_indicator_zumsk,
  bsad.shkzg AS debit_credit_indicator_shkzg,
  bsad.gsber AS business_area_gsber,
  bsad.mwskz AS tax_code_mwskz,
  bsad.dmbtr AS amount_in_local_currency_dmbtr,
  bsad.wrbtr AS amount_wrbtr,
  bsad.mwsts AS local_currency_tax_amount_mwsts,
  bsad.wmwst AS tax_amount_wmwst,
  bsad.bdiff AS valuation_difference_bdiff,
  bsad.bdif2 AS valuation_difference_2_bdif2,
  bsad.sgtxt AS text_sgtxt,
  bsad.projn AS not_in_use_projn,
  bsad.aufnr AS order_aufnr,
  bsad.anln1 AS asset_anln1,
  bsad.anln2 AS sub_number_anln2,
  bsad.saknr AS gl_account_saknr,
  bsad.hkont AS gl_account_hkont,
  bsad.fkont AS financial_budget_fkont,
  bsad.filkd AS branch_account_filkd,
  bsad.zfbdt AS baseline_payment_date_zfbdt,
  bsad.zterm AS terms_of_payment_zterm,
  bsad.zbd1t AS days_1_zbd1t,
  bsad.zbd2t AS days_2_zbd2t,
  bsad.zbd3t AS days_net_zbd3t,
  bsad.zbd1p AS cash_discount_percent_1_zbd1p,
  bsad.zbd2p AS cash_discount_percent_2_zbd2p,
  bsad.skfbt AS cash_discount_base_skfbt,
  bsad.sknto AS cash_discount_amount_sknto,
  bsad.wskto AS cash_discount_amount_wskto,
  bsad.zlsch AS payment_method_zlsch,
  bsad.zlspr AS payment_block_zlspr,
  bsad.zbfix AS fixed_zbfix,
  bsad.hbkid AS house_bank_hbkid,
  bsad.bvtyp AS part_bank_type_bvtyp,
  bsad.rebzg AS invoice_reference_rebzg,
  bsad.rebzj AS fiscal_year_rebzj,
  bsad.rebzz AS line_item_rebzz,
  bsad.samnr AS collective_invoice_samnr,
  bsad.anfbn AS bill_of_exchange_payment_request_anfbn,
  bsad.anfbj AS fiscal_year_of_the_bill_of_exchange_payment_request_document_anfbj,
  bsad.anfbu AS company_code_anfbu,
  bsad.mansp AS dunning_block_mansp,
  bsad.mschl AS dunning_key_mschl,
  bsad.madat AS last_dunned_madat,
  bsad.manst AS dunning_level_manst,
  bsad.maber AS dunning_area_maber,
  bsad.xnetb AS net_document_type_xnetb,
  bsad.xanet AS indicator_down_payment_in_net_procedure_xanet,
  bsad.xcpdd AS individ_set_xcpdd,
  bsad.xinve AS investment_id_xinve,
  bsad.xzahl AS payment_transaction_xzahl,
  bsad.mwsk1 AS tax_code_mwsk1,
  bsad.dmbt1 AS amount_dmbt1,
  bsad.wrbt1 AS amount_wrbt1,
  bsad.mwsk2 AS tax_code_mwsk2,
  bsad.dmbt2 AS amount_dmbt2,
  bsad.wrbt2 AS amount_wrbt2,
  bsad.mwsk3 AS tax_code_mwsk3,
  bsad.dmbt3 AS amount_dmbt3,
  bsad.wrbt3 AS amount_wrbt3,
  bsad.bstat AS document_status_bstat,
  bsad.vbund AS trading_partner_vbund,
  bsad.vbeln AS billing_document_vbeln,
  bsad.rebzt AS follow_on_document_type_rebzt,
  bsad.stceg AS vat_registration_number_stceg,
  bsad.egbld AS country_of_destinat_egbld,
  bsad.eglld AS supplying_country_eglld,
  bsad.rstgr AS reason_code_rstgr,
  bsad.vertt AS contract_type_vertt,
  bsad.vertn AS contract_number_vertn,
  bsad.vbewa AS flow_type_vbewa,
  bsad.wverw AS bill_of_exchange_usage_type_wverw,
  bsad.projk AS wbs_element_projk,
  bsad.fipos AS commitment_item_fipos,
  bsad.nplnr AS network_nplnr,
  bsad.aufpl AS operation_task_list_number_aufpl,
  bsad.aplzl AS counter_aplzl,
  bsad.xegdr AS eu_triangular_deal_xegdr,
  bsad.dmbe2 AS lc2_amount_dmbe2,
  bsad.dmbe3 AS lc3_amount_dmbe3,
  bsad.dmb21 AS amount_dmb21,
  bsad.dmb22 AS amount_dmb22,
  bsad.dmb23 AS amount_dmb23,
  bsad.dmb31 AS amount_dmb31,
  bsad.dmb32 AS amount_dmb32,
  bsad.dmb33 AS amount_dmb33,
  bsad.bdif3 AS valuation_difference_3_bdif3,
  bsad.xragl AS reverse_clearing_xragl,
  bsad.uzawe AS payment_meth_supplement_uzawe,
  bsad.xstov AS reversal_flag_xstov,
  bsad.mwst2 AS lc2_tax_amount_mwst2,
  bsad.mwst3 AS lc3_tax_amount_mwst3,
  bsad.sknt2 AS lc2_cash_discount_amnt_sknt2,
  bsad.sknt3 AS lc3_cash_discount_amnt_sknt3,
  bsad.xref1 AS reference_key_1_xref1,
  bsad.xref2 AS reference_key_2_xref2,
  bsad.xarch AS archived_xarch,
  bsad.pswsl AS general_ledger_currency_pswsl,
  bsad.pswbt AS general_ledger_amount_pswbt,
  bsad.lzbkz AS scb_indicator_lzbkz,
  bsad.landl AS supplying_country_landl,
  bsad.imkey AS real_estate_key_imkey,
  bsad.vbel2 AS sales_document_vbel2,
  bsad.posn2 AS sales_document_item_posn2,
  bsad.eten2 AS schedule_line_number_eten2,
  bsad.fistl AS funds_center_fistl,
  bsad.geber AS fund_geber,
  bsad.dabrz AS reference_date_dabrz,
  bsad.xnegp AS negative_posting_xnegp,
  bsad.kostl AS cost_center_kostl,
  bsad.rfzei AS payment_card_item_rfzei,
  bsad.kkber AS credit_control_area_kkber,
  bsad.empfb AS payee_empfb,
  bsad.prctr AS profit_center_prctr,
  bsad.xref3 AS reference_key_3_xref3,
  bsad.qsskz AS withholding_tax_code_qsskz,
  bsad.zinkz AS interest_block_zinkz,
  bsad.dtws1 AS instruction_1_dtws1,
  bsad.dtws2 AS instruction_2_dtws2,
  bsad.dtws3 AS instruction_3_dtws3,
  bsad.dtws4 AS instruction_4_dtws4,
  bsad.xpypr AS payment_sent_xpypr,
  bsad.kidno AS payment_reference_kidno,
  bsad.absbt AS credit_management_hedged_amount_absbt,
  bsad.ccbtc AS payment_cards_settlement_run_ccbtc,
  bsad.pycur AS payment_currency_pycur,
  bsad.pyamt AS payment_curr_amnt_pyamt,
  bsad.bupla AS business_place_bupla,
  bsad.secco AS section_code_secco,
  bsad.cession_kz AS accounts_receivable_pledging_indicator_cession_kz,
  bsad.ppdiff AS difference_realized_ppdiff,
  bsad.ppdif2 AS difference_realized_ppdif2,
  bsad.ppdif3 AS difference_realized_ppdif3,
  bsad.kblnr AS earmarked_funds_kblnr,
  bsad.kblpos AS document_item_kblpos,
  bsad.grant_nbr AS grant_nbr,
  bsad.gmvkz AS transfer_to_execution_gmvkz,
  bsad.srtype AS type_of_addtnl_recvabl_srtype,
  bsad.lotkz AS request_number_lotkz,
  bsad.fkber AS functional_area_fkber,
  bsad.intreno AS real_estate_code_intreno,
  bsad.pprct AS partner_profit_center_pprct,
  bsad.buzid AS line_item_id_buzid,
  bsad.auggj AS clearing_fiscal_year_auggj,
  bsad.hktid AS account_id_hktid,
  bsad.budget_pd AS budget_period_budget_pd,
  bsad.kontt AS account_assignment_cat_kontt,
  bsad.kontl AS account_assignment_kontl,
  bsad.uebgdat AS transfer_date_to_legal_dunning_proc_uebgdat,
  bsad.vname AS joint_venture_vname,
  bsad.egrup AS equity_group_egrup,
  bsad.btype AS billing_indicator_btype,
  bsad.propmano AS mandate_propmano,
  IFNULL(bsad.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bsad")} AS bsad
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["bsad"])
])}
`
);
