/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_rclnt",
    "ledger_rldnr",
    "company_code_rbukrs",
    "fiscal_year_gjahr",
    "document_number_belnr",
    "line_item_docln"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  acdoca.rclnt AS client_rclnt,
  acdoca.rldnr AS ledger_rldnr,
  acdoca.rbukrs AS company_code_rbukrs,
  acdoca.gjahr AS fiscal_year_gjahr,
  acdoca.belnr AS document_number_belnr,
  acdoca.docln AS line_item_docln,
  acdoca.ryear AS gl_fiscal_year_ryear,
  acdoca.docnr_ld AS ledger_specific_document_number_docnr_ld,
  acdoca.rrcty AS record_type_rrcty,
  acdoca.rmvct AS transaction_type_rmvct,
  acdoca.vorgn AS gl_transaction_type_vorgn,
  acdoca.vrgng AS business_transaction_vrgng,
  acdoca.bttype AS bus_transac_type_bttype,
  acdoca.cbttype AS business_transaction_type_cbttype,
  acdoca.awtyp AS reference_procedure_awtyp,
  acdoca.awsys AS log_system_source_awsys,
  acdoca.aworg AS reference_org_unit_aworg,
  acdoca.awref AS reference_document_awref,
  acdoca.awitem AS ref_document_line_item_awitem,
  acdoca.awitgrp AS ref_document_item_group_awitgrp,
  acdoca.subta AS sub_transaction_subta,
  acdoca.xreversing AS is_reversing_another_item_xreversing,
  acdoca.xreversed AS is_reversed_xreversed,
  acdoca.xtruerev AS is_true_reversal_xtruerev,
  acdoca.awtyp_rev AS reversal_reference_transaction_awtyp_rev,
  acdoca.aworg_rev AS reversal_organizational_aworg_rev,
  acdoca.awref_rev AS reversal_reference_awref_rev,
  acdoca.awitem_rev AS reversal_reference_document_line_item_awitem_rev,
  acdoca.subta_rev AS reversal_sub_transaction_subta_rev,
  acdoca.xsettling AS is_settling_transferring_another_item_xsettling,
  acdoca.xsettled AS is_settled_transferred_xsettled,
  acdoca.prec_awtyp AS preceding_reftransact_prec_awtyp,
  acdoca.prec_awsys AS preceding_reflogsystem_prec_awsys,
  acdoca.prec_aworg AS preceding_reforgunit_prec_aworg,
  acdoca.prec_awref AS preceding_ref_document_prec_awref,
  acdoca.prec_awitem AS preceding_ref_document_line_item_prec_awitem,
  acdoca.prec_subta AS preceding_sub_transaction_prec_subta,
  acdoca.prec_awmult AS multiple_precref_id_prec_awmult,
  acdoca.prec_bukrs AS preceding_je_company_code_prec_bukrs,
  acdoca.prec_gjahr AS preceding_je_year_prec_gjahr,
  acdoca.prec_belnr AS preceding_je_document_number_prec_belnr,
  acdoca.prec_docln AS preceding_journal_entry_line_item_prec_docln,
  acdoca.xsecondary AS secondary_journal_entry_xsecondary,
  acdoca.closing_run_id AS uuid_of_financial_closing_run_closing_run_id,
  acdoca.orgl_change AS organizational_change_orgl_change,
  acdoca.src_awtyp AS source_document_type_src_awtyp,
  acdoca.src_awsys AS source_document_system_src_awsys,
  acdoca.src_aworg AS source_document_org_unit_src_aworg,
  acdoca.src_awref AS source_document_number_src_awref,
  acdoca.src_awitem AS source_document_line_item_src_awitem,
  acdoca.src_awsubit AS source_document_subitem_src_awsubit,
  acdoca.xcommitment AS commitment_xcommitment,
  acdoca.obs_reason AS reason_why_this_item_is_obsolete_obs_reason,
  acdoca.rtcur AS balance_transaction_currency_rtcur,
  acdoca.rwcur AS transaction_currency_rwcur,
  acdoca.rhcur AS company_code_currency_rhcur,
  acdoca.rkcur AS global_currency_rkcur,
  acdoca.rocur AS freely_defined_currency_1_rocur,
  acdoca.rvcur AS freely_defined_currency_2_rvcur,
  acdoca.rbcur AS freely_defined_currency_3_rbcur,
  acdoca.rccur AS freely_defined_currency_4_rccur,
  acdoca.rdcur AS freely_defined_currency_5_rdcur,
  acdoca.recur AS freely_defined_currency_6_recur,
  acdoca.rfcur AS freely_defined_currency_7_rfcur,
  acdoca.rgcur AS freely_defined_currency_8_rgcur,
  acdoca.rco_ocur AS co_object_currency_rco_ocur,
  acdoca.rgm_ocur AS grant_currency_rgm_ocur,
  acdoca.runit AS base_unit_of_measure_runit,
  acdoca.rvunit AS valunit_of_measure_rvunit,
  acdoca.rrunit AS refunit_of_measure_rrunit,
  acdoca.rmsl_type AS reference_quantity_type_rmsl_type,
  acdoca.riunit AS inventory_unit_of_measure_riunit,
  acdoca.qunit1 AS add_unit_of_measure1_qunit1,
  acdoca.qunit2 AS add_unit_of_measure2_qunit2,
  acdoca.qunit3 AS add_unit_of_measure3_qunit3,
  acdoca.co_meinh AS uom_co_valuation_quantity_co_meinh,
  acdoca.racct AS account_number_racct,
  acdoca.rcntr AS cost_center_rcntr,
  acdoca.prctr AS profit_center_prctr,
  acdoca.rfarea AS functional_area_rfarea,
  acdoca.rbusa AS business_area_rbusa,
  acdoca.kokrs AS controlling_area_kokrs,
  acdoca.segment AS segment,
  acdoca.scntr AS sender_cost_center_scntr,
  acdoca.pprctr AS partner_profit_center_pprctr,
  acdoca.sfarea AS partner_func_area_sfarea,
  acdoca.sbusa AS trading_part_ba_sbusa,
  acdoca.rassc AS trading_partner_number_rassc,
  acdoca.psegment AS partner_segment_psegment,
  acdoca.tsl AS amount_in_balance_transaction_currency_tsl,
  acdoca.wsl AS amount_in_transaction_currency_wsl,
  acdoca.wsl2 AS group_valuation_amnt_in_transaction_crcy_wsl2,
  acdoca.wsl3 AS prctr_valuation_amnt_in_transaction_crcy_wsl3,
  acdoca.hsl AS amount_in_company_code_currency_hsl,
  acdoca.ksl AS amount_in_global_currency_ksl,
  acdoca.osl AS amount_in_freely_defined_currency_1_osl,
  acdoca.vsl AS amount_in_freely_defined_currency_2_vsl,
  acdoca.bsl AS amount_in_freely_defined_currency_3_bsl,
  acdoca.csl AS amount_in_freely_defined_currency_4_csl,
  acdoca.dsl AS amount_in_freely_defined_currency_5_dsl,
  acdoca.esl AS amount_in_freely_defined_currency_6_esl,
  acdoca.fsl AS amount_in_freely_defined_currency_7_fsl,
  acdoca.gsl AS amount_in_freely_defined_currency_8_gsl,
  acdoca.kfsl AS fixed_amount_in_global_currency_kfsl,
  acdoca.kfsl2 AS group_valuation_fixed_amount_in_global_crcy_kfsl2,
  acdoca.kfsl3 AS prctr_valuation_fixed_amount_in_global_crcy_kfsl3,
  acdoca.psl AS total_price_variance_in_global_crcy_psl,
  acdoca.psl2 AS group_valuation_total_price_var_in_global_crcy_psl2,
  acdoca.psl3 AS prctr_valuation_total_price_var_in_global_crcy_psl3,
  acdoca.pfsl AS fixed_price_variance_in_global_crcy_pfsl,
  acdoca.pfsl2 AS group_valfixed_price_var_in_global_crcy_pfsl2,
  acdoca.pfsl3 AS prctr_valuation_fixed_price_var_in_global_crcy_pfsl3,
  acdoca.co_osl AS amount_in_co_object_currency_co_osl,
  acdoca.gm_osl AS amount_in_grant_currency_gm_osl,
  acdoca.hslalt AS altvalue_local_crcy_hslalt,
  acdoca.kslalt AS altvalue_in_grpcrcy_kslalt,
  acdoca.oslalt AS alt_value_in_freely_defined_currency_1_oslalt,
  acdoca.vslalt AS alt_value_in_freely_defined_currency_2_vslalt,
  acdoca.bslalt AS alt_value_in_freely_defined_currency_3_bslalt,
  acdoca.cslalt AS alt_value_in_freely_defined_currency_4_cslalt,
  acdoca.dslalt AS alt_value_in_freely_defined_currency_5_dslalt,
  acdoca.eslalt AS alt_value_in_freely_defined_currency_6_eslalt,
  acdoca.fslalt AS alt_value_in_freely_defined_currency_7_fslalt,
  acdoca.gslalt AS alt_value_in_freely_defined_currency_8_gslalt,
  acdoca.hslext AS extvalue_local_crcy_hslext,
  acdoca.kslext AS extvalue_in_grpcrcy_kslext,
  acdoca.oslext AS ext_value_in_freely_defined_currency_1_oslext,
  acdoca.vslext AS ext_value_in_freely_defined_currency_2_vslext,
  acdoca.bslext AS ext_value_in_freely_defined_currency_3_bslext,
  acdoca.cslext AS ext_value_in_freely_defined_currency_4_cslext,
  acdoca.dslext AS ext_value_in_freely_defined_currency_5_dslext,
  acdoca.eslext AS ext_value_in_freely_defined_currency_6_eslext,
  acdoca.fslext AS ext_value_in_freely_defined_currency_7_fslext,
  acdoca.gslext AS ext_value_in_freely_defined_currency_8_gslext,
  acdoca.hvkwrt AS value_special_localcrcy_hvkwrt,
  acdoca.msl AS quantity_msl,
  acdoca.mfsl AS fixed_quantity_mfsl,
  acdoca.vmsl AS valuation_quantity_vmsl,
  acdoca.vmfsl AS fixed_valuation_qty_vmfsl,
  acdoca.rmsl AS reference_quantity_rmsl,
  acdoca.quant1 AS add_quantity_1_quant1,
  acdoca.quant2 AS add_quantity_2_quant2,
  acdoca.quant3 AS add_quantity_3_quant3,
  acdoca.co_megbtr AS co_valuation_quantity_co_megbtr,
  acdoca.co_mefbtr AS co_valuation_quantity_fix_co_mefbtr,
  acdoca.hsalk3 AS invvalue_localcrcy_hsalk3,
  acdoca.ksalk3 AS invvalue_groupcrcy_ksalk3,
  acdoca.osalk3 AS invvalue_freely_defined_currency_1_osalk3,
  acdoca.vsalk3 AS invvalue_freely_defined_currency_2_vsalk3,
  acdoca.hsalkv AS altinvvalue_local_currency_hsalkv,
  acdoca.ksalkv AS altinvvalue_grpcrcy_ksalkv,
  acdoca.osalkv AS altvalue_freely_defined_currency_1_osalkv,
  acdoca.vsalkv AS altvalue_freely_defined_currency_2_vsalkv,
  acdoca.hpvprs AS mvavgprice_localcrcy_hpvprs,
  acdoca.kpvprs AS mvavgprice_groupcrcy_kpvprs,
  acdoca.opvprs AS map_anothercrcy_opvprs,
  acdoca.vpvprs AS map_4crcy_vpvprs,
  acdoca.hstprs AS stdprice_localcrcy_hstprs,
  acdoca.kstprs AS stdprice_groupcrcy_kstprs,
  acdoca.ostprs AS stdprice_anothercrcy_ostprs,
  acdoca.vstprs AS stdprice_4crcy_vstprs,
  acdoca.hvksal AS invval_special_localcrcy_hvksal,
  acdoca.lbkum AS inventory_quantity_lbkum,
  acdoca.drcrk AS debit_credit_indicator_drcrk,
  acdoca.poper AS posting_period_poper,
  acdoca.periv AS fiscal_year_variant_periv,
  acdoca.fiscyearper AS period_year_fiscyearper,
  acdoca.budat AS posting_date_budat,
  acdoca.bldat AS document_date_bldat,
  acdoca.blart AS document_type_blart,
  acdoca.buzei AS line_item_buzei,
  acdoca.zuonr AS assignment_zuonr,
  acdoca.bschl AS posting_key_bschl,
  acdoca.bstat AS document_status_bstat,
  acdoca.linetype AS item_category_linetype,
  acdoca.ktosl AS transaction_ktosl,
  acdoca.slalittype AS sla_line_item_type_slalittype,
  acdoca.xsplitmod AS changed_document_split_xsplitmod,
  acdoca.usnam AS user_name_usnam,
  acdoca.timestamp AS time_stamp_timestamp,
  acdoca.eprctr AS elimination_prctr_eprctr,
  acdoca.rhoart AS origin_object_rhoart,
  acdoca.glaccount_type AS gl_account_type_glaccount_type,
  acdoca.ktopl AS chart_of_accounts_ktopl,
  acdoca.lokkt AS alternative_account_number_lokkt,
  acdoca.ktop2 AS country_chart_accts_ktop2,
  acdoca.rebzg AS invoice_reference_rebzg,
  acdoca.rebzj AS fiscal_year_rebzj,
  acdoca.rebzz AS line_item_rebzz,
  acdoca.rebzt AS follow_on_document_type_rebzt,
  acdoca.rbest AS po_category_rbest,
  acdoca.ebeln_logsys AS logical_system_of_purchasing_document_ebeln_logsys,
  acdoca.ebeln AS purchasing_document_ebeln,
  acdoca.ebelp AS item_ebelp,
  acdoca.zekkn AS seq_number_of_account_assgt_zekkn,
  acdoca.sgtxt AS text_sgtxt,
  acdoca.kdauf AS sales_order_kdauf,
  acdoca.kdpos AS sales_order_item_kdpos,
  acdoca.matnr AS material_matnr,
  acdoca.werks AS plant_werks,
  acdoca.lifnr AS vendor_lifnr,
  acdoca.kunnr AS customer_kunnr,
  acdoca.fbuda AS serv_rendered_date_fbuda,
  acdoca.perop_beg AS billing_period_of_performance_start_date_perop_beg,
  acdoca.perop_end AS billing_period_of_performance_end_date_perop_end,
  acdoca.coco_num AS condition_contract_coco_number,
  acdoca.wwert AS translation_date_wwert,
  acdoca.prctr_drvtn_source_type AS profit_center_drvtn_srce_type_prctr_drvtn_source_type,
  acdoca.koart AS account_type_koart,
  acdoca.umskz AS special_gl_indicator_umskz,
  acdoca.tax_country AS tax_country,
  acdoca.mwskz AS tax_code_mwskz,
  acdoca.hbkid AS house_bank_hbkid,
  acdoca.hktid AS account_id_hktid,
  acdoca.valut AS value_date_valut,
  acdoca.xopvw AS open_item_management_xopvw,
  acdoca.augdt AS clearing_date_augdt,
  acdoca.augbl AS clearing_document_augbl,
  acdoca.auggj AS clearing_fiscal_year_auggj,
  acdoca.afabe AS depreciation_area_afabe,
  acdoca.anln1 AS asset_anln1,
  acdoca.anln2 AS sub_number_anln2,
  acdoca.bzdat AS asset_value_date_bzdat,
  acdoca.anbwa AS asset_transaction_type_anbwa,
  acdoca.movcat AS transaction_type_category_movcat,
  acdoca.depr_period AS depreciation_period_depr_period,
  acdoca.anlgr AS group_asset_anlgr,
  acdoca.anlgr2 AS subnumber_anlgr2,
  acdoca.settlement_rule AS distrib_rule_group_settlement_rule,
  acdoca.anlkl AS asset_class_anlkl,
  acdoca.ktogr AS account_determination_ktogr,
  acdoca.panl1 AS partner_asset_panl1,
  acdoca.panl2 AS partner_subnumber_panl2,
  acdoca.ubzdt_pn AS orig_valuation_date_ubzdt_pn,
  acdoca.xvabg_pn AS complete_retirement_xvabg_pn,
  acdoca.prozs_pn AS percentage_rate_prozs_pn,
  acdoca.xmanpropval_pn AS manual_proportional_values_xmanpropval_pn,
  acdoca.kalnr AS cost_estimate_number_kalnr,
  acdoca.vprsv AS price_control_vprsv,
  acdoca.mlast AS material_price_determination_control_mlast,
  acdoca.kzbws AS spec_stk_valuation_kzbws,
  acdoca.xobew AS vendor_stock_valuation_xobew,
  acdoca.sobkz AS special_stock_sobkz,
  acdoca.vtstamp AS valuation_time_stamp_vtstamp,
  acdoca.mat_kdauf AS sd_document_of_inventory_mat_kdauf,
  acdoca.mat_kdpos AS sd_item_of_inventory_mat_kdpos,
  acdoca.mat_pspnr AS wbselem_of_inventory_mat_pspnr,
  acdoca.mat_ps_posid AS wbselem_of_inventory_mat_ps_posid,
  acdoca.mat_lifnr AS vendor_of_inventory_mat_lifnr,
  acdoca.bwtar AS valuation_type_bwtar,
  acdoca.bwkey AS valuation_area_bwkey,
  acdoca.hpeinh AS price_unit_localcrcy_hpeinh,
  acdoca.kpeinh AS price_unit_groupcrcy_kpeinh,
  acdoca.opeinh AS price_unit_acrcy_opeinh,
  acdoca.vpeinh AS price_unit_4crcy_vpeinh,
  acdoca.mlptyp AS orig_process_catego_mlptyp,
  acdoca.mlcateg AS category_mlcateg,
  acdoca.qsbvalt AS procure_alt_process_qsbvalt,
  acdoca.qsprocess AS production_process_number_qsprocess,
  acdoca.perart AS period_type_perart,
  acdoca.mlposnr AS item_mlposnr,
  acdoca.inv_mov_categ AS inventory_movement_category_invoice_mov_categ,
  acdoca.bukrs_sender AS company_code_in_sender_system_bukrs_sender,
  acdoca.racct_sender AS sender_general_ledger_account_racct_sender,
  acdoca.accas_sender AS sender_account_assignment_accas_sender,
  acdoca.accasty_sender AS sender_account_assignment_type_accasty_sender,
  acdoca.objnr AS object_number_objnr,
  acdoca.hrkft AS co_subkey_hrkft,
  acdoca.hkgrp AS origin_group_hkgrp,
  acdoca.parob1 AS partner_object_parob1,
  acdoca.parobsrc AS partner_obj_source_parobsrc,
  acdoca.uspob AS source_object_uspob,
  acdoca.co_belkz AS dr_cr_indicator_co_belkz,
  acdoca.co_beknz AS dr_cr_indicator_origin_co_beknz,
  acdoca.beltp AS debit_type_beltp,
  acdoca.muvflg AS quantity_is_incomplete_muvflg,
  acdoca.gkont AS offsetting_account_gkont,
  acdoca.gkoar AS offsetting_account_type_gkoar,
  acdoca.erlkz AS completion_indicator_erlkz,
  acdoca.pernr AS personnel_number_pernr,
  acdoca.paobjnr AS profitab_segmt_number_paobjnr,
  acdoca.xpaobjnr_co_rel AS paobjnr_relevant_for_co_compatibility_xpaobjnr_co_rel,
  acdoca.scope AS object_class_scope,
  acdoca.logsyso AS logical_system_logsyso,
  acdoca.pbukrs AS partner_company_code_pbukrs,
  acdoca.pscope AS partner_object_class_pscope,
  acdoca.logsysp AS logical_system_logsysp,
  acdoca.bwstrat AS valuation_strategy_bwstrat,
  acdoca.objnr_hk AS origin_object_objnr_hk,
  acdoca.aufnr_org AS origin_order_number_aufnr_org,
  acdoca.ukostl AS origin_cctr_ukostl,
  acdoca.ulstar AS origin_activity_ulstar,
  acdoca.uprznr AS source_bus_process_uprznr,
  acdoca.uprctr AS origin_profit_center_uprctr,
  acdoca.umatnr AS origin_material_umatnr,
  acdoca.varc_uacct AS variance_origin_account_varc_uacct,
  acdoca.accas AS account_assignment_accas,
  acdoca.accasty AS object_type_accasty,
  acdoca.lstar AS activity_type_lstar,
  acdoca.aufnr AS order_aufnr,
  acdoca.autyp AS order_category_autyp,
  acdoca.ps_psp_pnr AS wbs_element_ps_psp_pnr,
  acdoca.ps_posid AS wbs_element_ps_posid,
  acdoca.ps_prj_pnr AS project_definition_ps_prj_pnr,
  acdoca.ps_pspid AS project_definition_ps_pspid,
  acdoca.nplnr AS network_nplnr,
  acdoca.nplnr_vorgn AS network_activity_nplnr_vorgn,
  acdoca.prznr AS business_process_prznr,
  acdoca.kstrg AS cost_object_kstrg,
  acdoca.bemot AS accounting_indicator_bemot,
  acdoca.rsrce AS resource_rsrce,
  acdoca.qmnum AS notification_qmnum,
  acdoca.service_doc_type AS service_document_type_service_document_type,
  acdoca.service_doc_id AS service_document_service_document_id,
  acdoca.service_doc_item_id AS service_document_item_service_document_item_id,
  acdoca.service_contract_type AS service_contract_type,
  acdoca.service_contract_id AS service_contract_service_contract_id,
  acdoca.service_contract_item_id AS service_contract_item_service_contract_item_id,
  acdoca.solution_order_id AS solution_order_solution_order_id,
  acdoca.solution_order_item_id AS solution_order_item_solution_order_item_id,
  acdoca.erkrs AS operating_concern_erkrs,
  acdoca.paccas AS partner_account_assignment_paccas,
  acdoca.paccasty AS partner_object_type_paccasty,
  acdoca.plstar AS paractivity_plstar,
  acdoca.paufnr AS partner_order_number_paufnr,
  acdoca.pautyp AS partner_order_category_pautyp,
  acdoca.pps_psp_pnr AS partner_wbs_element_internal_id_pps_psp_pnr,
  acdoca.pps_posid AS partner_work_breakdown_structure_element_pps_posid,
  acdoca.pps_prj_pnr AS partner_project_definition_internal_id_pps_prj_pnr,
  acdoca.pps_pspid AS partner_project_def_pps_pspid,
  acdoca.pkdauf AS partner_sales_order_number_pkdauf,
  acdoca.pkdpos AS partner_sales_order_item_pkdpos,
  acdoca.ppaobjnr AS partner_prof_segment_ppaobjnr,
  acdoca.pnplnr AS partner_project_network_pnplnr,
  acdoca.pnplnr_vorgn AS part_project_network_activity_pnplnr_vorgn,
  acdoca.pprznr AS partner_business_process_pprznr,
  acdoca.pkstrg AS partner_cost_object_pkstrg,
  acdoca.pservice_doc_type AS partner_service_document_type_pservice_document_type,
  acdoca.pservice_doc_id AS partner_service_document_pservice_document_id,
  acdoca.pservice_doc_item_id AS partner_service_document_item_pservice_document_item_id,
  acdoca.co_accasty_n1 AS statistical_account_assignment_type_1_co_accasty_n1,
  acdoca.co_accasty_n2 AS statistical_account_assignment_type_2_co_accasty_n2,
  acdoca.co_accasty_n3 AS statistical_account_assignment_type_3_co_accasty_n3,
  acdoca.co_zlenr AS document_item_co_zlenr,
  acdoca.co_belnr AS document_number_co_belnr,
  acdoca.co_buzei AS posting_row_co_buzei,
  acdoca.co_buzei1 AS co_posting_row_1_co_buzei1,
  acdoca.co_buzei2 AS co_posting_row_2_co_buzei2,
  acdoca.co_buzei5 AS co_posting_row_5_co_buzei5,
  acdoca.co_buzei6 AS co_posting_row_6_co_buzei6,
  acdoca.co_buzei7 AS co_posting_row_7_co_buzei7,
  acdoca.co_refbz AS posting_row_co_refbz,
  acdoca.co_refbz1 AS refdoc_posting_row_1_co_refbz1,
  acdoca.co_refbz2 AS refdoc_posting_row_2_co_refbz2,
  acdoca.co_refbz5 AS refdoc_posting_row_5_co_refbz5,
  acdoca.co_refbz6 AS refdoc_posting_row_6_co_refbz6,
  acdoca.co_refbz7 AS refdoc_posting_row_7_co_refbz7,
  acdoca.overtimecat AS overtime_category_overtimecat,
  acdoca.work_item_id AS work_item_id,
  acdoca.arbid AS object_id_arbid,
  acdoca.vornr AS activity_vornr,
  acdoca.aufps AS order_item_number_aufps,
  acdoca.uvorn AS suboperation_uvorn,
  acdoca.equnr AS equipment_equnr,
  acdoca.tplnr AS functional_location_tplnr,
  acdoca.istru AS assembly_istru,
  acdoca.ilart AS maintactivitytype_ilart,
  acdoca.plknz AS order_planning_indicator_plknz,
  acdoca.artpr AS priority_type_artpr,
  acdoca.priok AS priority_priok,
  acdoca.maufnr AS superior_order_maufnr,
  acdoca.matkl_mm AS material_group_matkl_mm,
  acdoca.paufps AS partner_order_item_number_paufps,
  acdoca.planned_parts_work AS planned_parts_work,
  acdoca.fkart AS billing_type_fkart,
  acdoca.vkorg AS sales_organization_vkorg,
  acdoca.vtweg AS distribution_channel_vtweg,
  acdoca.spart AS division_spart,
  acdoca.matnr_copa AS product_sold_matnr_copa,
  acdoca.matkl AS product_sold_group_matkl,
  acdoca.kdgrp AS customer_group_kdgrp,
  acdoca.land1 AS country_land1,
  acdoca.brsch AS industry_brsch,
  acdoca.bzirk AS sales_district_bzirk,
  acdoca.kunre AS bill_to_party_kunre,
  acdoca.kunwe AS ship_to_party_kunwe,
  acdoca.konzs AS group_key_konzs,
  acdoca.acdoc_copa_eew_dummy_pa AS dummy_function_in_length_1_acdoc_copa_eew_dummy_pa,
  acdoca.kmbrnd_pa AS brand_kmbrnd_pa,
  acdoca.kmcatg_pa AS business_field_kmcatg_pa,
  acdoca.kmkdgr_pa AS customer_group_kmkdgr_pa,
  acdoca.kmland_pa AS country_kmland_pa,
  acdoca.kmmakl_pa AS material_group_kmmakl_pa,
  acdoca.kmvkbu_pa AS sales_office_kmvkbu_pa,
  acdoca.beskz_pa AS procurement_type_beskz_pa,
  acdoca.kmvtnr_pa AS sales_employee_kmvtnr_pa,
  acdoca.paph1_pa AS prod_hierarchy01_1_paph1_pa,
  acdoca.paph2_pa AS prod_hierarchy01_2_paph2_pa,
  acdoca.paph3_pa AS prod_hierarchy01_3_paph3_pa,
  acdoca.vkbur_pa AS sales_office_vkbur_pa,
  acdoca.dummy_mrkt_sgmnt_eew_ps AS dummy_mrkt_sgmnt_eew_ps,
  acdoca.re_bukrs AS cash_origin_company_code_re_bukrs,
  acdoca.re_account AS cash_origin_account_re_account,
  acdoca.fikrs AS fm_area_fikrs,
  acdoca.fipex AS commitment_item_fipex,
  acdoca.fistl AS funds_center_fistl,
  acdoca.measure AS funded_program_measure,
  acdoca.rfund AS fund_rfund,
  acdoca.rgrant_nbr AS grant_rgrant_nbr,
  acdoca.rbudget_pd AS budget_period_budget_pd,
  acdoca.sfund AS partner_fund_sfund,
  acdoca.sgrant_nbr AS partner_grant_sgrant_nbr,
  acdoca.sbudget_pd AS par_budget_per_sbudget_pd,
  acdoca.bdgt_account AS budget_account_bdgt_account,
  acdoca.bdgt_account_cocode AS company_code_for_budget_account_bdgt_account_company_code,
  acdoca.bdgt_cnsmpn_date AS budget_consumption_date_bdgt_cnsmpn_date,
  acdoca.bdgt_cnsmpn_period AS posting_period_for_budget_consumption_bdgt_cnsmpn_period,
  acdoca.bdgt_cnsmpn_year AS year_of_budget_consumption_bdgt_cnsmpn_year,
  acdoca.bdgt_relevant AS budget_relevant_bdgt_relevant,
  acdoca.bdgt_cnsmpn_type AS budget_consumption_type_bdgt_cnsmpn_type,
  acdoca.bdgt_cnsmpn_amount_type AS amount_type_for_budget_consumption_bdgt_cnsmpn_amount_type,
  acdoca.rsponsored_prog AS sponsored_program_rsponsored_prog,
  acdoca.rsponsored_class AS sponsored_class_rsponsored_class,
  acdoca.rbdgt_vldty_nbr AS budget_validity_number_rbdgt_vldty_nbr,
  acdoca.kblnr AS earmarked_funds_kblnr,
  acdoca.kblpos AS document_item_kblpos,
  acdoca.vname AS joint_venture_vname,
  acdoca.egrup AS equity_group_egrup,
  acdoca.recid AS recovery_indicator_recid,
  acdoca.vptnr AS partner_vptnr,
  acdoca.btype AS billing_indicator_btype,
  acdoca.etype AS equity_type_etype,
  acdoca.prodper AS production_month_prodper,
  acdoca.billm AS billing_month_billm,
  acdoca.pom AS proc_operational_month_pom,
  acdoca.cbrunid AS cutback_run_id_jva_cbrunid,
  acdoca.jvactivity AS jva_activity_joint_venture_accounting_jvactivity,
  acdoca.pvname AS partner_venture_jva_pvname,
  acdoca.pegrup AS partner_equity_group_jva_pegrup,
  acdoca.s_recind AS sender_rec_indicator_s_recind,
  acdoca.cbracct AS cutback_account_jva_cbracct,
  acdoca.cbobjnr AS cutback_cost_object_jva_cbobjnr,
  acdoca.swenr AS business_entity_swenr,
  acdoca.sgenr AS building_sgenr,
  acdoca.sgrnr AS land_sgrnr,
  acdoca.smenr AS rental_object_smenr,
  acdoca.recnnr AS contract_recnnr,
  acdoca.snksl AS service_charge_key_snksl,
  acdoca.sempsl AS settlement_unit_sempsl,
  acdoca.dabrz AS reference_date_dabrz,
  acdoca.pswenr AS partner_business_entity_pswenr,
  acdoca.psgenr AS partner_building_psgenr,
  acdoca.psgrnr AS partner_land_psgrnr,
  acdoca.psmenr AS partner_rent_unit_psmenr,
  acdoca.precnnr AS partner_contract_number_precnnr,
  acdoca.psnksl AS partner_servic_charge_key_psnksl,
  acdoca.psempsl AS partner_settlement_unit_psempsl,
  acdoca.pdabrz AS partner_reference_date_pdabrz,
  acdoca.acrobjtype AS accrual_object_type_acrobjtype,
  acdoca.acrlogsys AS logical_system_of_accrual_object_acrlogsys,
  acdoca.acrobj_id AS accrual_object_acrobj_id,
  acdoca.acrsobj_id AS accrual_subobject_acrsobj_id,
  acdoca.acritmtype AS accrual_item_type_acritmtype,
  acdoca.acrvaldat AS accrual_value_date_acrvaldat,
  acdoca.valobjtype AS type_of_the_financial_valuation_object_valobjtype,
  acdoca.valobj_id AS financial_valuation_object_valobj_id,
  acdoca.valsobj_id AS financial_valuation_subobject_valsobj_id,
  acdoca.netdt AS net_due_date_netdt,
  acdoca.risk_class AS risk_class,
  acdoca.acdoc_eew_dummy AS dummy_acdoc_eew_dummy,
  acdoca.dummy_incl_eew_cobl AS dummy_incl_eew_cobl,
  acdoca.fup_action AS follow_up_action_fup_action,
  acdoca.sdm_version AS sdm_versioning_sdm_version,
  acdoca.mig_source AS migration_source_mig_source,
  acdoca.mig_docln AS migrated_line_item_id_mig_docln,
  bseg.zfbdt AS baseline_payment_date_zfbdt,
  bseg.zterm AS terms_of_payment_zterm,
  bseg.zbd1t AS days_1_zbd1t,
  bseg.zbd2t AS days_2_zbd2t,
  bseg.zbd3t AS days_net_zbd3t,
  bseg.zbd1p AS cash_discount_percent_1_zbd1p,
  bseg.zbd2p AS cash_discount_percent_2_zbd2p,
  bseg.zlsch AS payment_method_zlsch,
  bseg.zlspr AS payment_block_zlspr,
  bseg.diekz AS service_indicator_diekz,
  bseg.mansp AS dunning_block_mansp,
  bseg.mschl AS dunning_key_mschl,
  bseg.madat AS last_dunned_madat,
  bseg.manst AS dunning_level_manst,
  bseg.maber AS dunning_area_maber,
  bseg.qsshb AS withholding_tax_base_qsshb,
  bseg.qbshb AS withholding_tax_amnt_qbshb,
  GREATEST(
    IFNULL(acdoca.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
    IFNULL(bkpf.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
    IFNULL(bseg.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00'))
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "acdoca")} AS acdoca
INNER JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bkpf")} AS bkpf
  ON acdoca.rclnt = bkpf.mandt
  AND acdoca.rbukrs = bkpf.bukrs
  AND acdoca.gjahr = bkpf.gjahr
  AND acdoca.belnr = bkpf.belnr
LEFT JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "bseg")} AS bseg
  ON acdoca.rclnt = bseg.mandt
  AND acdoca.rbukrs = bseg.bukrs
  AND acdoca.gjahr = bseg.gjahr
  AND acdoca.belnr = bseg.belnr
  AND acdoca.buzei = bseg.buzei
${sql_helper.buildDynamicWhere([
  "acdoca.koart = 'K'",
  incremental.getFilter(ctx, ["acdoca", "bkpf", "bseg"])
])}
`
);
