/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_rclnt",
    "ledger_in_general_ledger_accounting_rldnr",
    "company_code_rbukrs",
    "fiscal_year_gjahr",
    "accounting_document_number_belnr",
    "line_item_docln"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
),
currency_decimal AS (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  acdoca.rclnt AS client_rclnt,
  acdoca.rldnr AS ledger_in_general_ledger_accounting_rldnr,
  acdoca.rbukrs AS company_code_rbukrs,
  acdoca.gjahr AS fiscal_year_gjahr,
  acdoca.belnr AS accounting_document_number_belnr,
  acdoca.docln AS line_item_docln,
  acdoca.ryear AS general_ledger_fiscal_year_ryear,
  acdoca.docnr_ld AS document_number_ledger_docnr_ld,
  acdoca.rrcty AS record_type_rrcty,
  acdoca.rmvct AS transaction_type_rmvct,
  acdoca.vorgn AS transaction_type_for_general_ledger_vorgn,
  acdoca.vrgng AS co_business_transaction_vrgng,
  acdoca.bttype AS business_transaction_type_bttype,
  acdoca.cbttype AS custom_business_transaction_type_not_used_yet_cbttype,
  acdoca.awtyp AS reference_procedure_awtyp,
  acdoca.awsys AS logical_system_awsys,
  acdoca.aworg AS reference_organizational_units_aworg,
  acdoca.awref AS reference_document_number_awref,
  acdoca.awitem AS reference_document_line_item_awitem,
  acdoca.awitgrp AS group_of_reference_document_line_items_awitgrp,
  acdoca.subta AS partial_document_to_be_balanced_to_zero_subta,
  acdoca.xreversing AS indicator_item_is_reversing_another_item_xreversing,
  acdoca.xreversed AS indicator_item_is_reversed_xreversed,
  acdoca.xtruerev AS indicator_true_reversal_ie_cancellation_xtruerev,
  acdoca.awtyp_rev AS reversal_transaction_awtyp_rev,
  acdoca.aworg_rev AS reversal_reference_organizations_of_document_to_be_reversed_aworg_rev,
  acdoca.awref_rev AS reversal_reference_document_number_awref_rev,
  acdoca.awitem_rev AS reversal_reference_doc_line_itm_of_document_to_be_reversed_awitem_rev,
  acdoca.subta_rev AS reversal_partial_document_to_be_balanced_to_zero_subta_rev,
  acdoca.xsettling AS indicator_item_is_settling_or_transferring_another_item_xsettling,
  acdoca.xsettled AS indicator_line_item_is_settled_or_transferred_xsettled,
  acdoca.prec_awtyp AS preceding_document_reference_transaction_prec_awtyp,
  acdoca.prec_awsys AS logical_system_of_preceding_reference_document_prec_awsys,
  acdoca.prec_aworg AS preceding_document_reference_organizational_units_prec_aworg,
  acdoca.prec_awref AS preceding_document_reference_document_number_prec_awref,
  acdoca.prec_awitem AS preceding_reference_document_line_item_prec_awitem,
  acdoca.prec_subta AS preceding_partial_document_to_be_balanced_to_zero_prec_subta,
  acdoca.prec_awmult AS id_of_multiple_preceding_document_references_prec_awmult,
  acdoca.prec_bukrs AS preceding_journal_entry_company_code_prec_bukrs,
  acdoca.prec_gjahr AS preceding_fiscal_year_prec_gjahr,
  acdoca.prec_belnr AS preceding_journal_entry_document_number_prec_belnr,
  acdoca.prec_docln AS preceding_line_item_prec_docln,
  acdoca.xsecondary AS secondary_journal_entry_xsecondary,
  acdoca.closing_run_id AS uuid_of_financial_closing_run_closing_run_id,
  acdoca.orgl_change AS organizational_change_orgl_change,
  acdoca.src_awtyp AS source_document_type_src_awtyp,
  acdoca.src_awsys AS source_document_system_src_awsys,
  acdoca.src_aworg AS organizational_unit_of_source_document_src_aworg,
  acdoca.src_awref AS source_document_number_src_awref,
  acdoca.src_awitem AS line_item_in_source_document_src_awitem,
  acdoca.src_awsubit AS subitem_in_source_document_src_awsubit,
  acdoca.xcommitment AS indicator_commitment_xcommitment,
  acdoca.obs_reason AS reason_why_this_item_is_obsolete_obs_reason,
  acdoca.rtcur AS balance_transaction_currency_rtcur,
  acdoca.rwcur AS transaction_currency_rwcur,
  acdoca.rhcur AS company_code_currency_rhcur,
  acdoca.rkcur AS global_currency_rkcur,
  acdoca.rco_ocur AS co_object_currency_rco_ocur,
  acdoca.rgm_ocur AS grant_currency_rgm_ocur,
  acdoca.runit AS base_unit_of_measure_runit,
  acdoca.rvunit AS unit_of_measure_for_valuation_quantity_rvunit,
  acdoca.rrunit AS unit_of_measure_for_reference_quantity_rrunit,
  acdoca.rmsl_type AS quantity_type_code_of_the_reference_quantity_rmsl_type,
  acdoca.riunit AS unit_of_measure_for_inventory_quantity_riunit,
  acdoca.qunit1 AS additional_unit_of_measure_1_qunit1,
  acdoca.qunit2 AS additional_unit_of_measure_2_qunit2,
  acdoca.qunit3 AS additional_unit_of_measure_3_qunit3,
  acdoca.co_meinh AS unit_of_measure_for_co_valuation_quantity_co_meinh,
  acdoca.racct AS account_number_racct,
  acdoca.rcntr AS cost_center_rcntr,
  acdoca.prctr AS profit_center_prctr,
  acdoca.rfarea AS functional_area_rfarea,
  acdoca.rbusa AS business_area_rbusa,
  acdoca.kokrs AS controlling_area_kokrs,
  acdoca.segment AS segment_for_segmental_reporting_segment,
  acdoca.scntr AS sender_cost_center_scntr,
  acdoca.pprctr AS partner_profit_center_pprctr,
  acdoca.sfarea AS partner_functional_area_sfarea,
  acdoca.sbusa AS trading_partners_business_area_sbusa,
  acdoca.rassc AS company_id_of_trading_partner_rassc,
  acdoca.psegment AS partner_segment_for_segmental_reporting_psegment,
  ${currency.amountWithDecimalShift("acdoca.tsl", "currency_decimal_rtcur")} AS amount_in_balance_transaction_currency_tsl,
  ${currency.amountWithDecimalShift("acdoca.wsl", "currency_decimal_rwcur")} AS amount_in_transaction_currency_wsl,
  ${currency.amountWithDecimalShift("acdoca.wsl2", "currency_decimal_rwcur")} AS group_valuation_amount_in_transaction_currency_wsl2,
  ${currency.amountWithDecimalShift("acdoca.wsl3", "currency_decimal_rwcur")} AS profitcenter_valuation_amount_in_transaction_currency_wsl3,
  ${currency.amountWithDecimalShift("acdoca.hsl", "currency_decimal_rhcur")} AS amount_in_company_code_currency_hsl,
  ${currency.amountWithDecimalShift("acdoca.ksl", "currency_decimal_rkcur")} AS amount_in_global_currency_ksl,
  ${currency.amountWithDecimalShift("acdoca.kfsl", "currency_decimal_rkcur")} AS fixed_amount_in_global_currency_kfsl,
  ${currency.amountWithDecimalShift("acdoca.kfsl2", "currency_decimal_rkcur")} AS group_valuation_fixed_amount_in_global_currency_kfsl2,
  ${currency.amountWithDecimalShift("acdoca.kfsl3", "currency_decimal_rkcur")} AS prctr_valuation_fixed_amount_in_global_currency_kfsl3,
  ${currency.amountWithDecimalShift("acdoca.psl", "currency_decimal_rkcur")} AS total_price_variance_in_global_currency_psl,
  ${currency.amountWithDecimalShift("acdoca.psl2", "currency_decimal_rkcur")} AS group_valuation_total_price_variance_in_global_currency_psl2,
  ${currency.amountWithDecimalShift("acdoca.psl3", "currency_decimal_rkcur")} AS prctr_valuation_total_price_variance_in_global_currency_psl3,
  ${currency.amountWithDecimalShift("acdoca.pfsl", "currency_decimal_rkcur")} AS fixed_price_variance_in_global_currency_pfsl,
  ${currency.amountWithDecimalShift("acdoca.pfsl2", "currency_decimal_rkcur")} AS group_valuation_fixed_price_variance_in_global_currency_pfsl2,
  ${currency.amountWithDecimalShift("acdoca.pfsl3", "currency_decimal_rkcur")} AS prctr_valuation_fixed_price_variance_in_global_currency_pfsl3,
  ${currency.amountWithDecimalShift("acdoca.co_osl", "currency_decimal_rco_ocur")} AS amount_in_co_object_currency_co_osl,
  ${currency.amountWithDecimalShift("acdoca.gm_osl", "currency_decimal_rgm_ocur")} AS grant_amount_in_grant_currency_gm_osl,
  ${currency.amountWithDecimalShift("acdoca.hslalt", "currency_decimal_rhcur")} AS alternative_value_in_local_currency_hslalt,
  ${currency.amountWithDecimalShift("acdoca.kslalt", "currency_decimal_rkcur")} AS alternative_value_in_group_currency_kslalt,
  ${currency.amountWithDecimalShift("acdoca.hslext", "currency_decimal_rhcur")} AS external_value_in_local_currency_hslext,
  ${currency.amountWithDecimalShift("acdoca.kslext", "currency_decimal_rkcur")} AS external_value_in_group_currency_kslext,
  ${currency.amountWithDecimalShift("acdoca.hvkwrt", "currency_decimal_rhcur")} AS value_at_sales_price_in_local_currency_hvkwrt,
  acdoca.msl AS quantity_msl,
  acdoca.mfsl AS fixed_quantity_mfsl,
  acdoca.vmsl AS valuation_quantity_vmsl,
  acdoca.vmfsl AS fixed_valuation_quantity_vmfsl,
  acdoca.rmsl AS reference_quantity_rmsl,
  acdoca.quant1 AS additional_quantity_1_quant1,
  acdoca.quant2 AS additional_quantity_2_quant2,
  acdoca.quant3 AS additional_quantity_3_quant3,
  acdoca.co_megbtr AS co_valuation_quantity_co_megbtr,
  acdoca.co_mefbtr AS co_valuation_quantity_fix_co_mefbtr,
  ${currency.amountWithDecimalShift("acdoca.hsalk3", "currency_decimal_rhcur")} AS inventory_value_in_local_currency_hsalk3,
  ${currency.amountWithDecimalShift("acdoca.ksalk3", "currency_decimal_rkcur")} AS inventory_value_in_group_currency_ksalk3,
  ${currency.amountWithDecimalShift("acdoca.hsalkv", "currency_decimal_rhcur")} AS alternative_inventory_value_in_local_currency_hsalkv,
  ${currency.amountWithDecimalShift("acdoca.ksalkv", "currency_decimal_rkcur")} AS alternative_inventory_value_in_group_currency_ksalkv,
  ${currency.amountWithDecimalShift("acdoca.hpvprs", "currency_decimal_rhcur")} AS moving_average_price_in_local_currency_hpvprs,
  ${currency.amountWithDecimalShift("acdoca.kpvprs", "currency_decimal_rkcur")} AS moving_average_price_in_group_currency_kpvprs,
  ${currency.amountWithDecimalShift("acdoca.hstprs", "currency_decimal_rhcur")} AS standard_price_in_local_currency_hstprs,
  ${currency.amountWithDecimalShift("acdoca.kstprs", "currency_decimal_rkcur")} AS standard_price_in_group_currency_kstprs,
  ${currency.amountWithDecimalShift("acdoca.hvksal", "currency_decimal_rhcur")} AS inventory_value_at_sales_price_in_local_currency_hvksal,
  acdoca.lbkum AS inventory_quantity_lbkum,
  acdoca.drcrk AS debitcredit_indicator_drcrk,
  acdoca.poper AS posting_period_poper,
  acdoca.periv AS fiscal_year_variant_periv,
  acdoca.fiscyearper AS periodyear_fiscyearper,
  acdoca.budat AS posting_date_in_the_document_budat,
  acdoca.bldat AS document_date_in_document_bldat,
  acdoca.blart AS document_type_blart,
  acdoca.buzei AS number_of_line_item_within_accounting_document_buzei,
  acdoca.zuonr AS assignment_number_zuonr,
  acdoca.bschl AS posting_key_bschl,
  acdoca.bstat AS document_status_bstat,
  acdoca.linetype AS item_category_linetype,
  acdoca.ktosl AS transaction_key_ktosl,
  acdoca.slalittype AS subledgerspecific_line_item_type_slalittype,
  acdoca.xsplitmod AS item_changed_by_document_splitting_xsplitmod,
  acdoca.usnam AS user_name_usnam,
  acdoca.timestamp AS utc_time_stamp_in_short_form_yyyymmddhhmmss_timestamp,
  acdoca.eprctr AS partner_profit_center_for_elimination_of_internal_business_eprctr,
  acdoca.rhoart AS type_of_origin_object_ecpca_rhoart,
  acdoca.glaccount_type AS type_of_a_general_ledger_account_glaccount_type,
  acdoca.ktopl AS chart_of_accounts_ktopl,
  acdoca.lokkt AS alternative_account_number_in_company_code_lokkt,
  acdoca.ktop2 AS chart_of_accounts_according_to_country_legislation_ktop2,
  acdoca.rebzg AS document_no_of_the_invoice_to_which_the_transaction_belongs_rebzg,
  acdoca.rebzj AS fiscal_year_of_the_relevant_invoice_for_credit_memo_rebzj,
  acdoca.rebzz AS line_item_in_the_relevant_invoice_rebzz,
  acdoca.rebzt AS follow_on_document_type_rebzt,
  acdoca.rbest AS category_of_reference_purchase_order_rbest,
  acdoca.ebeln_logsys AS logical_system_of_purchasing_document_ebeln_logsys,
  acdoca.ebeln AS purchasing_document_number_ebeln,
  acdoca.ebelp AS item_number_of_purchasing_document_ebelp,
  acdoca.zekkn AS sequential_number_of_account_assignment_zekkn,
  acdoca.sgtxt AS item_text_sgtxt,
  acdoca.kdauf AS sales_order_number_kdauf,
  acdoca.kdpos AS sales_order_item_kdpos,
  acdoca.matnr AS material_number_matnr,
  acdoca.werks AS plant_werks,
  acdoca.lifnr AS account_number_of_vendor_or_creditor_lifnr,
  acdoca.kunnr AS customer_number_kunnr,
  acdoca.fbuda AS date_on_which_services_are_rendered_fbuda,
  acdoca.perop_beg AS billing_period_of_performance_start_date_perop_beg,
  acdoca.perop_end AS billing_period_of_performance_end_date_perop_end,
  acdoca.coco_num AS condition_contract_coco_num,
  acdoca.wwert AS translation_date_wwert,
  acdoca.prctr_drvtn_source_type AS profit_center_derivation_source_type_prctr_drvtn_source_type,
  acdoca.koart AS account_type_koart,
  acdoca.umskz AS special_gl_indicator_umskz,
  acdoca.tax_country AS tax_reporting_country_tax_country,
  acdoca.mwskz AS tax_on_salespurchases_code_mwskz,
  acdoca.hbkid AS short_key_for_a_house_bank_hbkid,
  acdoca.hktid AS id_for_account_details_hktid,
  acdoca.valut AS value_date_valut,
  acdoca.xopvw AS indicator_open_item_management_xopvw,
  acdoca.augdt AS clearing_date_augdt,
  acdoca.augbl AS document_number_of_the_clearing_document_augbl,
  acdoca.auggj AS fiscal_year_of_clearing_document_auggj,
  acdoca.afabe AS depreciation_area_afabe,
  acdoca.anln1 AS main_asset_number_anln1,
  acdoca.anln2 AS asset_subnumber_anln2,
  acdoca.bzdat AS asset_value_date_bzdat,
  acdoca.anbwa AS asset_transaction_type_anbwa,
  acdoca.movcat AS transaction_type_category_movcat,
  acdoca.depr_period AS posting_period_of_depreciation_depr_period,
  acdoca.anlgr AS group_asset_anlgr,
  acdoca.anlgr2 AS subnumber_of_group_asset_anlgr2,
  acdoca.settlement_rule AS distribution_rule_group_settlement_rule,
  acdoca.anlkl AS asset_class_anlkl,
  acdoca.ktogr AS account_determination_ktogr,
  acdoca.panl1 AS main_number_partner_asset_transfer_panl1,
  acdoca.panl2 AS partner_asset_subnumber_transfer_panl2,
  acdoca.ubzdt_pn AS original_value_date_of_transaction_ubzdt_pn,
  acdoca.xvabg_pn AS indicator_post_complete_retirement_xvabg_pn,
  acdoca.prozs_pn AS percentage_rate_prozs_pn,
  acdoca.xmanpropval_pn AS indicator_proportional_values_entered_manually_xmanpropval_pn,
  acdoca.kalnr AS cost_estimate_number_for_cost_est_wo_qty_structure_kalnr,
  acdoca.vprsv AS price_control_indicator_vprsv,
  acdoca.mlast AS material_price_determination_control_mlast,
  acdoca.kzbws AS valuation_of_special_stock_kzbws,
  acdoca.xobew AS vendor_stock_valuation_indicator_xobew,
  acdoca.sobkz AS special_stock_indicator_sobkz,
  acdoca.vtstamp AS valuation_time_stamp_vtstamp,
  acdoca.mat_kdauf AS sales_document_number_of_valuated_special_inventory_mat_kdauf,
  acdoca.mat_kdpos AS sales_document_item_number_of_valuated_special_inventory_mat_kdpos,
  acdoca.mat_pspnr AS wbs_element_internal_id_of_inventory_mat_pspnr,
  acdoca.mat_ps_posid AS wbs_element_of_inventory_mat_ps_posid,
  acdoca.mat_lifnr AS supplier_of_valuated_special_inventory_mat_lifnr,
  acdoca.bwtar AS valuation_type_bwtar,
  acdoca.bwkey AS valuation_area_bwkey,
  acdoca.hpeinh AS price_unit_in_local_currency_hpeinh,
  acdoca.kpeinh AS price_unit_in_group_currency_kpeinh,
  acdoca.opeinh AS price_unit_in_another_currency_opeinh,
  acdoca.vpeinh AS price_unit_in_fourth_currency_vpeinh,
  acdoca.mlptyp AS original_process_category_mlptyp,
  acdoca.mlcateg AS category_in_material_update_structure_mlcateg,
  acdoca.qsbvalt AS procurement_alternativeprocess_qsbvalt,
  acdoca.qsprocess AS production_process_qsprocess,
  acdoca.perart AS type_of_period_perart,
  acdoca.mlposnr AS item_in_material_ledger_document_mlposnr,
  acdoca.inv_mov_categ AS balance_sheet_valuation_inventory_movement_category_inv_mov_categ,
  acdoca.bukrs_sender AS company_code_in_sender_system_bukrs_sender,
  acdoca.racct_sender AS general_ledger_account_in_sender_system_racct_sender,
  acdoca.accas_sender AS account_assignment_in_sender_system_accas_sender,
  acdoca.accasty_sender AS account_assignment_type_in_sender_system_accasty_sender,
  acdoca.objnr AS object_number_objnr,
  acdoca.hrkft AS co_key_subnumber_hrkft,
  acdoca.hkgrp AS origin_group_as_subdivision_of_cost_element_hkgrp,
  acdoca.parob1 AS partner_object_always_filled_parob1,
  acdoca.parobsrc AS source_of_parob_parob1_or_type_of_partner_object_parobsrc,
  acdoca.uspob AS source_object_cost_centeractivity_type_uspob,
  acdoca.co_belkz AS co_debitcredit_indicator_co_belkz,
  acdoca.co_beknz AS debitcredit_indicator_origin_co_beknz,
  acdoca.beltp AS debit_type_beltp,
  acdoca.muvflg AS indicator_quantity_is_incomplete_muvflg,
  acdoca.gkont AS offsetting_account_number_gkont,
  acdoca.gkoar AS offsetting_account_type_gkoar,
  acdoca.erlkz AS completion_indicator_for_line_item_erlkz,
  acdoca.pernr AS personnel_number_pernr,
  acdoca.paobjnr AS profitability_segment_number_copa_paobjnr,
  acdoca.xpaobjnr_co_rel AS indicator_profitability_segm_relevant_for_co_compatibility_xpaobjnr_co_rel,
  acdoca.scope AS object_class_scope,
  acdoca.logsyso AS logical_system_of_object_logsyso,
  acdoca.pbukrs AS partner_company_code_pbukrs,
  acdoca.pscope AS partner_object_class_pscope,
  acdoca.logsysp AS logical_system_of_partner_object_logsysp,
  acdoca.bwstrat AS strategy_for_determining_an_allocation_price_bwstrat,
  acdoca.objnr_hk AS object_number_of_origin_object_objnr_hk,
  acdoca.aufnr_org AS origin_order_number_aufnr_org,
  acdoca.ukostl AS origin_cost_center_ukostl,
  acdoca.ulstar AS origin_activity_ulstar,
  acdoca.uprznr AS source_business_process_uprznr,
  acdoca.uprctr AS origin_profit_center_uprctr,
  acdoca.umatnr AS origin_material_number_umatnr,
  acdoca.varc_uacct AS origin_gl_account_of_a_variance_varc_uacct,
  acdoca.accas AS account_assignment_accas,
  acdoca.accasty AS account_assignment_type_accasty,
  acdoca.lstar AS activity_type_lstar,
  acdoca.aufnr AS order_number_aufnr,
  acdoca.autyp AS order_category_autyp,
  acdoca.ps_psp_pnr AS work_breakdown_structure_element_wbs_element_ps_psp_pnr,
  acdoca.ps_posid AS work_breakdown_structure_element_wbs_element_ps_posid,
  acdoca.ps_prj_pnr AS project_internal_ps_prj_pnr,
  acdoca.ps_pspid AS project_definition_ps_pspid,
  acdoca.nplnr AS network_number_for_account_assignment_nplnr,
  acdoca.nplnr_vorgn AS network_activity_nplnr_vorgn,
  acdoca.prznr AS business_process_prznr,
  acdoca.kstrg AS cost_object_kstrg,
  acdoca.bemot AS accounting_indicator_bemot,
  acdoca.rsrce AS resource_rsrce,
  acdoca.qmnum AS notification_number_qmnum,
  acdoca.service_doc_type AS service_document_type_service_doc_type,
  acdoca.service_doc_id AS service_document_id_service_doc_id,
  acdoca.service_doc_item_id AS service_document_item_id_service_doc_item_id,
  acdoca.service_contract_type AS service_contract_type,
  acdoca.service_contract_id AS service_contract_id_service_contract_id,
  acdoca.service_contract_item_id AS service_contract_item_id_service_contract_item_id,
  acdoca.solution_order_id AS solution_order_id_solution_order_id,
  acdoca.solution_order_item_id AS solution_order_item_id_solution_order_item_id,
  acdoca.erkrs AS operating_concern_erkrs,
  acdoca.paccas AS partner_account_assignment_paccas,
  acdoca.paccasty AS partner_account_assignment_type_paccasty,
  acdoca.plstar AS partner_activity_type_plstar,
  acdoca.paufnr AS partner_order_number_paufnr,
  acdoca.pautyp AS partner_order_category_pautyp,
  acdoca.pps_psp_pnr AS partner_work_breakdown_structure_element_internal_id_pps_psp_pnr,
  acdoca.pps_posid AS partner_work_breakdown_structure_element_pps_posid,
  acdoca.pps_prj_pnr AS partner_project_internal_id_pps_prj_pnr,
  acdoca.pps_pspid AS partner_project_pps_pspid,
  acdoca.pkdauf AS number_of_partner_sales_order_pkdauf,
  acdoca.pkdpos AS partner_sales_order_item_pkdpos,
  acdoca.ppaobjnr AS partner_profitability_segment_number_copa_ppaobjnr,
  acdoca.pnplnr AS partner_project_network_pnplnr,
  acdoca.pnplnr_vorgn AS partner_project_network_activity_pnplnr_vorgn,
  acdoca.pprznr AS partner_business_process_pprznr,
  acdoca.pkstrg AS partner_cost_object_pkstrg,
  acdoca.pservice_doc_type AS partner_service_document_type_pservice_doc_type,
  acdoca.pservice_doc_id AS partner_service_document_id_pservice_doc_id,
  acdoca.pservice_doc_item_id AS partner_service_document_item_id_pservice_doc_item_id,
  acdoca.co_accasty_n1 AS type_of_first_statistical_account_assignment_co_accasty_n1,
  acdoca.co_accasty_n2 AS type_of_second_statistical_account_assignment_co_accasty_n2,
  acdoca.co_accasty_n3 AS type_of_third_statistical_account_assignment_co_accasty_n3,
  acdoca.co_zlenr AS document_item_number_co_zlenr,
  acdoca.co_belnr AS document_number_co_belnr,
  acdoca.co_buzei AS posting_row_co_buzei,
  acdoca.co_buzei1 AS posting_row_of_co_item_in_first_additional_valuation_co_buzei1,
  acdoca.co_buzei2 AS posting_row_of_co_item_in_second_additional_valuation_co_buzei2,
  acdoca.co_buzei5 AS posting_row_of_co_item_in_valuation_view_5_co_buzei5,
  acdoca.co_buzei6 AS posting_row_of_co_item_in_valuation_view_6_co_buzei6,
  acdoca.co_buzei7 AS posting_row_of_co_item_in_valuation_view_7_co_buzei7,
  acdoca.co_refbz AS posting_row_of_reference_document_co_refbz,
  acdoca.co_refbz1 AS posting_row_of_reference_document_in_first_addl_valuation_co_refbz1,
  acdoca.co_refbz2 AS posting_row_of_reference_document_in_second_addl_valuation_co_refbz2,
  acdoca.co_refbz5 AS posting_row_of_reference_document_in_valuation_view_5_co_refbz5,
  acdoca.co_refbz6 AS posting_row_of_reference_document_in_valuation_view_6_co_refbz6,
  acdoca.co_refbz7 AS posting_row_of_reference_document_in_valuation_view_7_co_refbz7,
  acdoca.overtimecat AS overtime_category_overtimecat,
  acdoca.work_item_id AS work_item_id,
  acdoca.arbid AS object_id_of_the_resource_arbid,
  acdoca.vornr AS operationactivity_number_vornr,
  acdoca.aufps AS order_item_number_aufps,
  acdoca.uvorn AS suboperation_uvorn,
  acdoca.equnr AS equipment_number_equnr,
  acdoca.tplnr AS functional_location_tplnr,
  acdoca.istru AS assembly_istru,
  acdoca.ilart AS maintenance_activity_type_ilart,
  acdoca.plknz AS maintenance_order_planning_indicator_plknz,
  acdoca.artpr AS priority_type_artpr,
  acdoca.priok AS priority_priok,
  acdoca.maufnr AS number_of_superior_order_maufnr,
  acdoca.matkl_mm AS material_group_matkl_mm,
  acdoca.paufps AS partner_order_item_number_paufps,
  acdoca.planned_parts_work AS planned_partswork_planned_parts_work,
  acdoca.fkart AS billing_type_fkart,
  acdoca.vkorg AS sales_organization_vkorg,
  acdoca.vtweg AS distribution_channel_vtweg,
  acdoca.spart AS division_spart,
  acdoca.matnr_copa AS product_sold_matnr_copa,
  acdoca.matkl AS product_sold_group_matkl,
  acdoca.kdgrp AS customer_group_kdgrp,
  acdoca.land1 AS country_key_land1,
  acdoca.brsch AS industry_key_brsch,
  acdoca.bzirk AS sales_district_bzirk,
  acdoca.kunre AS billto_party_kunre,
  acdoca.kunwe AS shipto_party_kunwe,
  acdoca.konzs AS group_key_konzs,
  acdoca.acdoc_copa_eew_dummy_pa AS dummy_function_in_length_1_acdoc_copa_eew_dummy_pa,
  acdoca.kmbrnd_pa AS brand_kmbrnd_pa,
  acdoca.kmcatg_pa AS business_field_kmcatg_pa,
  acdoca.kmkdgr_pa AS customer_group_kmkdgr_pa,
  acdoca.kmland_pa AS country_key_kmland_pa,
  acdoca.kmmakl_pa AS material_group_kmmakl_pa,
  acdoca.kmvkbu_pa AS sales_office_kmvkbu_pa,
  acdoca.beskz_pa AS procurement_type_beskz_pa,
  acdoca.kmvtnr_pa AS sales_employee_kmvtnr_pa,
  acdoca.paph1_pa AS product_hierarchy_level_1_paph1_pa,
  acdoca.paph2_pa AS product_hierarchy_level_2_paph2_pa,
  acdoca.paph3_pa AS prodhierarchy013_paph3_pa,
  acdoca.vkbur_pa AS sales_office_vkbur_pa,
  acdoca.dummy_mrkt_sgmnt_eew_ps AS custom_fields_dummy_for_use_in_extension_includes_dummy_mrkt_sgmnt_eew_ps,
  acdoca.re_bukrs AS cash_origin_company_code_re_bukrs,
  acdoca.re_account AS cash_origin_account_re_account,
  acdoca.fikrs AS financial_management_area_fikrs,
  acdoca.fipex AS commitment_item_fipex,
  acdoca.fistl AS funds_center_fistl,
  acdoca.measure AS funded_program_measure,
  acdoca.rfund AS fund_rfund,
  acdoca.rgrant_nbr AS grant_rgrant_nbr,
  acdoca.rbudget_pd AS budget_period_rbudget_pd,
  acdoca.sfund AS partner_fund_sfund,
  acdoca.sgrant_nbr AS partner_grant_sgrant_nbr,
  acdoca.sbudget_pd AS fm_partner_budget_period_sbudget_pd,
  acdoca.bdgt_account AS budget_account_bdgt_account,
  acdoca.bdgt_account_cocode AS budget_account_company_code_bdgt_account_cocode,
  acdoca.bdgt_cnsmpn_date AS budget_consumption_date_bdgt_cnsmpn_date,
  acdoca.bdgt_cnsmpn_period AS cc_fiscal_period_for_budget_consumption_date_bdgt_cnsmpn_period,
  acdoca.bdgt_cnsmpn_year AS cc_fiscal_year_for_budget_consumption_date_bdgt_cnsmpn_year,
  acdoca.bdgt_relevant AS budgetrelevant_indicator_bdgt_relevant,
  acdoca.bdgt_cnsmpn_type AS budget_consumption_type_bdgt_cnsmpn_type,
  acdoca.bdgt_cnsmpn_amount_type AS budget_consumption_amount_type_bdgt_cnsmpn_amount_type,
  acdoca.rsponsored_prog AS sponsored_program_rsponsored_prog,
  acdoca.rsponsored_class AS sponsored_class_rsponsored_class,
  acdoca.rbdgt_vldty_nbr AS budget_validity_number_rbdgt_vldty_nbr,
  acdoca.kblnr AS document_number_for_earmarked_funds_kblnr,
  acdoca.kblpos AS earmarked_funds_document_item_kblpos,
  acdoca.vname AS joint_venture_vname,
  acdoca.egrup AS equity_group_egrup,
  acdoca.recid AS recovery_indicator_recid,
  acdoca.vptnr AS partner_account_number_vptnr,
  acdoca.btype AS billing_indicator_btype,
  acdoca.etype AS equity_type_etype,
  acdoca.prodper AS production_month_date_to_find_period_and_year_prodper,
  acdoca.billm AS billing_month_billm,
  acdoca.pom AS processing_operational_month_pom,
  acdoca.cbrunid AS cutback_run_id_joint_venture_accounting_cbrunid,
  acdoca.jvactivity AS jva_activity_joint_venture_accounting_jvactivity,
  acdoca.pvname AS partner_venture_pvname,
  acdoca.pegrup AS partner_equity_group_joint_venture_accounting_pegrup,
  acdoca.s_recind AS allocation_sender_credit_recovery_indicator_s_recind,
  acdoca.cbracct AS cutback_account_joint_venture_accounting_cbracct,
  acdoca.cbobjnr AS cutback_cost_object_joint_venture_accounting_cbobjnr,
  acdoca.swenr AS business_entity_number_swenr,
  acdoca.sgenr AS number_of_building_sgenr,
  acdoca.sgrnr AS number_of_land_sgrnr,
  acdoca.smenr AS number_of_rental_object_smenr,
  acdoca.recnnr AS contract_number_recnnr,
  acdoca.snksl AS service_charge_key_snksl,
  acdoca.sempsl AS settlement_unit_sempsl,
  acdoca.dabrz AS reference_date_for_settlement_dabrz,
  acdoca.pswenr AS partner_business_entity_number_pswenr,
  acdoca.psgenr AS partner_building_number_psgenr,
  acdoca.psgrnr AS partner_land_number_psgrnr,
  acdoca.psmenr AS number_of_partner_rental_unit_psmenr,
  acdoca.precnnr AS partner_contract_number_precnnr,
  acdoca.psnksl AS partner_service_charge_key_psnksl,
  acdoca.psempsl AS partner_settlement_unit_psempsl,
  acdoca.pdabrz AS partner_reference_date_for_settlement_pdabrz,
  acdoca.acrobjtype AS type_of_the_accrual_object_acrobjtype,
  acdoca.acrlogsys AS logical_system_of_the_accrual_object_acrlogsys,
  acdoca.acrobj_id AS identifier_of_the_accrual_object_acrobj_id,
  acdoca.acrsobj_id AS identifier_of_the_accrual_subobject_acrsobj_id,
  acdoca.acritmtype AS type_of_the_item_of_the_accrual_subobject_acritmtype,
  acdoca.acrvaldat AS accrual_value_date_acrvaldat,
  acdoca.valobjtype AS type_of_the_financial_valuation_object_valobjtype,
  acdoca.valobj_id AS identifier_of_the_financial_valuation_object_valobj_id,
  acdoca.valsobj_id AS identifier_of_the_financial_valuation_subobject_valsobj_id,
  acdoca.netdt AS net_due_date_netdt,
  acdoca.risk_class AS risk_class_risk_class,
  acdoca.acdoc_eew_dummy AS custom_fields_dummy_for_use_in_extension_includes_acdoc_eew_dummy,
  acdoca.dummy_incl_eew_cobl AS custom_fields_dummy_for_use_in_extension_includes_dummy_incl_eew_cobl,
  acdoca.fup_action AS followup_action_for_this_universal_journal_entry_line_item_fup_action,
  acdoca.sdm_version AS sdm_version_field_for_acdoca_sdm_version,
  acdoca.mig_source AS source_of_a_migrated_journal_entry_item_mig_source,
  acdoca.mig_docln AS item_id_of_migrated_gl_line_item_mig_docln,
  dimensional_date_budat.cal_year AS year_of_posting_date_budat,
  dimensional_date_budat.cal_month AS month_of_posting_date_budat,
  dimensional_date_budat.cal_quarter AS quarter_of_posting_date_budat,
  dimensional_date_budat.cal_week AS week_of_posting_date_budat,
  IFNULL(
    acdoca.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "acdoca")} AS acdoca
LEFT JOIN currency_decimal AS currency_decimal_rtcur
  ON acdoca.rtcur = currency_decimal_rtcur.currkey
LEFT JOIN currency_decimal AS currency_decimal_rwcur
  ON acdoca.rwcur = currency_decimal_rwcur.currkey
LEFT JOIN currency_decimal AS currency_decimal_rhcur
  ON acdoca.rhcur = currency_decimal_rhcur.currkey
LEFT JOIN currency_decimal AS currency_decimal_rkcur
  ON acdoca.rkcur = currency_decimal_rkcur.currkey
LEFT JOIN currency_decimal AS currency_decimal_rco_ocur
  ON acdoca.rco_ocur = currency_decimal_rco_ocur.currkey
LEFT JOIN currency_decimal AS currency_decimal_rgm_ocur
  ON acdoca.rgm_ocur = currency_decimal_rgm_ocur.currkey
LEFT JOIN date_dimension AS dimensional_date_budat
  ON acdoca.budat = dimensional_date_budat.date
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["acdoca"])
])}
`
);
