# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ecc:
  material_valuation:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, hourly]
  material_valuation_history:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, hourly]
  material_valuation_area:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: masterdata
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, masterdata,
      monthly]
  material_ledger_header:
    enabled: false
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, daily]
  material_ledger_period_totals:
    enabled: false
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, daily]
s4:
  material_ledger_header:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, daily]
  material_ledger_period_totals:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: transactional
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, 
        transactional, daily]
  material_valuation_area:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: supply_chain
    - key: sap_module
      value: sap_mm
    - key: data_class
      value: masterdata
    dataformTags: [sap, supply_chain, sap_mm, source_aligned_product, masterdata,
      monthly]
