/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "document_number_vbeln",
    "item_number_posnr"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
), currency_decimal as (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  lips.mandt AS client_mandt,
  lips.vbeln AS document_number_vbeln,
  lips.posnr AS item_number_posnr,
  lips.pstyv AS item_category_pstyv,
  lips.ernam AS created_by_ernam,
  lips.erzet AS creation_time_erzet,
  lips.erdat AS creation_date_erdat,
  lips.matnr AS material_number_matnr,
  lips.matwa AS material_entered_matwa,
  lips.matkl AS material_group_matkl,
  lips.werks AS plant_werks,
  lips.lgort AS storage_location_lgort,
  lips.charg AS batch_number_charg,
  lips.lichn AS vendor_batch_number_lichn,
  lips.kdmat AS material_belonging_to_the_customer_kdmat,
  lips.prodh AS product_hierarchy_prodh,
  lips.lfimg AS actual_quantity_delivered_in_sales_units_lfimg,
  lips.meins AS base_unit_of_measure_meins,
  lips.vrkme AS sales_unit_vrkme,
  lips.umvkz AS numerator_factor_for_conversion_of_sales_quantity_into_sku_umvkz,
  lips.umvkn AS denominator_divisor_for_conversion_of_sales_qty_into_sku_umvkn,
  lips.ntgew AS net_weight_ntgew,
  lips.brgew AS gross_weight_brgew,
  lips.gewei AS weight_unit_gewei,
  lips.volum AS volume_volum,
  lips.voleh AS volume_unit_voleh,
  lips.kztlf AS partial_delivery_at_item_level_kztlf,
  lips.uebtk AS indicator_unlimited_overdelivery_allowed_uebtk,
  lips.uebto AS overdelivery_tolerance_limit_uebto,
  lips.untto AS underdelivery_tolerance_limit_untto,
  lips.chspl AS batch_split_allowed_chspl,
  lips.faksp AS billing_block_faksp,
  lips.mbdat AS material_availability_date_mbdat,
  lips.lgmng AS actual_quantity_delivered_in_stock_keeping_units_lgmng,
  lips.arktx AS short_text_for_sales_order_item_arktx,
  lips.lgpbe AS storage_bin_lgpbe,
  lips.vbelv AS originating_document_vbelv,
  lips.posnv AS originating_item_posnv,
  lips.vbtyv AS sd_document_category_vbtyv,
  lips.vgsys AS logical_system_in_the_preceding_document_vgsys,
  lips.vgbel AS internal_reference_document_number_vgbel,
  lips.vgpos AS internal_reference_document_item_vgpos,
  lips.upflu AS update_indicator_for_delivery_document_flow_upflu,
  lips.uepos AS higher_level_item_in_bom_uepos,
  lips.fkrel AS relevant_for_billing_fkrel,
  lips.ladgr AS loading_group_ladgr,
  lips.tragr AS transportation_group_tragr,
  lips.komkz AS indicator_for_picking_control_komkz,
  lips.lgnum AS warehouse_number_lgnum,
  lips.lispl AS split_to_warehouse_number_required_lispl,
  lips.lgtyp AS storage_type_lgtyp,
  lips.lgpla AS storage_bin_lgpla,
  lips.bwtex AS indicator_separate_valuation_bwtex,
  lips.bwart AS movement_type_inventory_management_bwart,
  lips.bwlvs AS movement_type_for_warehouse_management_bwlvs,
  lips.kzdlg AS indicator_dynamic_storage_bin_in_warehouse_management_kzdlg,
  lips.bdart AS requirement_type_bdart,
  lips.plart AS planning_type_plart,
  lips.mtart AS material_type_mtart,
  lips.xchpf AS batch_management_requirement_indicator_xchpf,
  lips.xchar AS batch_management_indicator_internal_xchar,
  lips.vgref AS preceding_document_has_resulted_from_reference_vgref,
  lips.posar AS item_type_posar,
  lips.bwtar AS valuation_type_bwtar,
  lips.sumbd AS summing_up_of_requirements_sumbd,
  lips.mtvfp AS checking_group_for_availability_mtvfp,
  lips.eannr AS european_article_number_eannr,
  lips.gsber AS business_area_gsber,
  lips.vkbur AS sales_office_vkbur,
  lips.vkgrp AS sales_group_vkgrp,
  lips.vtweg AS distribution_channel_vtweg,
  lips.spart AS division_spart,
  lips.grkor AS delivery_group_items_are_delivered_together_grkor,
  lips.fmeng AS quantity_is_fixed_fmeng,
  lips.antlf AS maximum_number_of_partial_deliveries_allowed_per_item_antlf,
  lips.vbeaf AS fixed_shipping_processing_time_in_days_vbeaf,
  lips.vbeav AS variable_shipping_processing_time_in_days_vbeav,
  lips.stafo AS update_group_for_statistics_update_stafo,
  ${currency.amountWithDecimalShift("lips.wavwr", "currency_decimal")} AS cost_in_document_currency_wavwr,
  ${currency.amountWithDecimalShift("lips.kzwi1", "currency_decimal")} AS subtotal1_from_pricing_procedure_for_condition_kzwi1,
  ${currency.amountWithDecimalShift("lips.kzwi2", "currency_decimal")} AS subtotal2_from_pricing_procedure_for_condition_kzwi2,
  ${currency.amountWithDecimalShift("lips.kzwi3", "currency_decimal")} AS subtotal3_from_pricing_procedure_for_condition_kzwi3,
  ${currency.amountWithDecimalShift("lips.kzwi4", "currency_decimal")} AS subtotal4_from_pricing_procedure_for_condition_kzwi4,
  ${currency.amountWithDecimalShift("lips.kzwi5", "currency_decimal")} AS subtotal5_from_pricing_procedure_for_condition_kzwi5,
  ${currency.amountWithDecimalShift("lips.kzwi6", "currency_decimal")} AS subtotal6_from_pricing_procedure_for_condition_kzwi6,
  lips.sobkz AS special_stock_indicator_sobkz,
  lips.aedat AS changed_on_aedat,
  lips.ean11 AS international_article_number_eanupc_ean11,
  lips.kvgr1 AS customer_group1_kvgr1,
  lips.kvgr2 AS customer_group2_kvgr2,
  lips.kvgr3 AS customer_group3_kvgr3,
  lips.kvgr4 AS customer_group4_kvgr4,
  lips.kvgr5 AS customer_group5_kvgr5,
  lips.mvgr1 AS material_group1_mvgr1,
  lips.mvgr2 AS material_group2_mvgr2,
  lips.mvgr3 AS material_group3_mvgr3,
  lips.mvgr4 AS material_group4_mvgr4,
  lips.mvgr5 AS material_group5_mvgr5,
  lips.vpzuo AS allocation_indicator_vpzuo,
  lips.vgtyp AS sd_document_category_vgtyp,
  lips.rfvgtyp AS type_of_preceding_document_in_central_system_rfvgtyp,
  lips.kostl AS cost_center_kostl,
  lips.kokrs AS controlling_area_kokrs,
  lips.paobjnr AS profitability_segment_number_paobjnr,
  lips.prctr AS profit_center_prctr,
  lips.ps_psp_pnr AS work_breakdown_structure_element_wbs_element_ps_psp_pnr,
  lips.aufnr AS order_number_aufnr,
  lips.posnr_pp AS order_item_number_posnr_pp,
  lips.kdauf AS sales_order_number_kdauf,
  lips.kdpos AS item_number_in_sales_order_kdpos,
  lips.vpmat AS planning_material_vpmat,
  lips.vpwrk AS planning_plant_vpwrk,
  lips.prbme AS base_unit_of_measure_for_product_group_prbme,
  lips.umref AS conversion_factor_quantities_umref,
  lips.knttp AS account_assignment_category_knttp,
  lips.kzvbr AS consumption_posting_kzvbr,
  lips.fipos AS commitment_item_fipos,
  lips.fistl AS funds_center_fistl,
  lips.geber AS fund_geber,
  lips.pckpf AS packing_control_pckpf,
  lips.bedar_lf AS requirements_class_bedar_lf,
  lips.cmpnt AS id_item_with_active_credit_function_relevant_for_credit_cmpnt,
  lips.kcmeng AS cumulative_batch_quantity_of_all_split_items_in_stckunit_kcmeng,
  lips.kcbrgew AS cumulative_gross_weight_of_all_batch_split_items_kcbrgew,
  lips.kcntgew AS cumulative_net_weight_of_all_batch_split_items_kcntgew,
  lips.kcvolum AS cumulative_volume_of_all_batch_split_items_kcvolum,
  lips.uecha AS higher_level_item_of_batch_split_item_uecha,
  lips.cuobj AS configuration_cuobj,
  lips.cuobj_ch AS internal_object_number_of_the_batch_classification_cuobj_ch,
  lips.anzsn AS number_of_serial_numbers_anzsn,
  lips.serail AS serial_number_profile_serail,
  lips.kcgewei AS weight_unit_kcgewei,
  lips.kcvoleh AS volume_unit_kcvoleh,
  lips.sernr AS bom_explosion_number_sernr,
  lips.abrli AS internal_delivery_schedule_number_abrli,
  lips.abart AS rel_type_abart,
  lips.abrvw AS usage_indicator_abrvw,
  lips.qplos AS inspection_lot_number_qplos,
  lips.qtlos AS partial_lot_number_qtlos,
  lips.nachl AS customer_has_not_posted_goods_receipt_nachl,
  lips.magrv AS material_group_packaging_materials_magrv,
  lips.objko AS object_number_at_header_level_objko,
  lips.objpo AS object_number_at_item_level_objpo,
  lips.aeskd AS customer_engineering_change_status_aeskd,
  lips.shkzg AS returns_item_shkzg,
  lips.prosa AS id_for_material_determination_prosa,
  lips.uepvw AS higher_level_item_usage_uepvw,
  lips.empst AS receiving_point_empst,
  lips.abtnr AS department_number_abtnr,
  lips.koqui AS picking_is_subject_to_confirmation_koqui,
  lips.stadat AS statistics_date_stadat,
  lips.aktnr AS promotion_aktnr,
  lips.knumh_ch AS number_of_condition_record_from_batch_determination_knumh_ch,
  lips.prefe AS preference_indicator_in_exportimport_prefe,
  lips.exart AS business_transaction_type_for_foreign_trade_exart,
  lips.clint AS internal_class_number_clint,
  lips.chmvs AS batches_exit_to_quantity_proposal_chmvs,
  lips.abeln AS allocation_table_number_abeln,
  lips.abelp AS item_number_of_allocation_table_abelp,
  lips.lfimg_flo AS internal_field_do_not_use_lfimg_in_float_mum_lfimg_flo,
  lips.lgmng_flo AS internal_field_do_not_use_lgmng_in_float_mum_lgmng_flo,
  lips.kcmeng_flo AS internal_field_do_not_use_kcmeng_in_float_mum_kcmeng_flo,
  lips.kzumw AS environmentally_relevant_kzumw,
  lips.kmpmg AS component_quantity_kmpmg,
  lips.aurel AS relevant_to_allocation_table_aurel,
  lips.kpein AS condition_pricing_unit_kpein,
  lips.kmein AS condition_unit_kmein,
  ${currency.amountWithDecimalShift("lips.netpr", "currency_decimal")} AS net_price_netpr,
  ${currency.amountWithDecimalShift("lips.netwr", "currency_decimal")} AS net_value_in_document_currency_netwr,
  lips.kzbew AS movement_indicator_kzbew,
  lips.mfrgr AS material_freight_group_mfrgr,
  lips.chhpv AS pack_accumulated_batches_movement_type_item_chhpv,
  lips.abfor AS form_of_payment_guarantee_abfor,
  lips.abges AS guaranteed_factor_between0_and1_abges,
  lips.mbuhr AS material_staging_time_mbuhr,
  lips.wktnr AS value_contract_no_wktnr,
  lips.wktps AS value_contract_item_wktps,
  lips.j_1bcfop AS cfop_code_and_extension_j_1_bcfop,
  lips.j_1btaxlw1 AS tax_law_icms_j_1_btaxlw1,
  lips.j_1btaxlw2 AS tax_law_ipi_j_1_btaxlw2,
  lips.j_1btxsdc AS sd_tax_code_j_1_btxsdc,
  lips.situa AS indicator_for_situation_situa,
  lips.rsnum AS number_of_reservationdependent_requirements_rsnum,
  lips.rspos AS item_number_of_reservation_dependent_requirements_rspos,
  lips.rsart AS record_type_rsart,
  lips.kannr AS kanbansequence_number_kannr,
  lips.kzfme AS id_leading_unit_of_measure_for_completing_a_transaction_kzfme,
  lips.profl AS dangerous_goods_indicator_profile_profl,
  lips.kcmengvme AS cumulative_batch_quantity_of_all_split_items_in_sales_units_kcmengvme,
  lips.kcmengvmef AS cumulated_batch_split_quantity_in_vrkme_and_float_kcmengvmef,
  lips.kzbws AS valuation_of_special_stock_kzbws,
  lips.pspnr AS project_definition_internal_pspnr,
  lips.eprio AS withdrawal_sequence_group_for_stocks_eprio,
  lips.rules AS stock_determination_rule_rules,
  lips.kzbef AS indicator_inventory_management_active_kzbef,
  lips.mprof AS mfr_part_profile_mprof,
  lips.ematn AS material_number_corresponding_to_manufacturer_part_number_ematn,
  lips.lgbzo AS staging_area_for_warehouse_complex_lgbzo,
  lips.handle AS worldwide_unique_key_forlips_handle,
  lips.verurpos AS distribution_delivery_original_item_verurpos,
  lips.lifexpos AS external_item_number_lifexpos,
  lips.noatp AS indicator_deactivate_availability_check_noatp,
  lips.nopck AS indicator_not_relevant_for_picking_nopck,
  lips.rblvs AS reference_movement_type_for_wm_from_material_movements_rblvs,
  lips.berid AS mrp_area_berid,
  lips.bestq AS stock_category_in_the_warehouse_management_system_bestq,
  lips.umbsq AS stock_category_in_the_warehouse_management_system_umbsq,
  lips.ummat AS receiving_issuing_material_ummat,
  lips.umwrk AS receiving_plant_issuing_plant_umwrk,
  lips.umlgo AS receiving_issuing_storage_location_umlgo,
  lips.umcha AS receiving_issuing_batch_umcha,
  lips.umbar AS valuation_type_of_transfer_batch_umbar,
  lips.umsok AS special_stock_indicator_for_physical_stock_transfer_umsok,
  lips.sonum AS special_stock_number_sonum,
  lips.usonu AS special_stock_number_usonu,
  lips.akkur AS exchange_rate_for_letter_foreign_trade_akkur,
  lips.akmng AS current_qty_field_for_arithmetic_operations_akmng,
  lips.vkgru AS repair_processing_classification_of_items_vkgru,
  lips.shkzg_um AS indicator_unmat_in_main_posting_shkzg_um,
  lips.insmk AS stock_type_insmk,
  lips.kzech AS determination_of_batch_entry_in_the_productionprocess_order_kzech,
  lips.flgwm AS dest_storage_data_from_preceding_document_flgwm,
  lips.berkz AS material_staging_indicator_for_production_supply_berkz,
  lips.hupos AS indicator_delivery_item_is_a_hu_item_hupos,
  lips.nowab AS indicator_item_not_relevant_for_goods_movements_nowab,
  lips.konto AS gl_account_number_konto,
  lips.kzear AS final_issue_for_this_reservation_kzear,
  lips.hsdat AS date_of_manufacture_hsdat,
  lips.vfdat AS best_before_date_vfdat,
  lips.lfgja AS fiscal_year_of_current_period_lfgja,
  lips.lfbnr AS a_reference_document_lfbnr,
  lips.lfpos AS item_of_a_reference_document_lfpos,
  lips.grund AS reason_for_goods_movment_grund,
  lips.fobwa AS subsequent_movement_type_fobwa,
  lips.dlvtp AS delivery_category_dlvtp,
  ${currency.amountWithDecimalShift("lips.exbwr", "currency_decimal")} AS externally_entered_posting_amount_in_local_currency_exbwr,
  lips.bpmng AS quantity_in_purchase_order_price_unit_bpmng,
  ${currency.amountWithDecimalShift("lips.exvkw", "currency_decimal")} AS externally_entered_sales_value_in_local_currency_exvkw,
  lips.cmpre_flt AS item_credit_price_cmpre_flt,
  lips.kzpod AS pod_indicator_kzpod,
  lips.lfdez AS not_relevant_for_distribution_for_wms_lfdez,
  lips.umrev AS conversion_factor_of_delivery_quantity_vrkme_for_meins_umrev,
  lips.podrel AS pod_control_proof_of_delivery_podrel,
  lips.kzuml AS stock_transfertransfer_posting_kzuml,
  lips.fkber AS functional_area_fkber,
  lips.grant_nbr AS grant_grant_nbr,
  lips.kzwso AS units_of_measure_usage_kzwso,
  lips.gmcontrol AS goods_movement_control_gmcontrol,
  lips.posting_change AS goods_movement_control_hu_posting_change,
  lips.um_ps_psp_pnr AS receivingissuing_wbs_element_um_ps_psp_pnr,
  lips.pre_vl_etens AS sequential_number_of_vendor_confirmation_pre_vl_etens,
  lips.spe_gen_elikz AS delivery_completed_spe_gen_elikz,
  lips.spe_scrap_ind AS scrap_indicator_for_ewm_processing_spe_scrap_ind,
  lips.spe_auth_number AS return_material_authorization_number_spe_auth_number,
  lips.spe_inspout_guid AS inspections_inspection_outcome_guid_set_by_ewm_spe_inspout_guid,
  lips.spe_follow_up AS default_follow_spe_follow_up,
  lips.spe_exp_date_ext AS end_date_of_validity_period_of_returns_delivery_spe_exp_date_ext,
  lips.spe_exp_date_int AS end_date_of_internal_validity_period_of_returns_delivery_spe_exp_date_int,
  lips.spe_auth_complet AS rma_completion_indicator_spe_auth_complet,
  lips.ormng AS original_quantity_of_delivery_item_ormng,
  lips.spe_atp_tmstmp AS atp_time_stamp_spe_atp_tmstmp,
  lips.spe_orig_sys AS original_system_type_itm_spe_orig_sys,
  lips.spe_lieffz AS cumulative_qty_for_schedagr_vendor_pov_spe_lieffz,
  lips.spe_imwrk AS inbound_delivery_item_has_statusin_plant_spe_imwrk,
  lips.spe_lifexpos2 AS external_item_identifier_spe_lifexpos2,
  lips.spe_except_code AS exception_code_warehouse_for_quantity_difference_spe_except_code,
  lips.spe_keep_qty AS retention_quantity_for_scrap_spe_keep_qty,
  lips.spe_alternate AS alternate_product_number_spe_alternate,
  lips.spe_mat_subst AS reason_for_material_substitution_spe_mat_subst,
  lips.spe_struc AS structure_of_items_that_are_delivered_together_spe_struc,
  lips.spe_apo_qntyfac AS numerator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntyfac,
  lips.spe_apo_qntydiv AS denominator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntydiv,
  lips.spe_herkl AS non_preferential_origin_spe_herkl,
  lips.spe_bxp_date_ext AS begin_date_of_validity_period_of_returns_delivery_spe_bxp_date_ext,
  lips.spe_version AS delivery_version_at_confirmation_spe_version,
  lips.spe_compl_mvt AS completion_of_goods_movements_after_difference_postings_spe_compl_mvt,
  lips.j_1btaxlw4 AS cofins_tax_law_j_1_btaxlw4,
  lips.j_1btaxlw5 AS pis_tax_law_j_1_btaxlw5,
  lips.j_1btaxlw3 AS iss_tax_law_j_1_btaxlw3,
  lips.budget_pd AS fm_budget_period_budget_pd,
  lips.kbnkz AS kanban_indicator_kbnkz,
  lips.sitkz AS specification_for_issuing_valuated_stock_in_transit_sitkz,
  lips.cons_order AS purchase_order_for_consignment_cons_order,
  lips.aufpl AS routing_number_for_operations_aufpl,
  lips.aplzl AS counter_aplzl,
  lips.farr_reltype AS revenue_accounting_type_farr_reltype,
  lips.sgt_rcat AS requirement_segment_sgt_rcat,
  lips.sgt_scat AS stock_segment_sgt_scat,
  lips.resource_id AS delivery_item_resource_id_resource_id,
  lips.loading_point AS loading_unloading_point_loading_point,
  lips.solution_order_id AS solution_order_id,
  lips.solution_order_itm_id AS item_number_in_document_solution_order_itm_id,
  lips.spe_herkr AS region_of_origin_spe_herkr,
  lips.itm_comco AS commodity_code_itm_comco,
  lips.besta AS item_status_besta,
  lips.cmppi AS credit_management_item_status_cmppi,
  lips.cmppj AS credit_management_payment_card_status_cmppj,
  lips.fkivp AS intercompany_billing_status_fkivp,
  lips.fksta AS delivery_related_billing_status_fksta,
  lips.gbsta AS sd_process_status_gbsta,
  lips.hdall AS delivery_item_not_complete_hdall,
  lips.koqua AS picking_confirmation_status_koqua,
  lips.kosta AS picking_status_kosta,
  lips.lvsta AS warehouse_activity_status_lvsta,
  lips.pdsta AS proof_of_delivery_status_pdsta,
  lips.pksta AS packing_status_pksta,
  lips.uvall AS item_general_incompletion_status_uvall,
  lips.uvfak AS item_billing_incompletion_status_uvfak,
  lips.uvpak AS item_packing_incompletion_status_uvpak,
  lips.uvpik AS item_picking_incompletion_status_uvpik,
  lips.uvvlk AS item_delivery_incompletion_status_uvvlk,
  lips.uvwak AS item_goods_movement_incompletion_status_uvwak,
  lips.vlstp AS distribution_status_vlstp,
  lips.wbsta AS goods_movement_status_wbsta,
  lips.uvp01 AS incompletion_status_1_uvp01,
  lips.uvp02 AS incompletion_status_2_uvp02,
  lips.uvp03 AS incompletion_status_3_uvp03,
  lips.uvp04 AS incompletion_status_4_uvp04,
  lips.uvp05 AS incompletion_status_5_uvp05,
  lips.emcst AS trade_compliance_embargo_status_emcst,
  lips.slcst AS trade_compliance_sanctioned_list_check_status_slcst,
  lips.lccst AS trade_compliance_legal_control_status_lccst,
  lips.pcsta AS chemical_compliance_status_pcsta,
  lips.dgsta AS dangerous_goods_status_dgsta,
  lips.sdssta AS safety_data_sheet_status_sdssta,
  lips.sapmp_lbasp AS dtuc_status_sapmp_lbasp,
  lips.arc_status AS eu_delivery_item_arc_status_arc_status,
  lips.cwm_lfimg AS delivery_quantity_parallel_unit_of_measure_cwm_lfimg,
  lips.cwm_lfime AS cwm_delivery_unit_cwm_lfime,
  lips.cwm_pikmg AS picked_quantity_parallel_unit_of_measure_cwm_pikmg,
  lips.cwm_pikme AS parallel_unit_of_measure_picked_quantity_cwm_pikme,
  lips.cwm_xenter AS parallel_quantity_entered_cwm_xenter,
  lips.cwm_xtaenter AS transfer_order_cwm_xtaenter,
  lips.cwm_kcmeng AS accumulated_cw_batch_quantity_cwm_kcmeng,
  lips.cwm_ebumg AS quantity_to_be_posted_parallel_unit_of_measure_cwm_ebumg,
  lips.dummy_delitm_incl_eew_ps AS dummy_delivery_item_dummy_delitm_incl_eew_ps,
  lips.kjedm_inverted AS inverted_kjedm_inverted,
  lips.sapmp_lba_no AS dtuc_sapmp_lba_no,
  lips.sapmp_alt_conv AS provisional_conversion_factors_sapmp_alt_conv,
  lips.lgtor AS door_lgtor,
  dimensional_date_erdat.cal_year AS year_of_creation_date_erdat,
  dimensional_date_erdat.cal_month AS month_of_creation_date_erdat,
  dimensional_date_erdat.cal_week AS week_of_creation_date_erdat,
  dimensional_date_erdat.day_of_month AS day_of_month_of_creation_date_erdat,
  dimensional_date_erdat.cal_quarter AS quarter_of_creation_date_erdat,
  IFNULL(
    lips.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "lips")} AS lips
LEFT JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'likp')} as likp
  ON lips.mandt = likp.mandt
  AND lips.vbeln = likp.vbeln
LEFT JOIN date_dimension AS dimensional_date_erdat
  ON lips.erdat = dimensional_date_erdat.date
LEFT JOIN currency_decimal
  ON likp.waerk = currency_decimal.currkey
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["lips"])
])}
`
);