/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "document_number_vbeln"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
),
currency_decimal AS (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  likp.mandt AS client_mandt,
  likp.vbeln AS document_number_vbeln,
  likp.ernam AS created_by_ernam,
  likp.erzet AS creation_time_erzet,
  likp.erdat AS creation_date_erdat,
  likp.bzirk AS sales_district_bzirk,
  likp.vstel AS shipping_point_receiving_point_vstel,
  likp.vkorg AS sales_organization_vkorg,
  likp.lfart AS delivery_type_lfart,
  likp.autlf AS complete_delivery_defined_indicator_autlf,
  likp.kzazu AS order_combination_indicator_kzazu,
  likp.wadat AS planned_goods_movement_date_wadat,
  likp.lddat AS loading_date_lddat,
  likp.tddat AS transportation_planning_date_tddat,
  likp.lfdat AS delivery_date_lfdat,
  likp.kodat AS picking_date_kodat,
  likp.ablad AS unloading_point_ablad,
  likp.inco1 AS incoterms_part1_inco1,
  likp.inco2 AS incoterms_part2_inco2,
  likp.expkz AS export_indicator_expkz,
  likp.route AS route_route,
  likp.faksk AS billing_block_in_sales_document_faksk,
  likp.lifsk AS delivery_block_document_header_lifsk,
  likp.vbtyp AS sales_document_category_vbtyp,
  likp.knfak AS customer_factory_calendar_knfak,
  likp.lprio AS delivery_priority_lprio,
  likp.vsbed AS shipping_conditions_vsbed,
  likp.kunnr AS ship_to_party_kunnr,
  likp.kunag AS sold_to_party_kunag,
  likp.kdgrp AS customer_group_kdgrp,
  likp.btgew AS total_weight_btgew,
  likp.ntgew AS net_weight_ntgew,
  likp.gewei AS weight_unit_gewei,
  likp.volum AS volume_volum,
  likp.voleh AS volume_unit_voleh,
  likp.anzpk AS total_packages_anzpk,
  likp.berot AS picked_items_location_berot,
  likp.lfuhr AS delivery_time_lfuhr,
  likp.grulg AS weight_group_grulg,
  likp.lstel AS loading_point_lstel,
  likp.tragr AS transportation_group_tragr,
  likp.fkarv AS proposed_billing_type_fkarv,
  likp.fkdat AS proposed_billing_date_fkdat,
  likp.perfk AS invoice_dates_perfk,
  likp.routa AS route_routa,
  likp.stafo AS update_group_for_statistics_stafo,
  likp.kalsm AS procedure_kalsm,
  likp.knumv AS condition_number_knumv,
  likp.waerk AS sales_document_currency_key_waerk,
  likp.vkbur AS sales_office_vkbur,
  likp.vbeak AS shipping_processing_time_vbeak,
  likp.zukrl AS delivery_combination_criteria_zukrl,
  likp.verur AS distribution_delivery_verur,
  likp.commn AS communication_number_commn,
  likp.stwae AS statistics_currency_stwae,
  likp.stcur AS statistics_exchange_rate_stcur,
  likp.exnum AS foreign_trade_data_number_exnum,
  likp.aenam AS changed_by_aenam,
  likp.aedat AS changed_on_aedat,
  likp.lgnum AS warehouse_number_lgnum,
  likp.lispl AS delivery_within_one_warehouse_lispl,
  likp.vkoiv AS intercompany_billing_sales_organization_vkoiv,
  likp.vtwiv AS intercompany_billing_distribution_channel_vtwiv,
  likp.spaiv AS intercompany_billing_division_spaiv,
  likp.fkaiv AS intercompany_billing_type_fkaiv,
  likp.pioiv AS intercompany_billing_price_date_pioiv,
  likp.fkdiv AS intercompany_billing_date_fkdiv,
  likp.kuniv AS intercompany_billing_customer_number_kuniv,
  likp.kkber AS credit_control_area_kkber,
  likp.knkli AS credit_account_knkli,
  likp.grupp AS customer_credit_group_grupp,
  likp.sbgrp AS credit_representative_group_sbgrp,
  likp.ctlpc AS credit_management_risk_category_ctlpc,
  likp.cmwae AS credit_control_area_currency_key_cmwae,
  likp.amtbl AS released_credit_value_amtbl,
  likp.bolnr AS bill_of_lading_bolnr,
  likp.lifnr AS vendor_account_number_lifnr,
  likp.traty AS means_of_transport_type_traty,
  likp.traid AS means_of_transport_id_traid,
  likp.cmfre AS credit_release_date_cmfre,
  likp.cmngv AS next_date_cmngv,
  likp.xabln AS goods_receipt_issue_slip_number_xabln,
  likp.bldat AS document_date_bldat,
  likp.wadat_ist AS actual_goods_movement_date_wadat_ist,
  likp.trspg AS shipment_blocking_reason_trspg,
  likp.tpsid AS external_transport_system_id_tpsid,
  likp.lifex AS external_delivery_note_id_lifex,
  likp.ternr AS order_number_ternr,
  likp.kalsm_ch AS batch_search_procedure_kalsm_ch,
  likp.klief AS correction_delivery_klief,
  likp.kalsp AS shipping_pricing_procedure_kalsp,
  likp.knump AS pricing_condition_number_knump,
  ${currency.amountWithDecimalShift("likp.netwr", "currency_decimal")} AS net_value_in_document_currency_netwr,
  likp.aulwe AS route_schedule_aulwe,
  likp.werks AS receiving_plant_werks,
  likp.lcnum AS internal_financial_document_number_lcnum,
  likp.abssc AS payment_guarantee_procedure_abssc,
  likp.kouhr AS picking_time_kouhr,
  likp.tduhr AS transportation_planning_time_tduhr,
  likp.lduhr AS loading_time_lduhr,
  likp.wauhr AS goods_issue_time_wauhr,
  likp.lgtor AS warehouse_door_number_lgtor,
  likp.lgbzo AS warehouse_staging_area_lgbzo,
  likp.akwae AS foreign_trade_currency_key_akwae,
  likp.akkur AS foreign_trade_exchange_rate_akkur,
  likp.akprz AS depreciation_percentage_akprz,
  likp.proli AS dangerous_goods_management_profile_proli,
  likp.xblnr AS reference_document_number_xblnr,
  likp.handle AS worldwide_unique_key_handle,
  likp.tsegfl AS time_segment_exists_indicator_tsegfl,
  likp.tsegtp AS event_group_time_segment_delivery_header_tsegtp,
  likp.tzonis AS delivery_location_timezone_tzonis,
  likp.tzonrc AS recipient_location_timezone_tzonrc,
  likp.cont_dg AS dangerous_goods_indicator_cont_dg,
  likp.verursys AS distribution_delivery_original_system_verursys,
  likp.kzwab AS goods_movement_control_indicator_kzwab,
  likp.vlstk AS distribution_status_vlstk,
  likp.tcode AS transaction_code_tcode,
  likp.vsart AS shipping_type_vsart,
  likp.trmtyp AS means_of_transport_trmtyp,
  likp.sdabw AS special_processing_indicator_sdabw,
  likp.vbund AS company_id_vbund,
  likp.xwoff AS calculation_of_value_open_indicator_xwoff,
  likp.dirta AS automatic_transportation_order_creation_indicator_dirta,
  likp.prvbe AS production_supply_area_prvbe,
  likp.folar AS delivery_type_folar,
  likp.podat AS proof_of_delivery_date_podat,
  likp.potim AS proof_of_delivery_confirmation_time_potim,
  likp.vganz AS shipment_document_total_count_vganz,
  likp.imwrk AS goods_movement_within_company_code_indicator_imwrk,
  likp.spe_loekz AS document_deletion_indicator_spe_loekz,
  likp.spe_loc_seq AS locations_sequenece_number_spe_loc_seq,
  likp.spe_acc_app_sts AS delivery_confirmation_status_spe_acc_app_sts,
  likp.spe_shp_inf_sts AS shipment_information_status_spe_shp_inf_sts,
  likp.spe_ret_canc AS return_document_cancellation_indicator_spe_ret_canc,
  likp.spe_wauhr_ist AS goods_issue_time_spe_wauhr_ist,
  likp.spe_wazone_ist AS goods_issue_time_zone_spe_wazone_ist,
  likp.spe_rev_vlstk AS revenue_recognition_status_spe_rev_vlstk,
  likp.spe_le_scenario AS logistics_execution_scenario_spe_le_scenario,
  likp.spe_orig_sys AS original_system_type_spe_orig_sys,
  likp.spe_chng_sys AS last_changer_system_type_spe_chng_sys,
  likp.spe_georoute AS geographical_route_description_spe_georoute,
  likp.spe_georouteind AS route_change_indicator_spe_georouteind,
  likp.spe_carrier_ind AS carrier_change_indicator_spe_carrier_ind,
  likp.spe_gts_rel AS goods_traffic_type_spe_gts_rel,
  likp.spe_gts_rt_cde AS sap_global_trade_services_route_code_spe_gts_rt_cde,
  likp.spe_rel_tmstmp AS release_time_stamp_spe_rel_tmstmp,
  likp.spe_unit_system AS measurement_unit_system_spe_unit_system,
  likp.spe_inv_bfr_gi AS invoice_creation_before_goods_issue_spe_inv_bfr_gi,
  likp.spe_qi_status AS return_delivery_quality_inspection_status_spe_qi_status,
  likp.spe_red_ind AS redirection_indicator_spe_red_ind,
  likp.sakes AS sap_global_trade_services_delivery_storage_status_sakes,
  likp.spe_lifex_type AS external_identification_type_spe_lifex_type,
  likp.spe_ttype AS means_of_transport_spe_ttype,
  likp.spe_pro_number AS progressive_identification_number_spe_pro_number,
  likp.loc_guid AS location_guid_loc_guid,
  likp.spe_billing_ind AS ewm_billing_indicator_spe_billing_ind,
  likp.printer_profile AS print_profile_description_printer_profile,
  likp.msr_active AS advanced_returns_management_active_msr_active,
  likp.prtnr AS confirmation_number_prtnr,
  likp.stge_loc_change AS storage_location_change_stge_loc_change,
  likp.tm_ctrl_key AS document_transfer_control_key_tm_ctrl_key,
  likp.dlv_split_initia AS delivery_split_initiator_dlv_split_initia,
  likp.dlv_version AS delivery_version_dlv_version,
  likp.gts_vorpa AS previous_document_type_gts_vorpa,
  likp.gts_vornu AS previous_document_number_gts_vornu,
  likp.gts_expvz AS intrastat_border_mode_of_transport_gts_expvz,
  likp.gts_porti AS port_airport_gts_porti,
  likp.itm_expvz AS border_means_of_transport_itm_expvz,
  likp.itm_stgbe AS origin_border_means_of_transport_itm_stgbe,
  likp.itm_kzgbe AS border_cross_means_of_transport_id_itm_kzgbe,
  likp.itm_vygid AS cross_border_conveyance_reference_id_itm_vygid,
  likp.itm_iever AS inland_means_of_transport_itm_iever,
  likp.itm_stabe AS country_of_origin_means_of_transport_itm_stabe,
  likp.itm_kzabe AS inland_means_of_transport_id_itm_kzabe,
  likp.handoverloc AS handover_location_handoverloc,
  likp.handoverdate AS handover_date_handoverdate,
  likp.handovertime AS handover_time_handovertime,
  likp.handovertzone AS handover_time_zone_handovertzone,
  likp.bestk AS delivery_confirmation_status_bestk,
  likp.cmpsc AS maximum_document_value_credit_check_status_cmpsc,
  likp.cmpsd AS terms_of_payment_credit_check_status_cmpsd,
  likp.cmpsi AS financial_document_credit_check_status_cmpsi,
  likp.cmpsj AS export_credit_insurance_credit_check_status_cmpsj,
  likp.cmpsk AS payment_card_authorization_credit_check_status_cmpsk,
  likp.cmps_cm AS sap_credit_management_credit_check_status_cmps_cm,
  likp.cmps_te AS sap_credit_management_technical_error_status_cmps_te,
  likp.cmgst AS credit_checks_overall_status_cmgst,
  likp.fkivk AS intercompany_billing_status_fkivk,
  likp.fkstk AS delivery_related_billing_status_fkstk,
  likp.gbstk AS overall_processing_status_gbstk,
  likp.hdall AS incomplete_inbound_delivery_header_indicator_hdall,
  likp.hdals AS incomplete_inbound_delivery_item_indicator_hdals,
  likp.koquk AS pick_confirmation_status_koquk,
  likp.kostk AS picking_status_kostk,
  likp.lvstk AS warehouse_management_status_lvstk,
  likp.pdstk AS pod_header_status_pdstk,
  likp.pkstk AS packing_status_pkstk,
  likp.spe_tmpid AS temporary_inbound_delivery_indicator_spe_tmpid,
  likp.spstg AS overall_header_block_status_spstg,
  likp.trsta AS transportation_planning_status_trsta,
  likp.uvall AS header_incompletion_status_uvall,
  likp.uvals AS items_incompletion_status_uvals,
  likp.uvfak AS header_billing_incompletion_status_uvfak,
  likp.uvfas AS items_billing_incompletion_status_uvfas,
  likp.uvpak AS header_packing_incompletion_status_uvpak,
  likp.uvpas AS items_packing_incompletion_status_uvpas,
  likp.uvpik AS header_picking_incompletion_status_uvpik,
  likp.uvpis AS items_picking_incompletion_status_uvpis,
  likp.uvvlk AS header_delivery_incompletion_status_uvvlk,
  likp.uvvls AS items_delivery_incompletion_status_uvvls,
  likp.uvwak AS header_goods_movement_incompletion_status_uvwak,
  likp.uvwas AS items_goods_movement_incompletion_status_uvwas,
  likp.vestk AS handling_unit_in_stock_indicator_vestk,
  likp.wbstk AS goods_movement_status_wbstk,
  likp.uvk01 AS header_customer_reserve_status1_suvk01,
  likp.uvk02 AS header_customer_reserve_status2_suvk02,
  likp.uvk03 AS header_customer_reserve_status3_suvk03,
  likp.uvk04 AS header_customer_reserve_status4_suvk04,
  likp.uvk05 AS header_customer_reserve_status5_suvk05,
  likp.uvs01 AS item_customer_reserve_status1_suvs01,
  likp.uvs02 AS item_customer_reserve_status2_suvs02,
  likp.uvs03 AS item_customer_reserve_status3_suvs03,
  likp.uvs04 AS item_customer_reserve_status4_suvs04,
  likp.uvs05 AS item_customer_reserve_status5_suvs05,
  likp.total_pcsta AS total_product_marketability_check_status_total_pcsta,
  likp.total_dgsta AS total_dangerous_goods_check_status_total_dgsta,
  likp.total_sdssta AS total_safety_data_sheet_check_status_total_sdssta,
  likp.total_arc_status AS excise_tax_total_header_status_total_arc_status,
  likp.sapmp_lbask AS dtuc_status_sapmp_lbask,
  likp.incov AS incoterms_version_incov,
  likp.inco2_l AS incoterms_location_1_inco2_l,
  likp.inco3_l AS incoterms_location_2_inco3_l,
  likp.oid_extbol AS external_billing_of_lading_oid_extbol,
  likp.oid_miscdl AS miscellaneous_delivery_number_oid_miscdl,
  likp.ext_bus_syst_id AS external_business_system_id_ext_bus_syst_id,
  likp.sitkz_db AS valuated_stock_in_transit_issue_specification_sitkz_db,
  likp.tm_adv_ship_recv AS advanced_shipping_receipt_relevance_indicator_tm_adv_ship_recv,
  likp.tm_whse_exec AS warehouse_execution_status_tm_whse_exec,
  likp.bev1_luleinh AS loading_units_bev1_luleinh,
  likp.bev1_rpfaess AS number_category_1_bev1_rpfaess,
  likp.bev1_rpkist AS number_category_2_bev1_rpkist,
  likp.bev1_rpcont AS number_category_3_bev1_rpcont,
  likp.bev1_rpsonst AS number_category_4_bev1_rpsonst,
  likp.bev1_rpflgnr AS tour_loading_sequqnce_number_bev1_rpflgnr,
  likp.idt_cur_evtloc AS tracking_last_notified_route_point_idt_cur_evtloc,
  likp.idt_cur_evtqua AS tracking_arrival_departure_indicator_idt_cur_evtqua,
  likp.idt_cur_evttst AS tracking_current_point_event_timestamp_idt_cur_evttst,
  likp.idt_cur_estloc AS tracking_current_point_time_estimation_base_point_idt_cur_estloc,
  likp.idt_cur_estqua AS tracking_current_point_arrival_departure_time_estimation_idt_cur_estqua,
  likp.idt_cur_esttst AS tracking_current_point_delivery_date_estimation_base_date_idt_cur_esttst,
  likp.idt_cur_wrkqua AS tracking_current_point_entry_qualifiers_idt_cur_wrkqua,
  likp.idt_pre_evtloc AS tracking_prior_point_idt_pre_evtloc,
  likp.idt_pre_evtqua AS tracking_prior_point_arrival_departure_indicator_idt_pre_evtqua,
  likp.idt_pre_evttst AS tracking_prior_point_event_timestamp_idt_pre_evttst,
  likp.idt_pre_estloc AS tracking_prior_point_time_estimation_base_point_idt_pre_estloc,
  likp.idt_pre_estqua AS tracking_prior_point_arrival_departure_time_estimation_idt_pre_estqua,
  likp.idt_pre_esttst AS tracking_prior_point_delivery_date_estimation_base_date_idt_pre_esttst,
  likp.idt_pre_wrkqua AS tracking_prior_point_entry_qualifiers_idt_pre_wrkqua,
  likp.idt_ref_estloc AS tracking_reference_point_time_estimation_base_point_idt_ref_estloc,
  likp.idt_ref_estqua AS tracking_reference_point_arrival_departure_time_estimation_idt_ref_estqua,
  likp.idt_ref_esttst AS tracking_reference_point_delivery_date_estimation_base_date_idt_ref_esttst,
  likp.idt_firm_lfdat AS delivery_date_time_commitment_level_idt_firm_lfdat,
  likp.idt_docnum AS document_number_idt_docnum,
  likp.borgr_grp AS multi_level_goods_receipt_automotive_borgr_grp,
  likp.kbnkz AS kanban_indicator_kbnkz,
  likp.rfm_psst_group AS psst_group_rfm_psst_group,
  likp.jit_rlvnt AS jit_relevant_indicator_jit_rlvnt,
  dimensional_date_lfdat.cal_year AS year_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_month AS month_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_quarter AS quarter_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_week AS week_of_delivery_date_lfdat,
  dimensional_date_podat.cal_year AS year_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_month AS month_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_quarter AS quarter_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_week AS week_of_proof_of_delivery_date_podat,
  dimensional_date_bldat.cal_year AS year_of_document_date_bldat,
  dimensional_date_bldat.cal_month AS month_of_document_date_bldat,
  dimensional_date_bldat.cal_quarter AS quarter_of_document_date_bldat,
  dimensional_date_bldat.cal_week AS week_of_document_date_bldat,
  IFNULL(
    likp.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at   
  FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "likp")} AS likp
LEFT JOIN currency_decimal
  ON likp.waerk = currency_decimal.currkey
LEFT JOIN date_dimension AS dimensional_date_lfdat
  ON likp.lfdat = dimensional_date_lfdat.date
LEFT JOIN date_dimension AS dimensional_date_podat
  ON likp.podat = dimensional_date_podat.date
LEFT JOIN date_dimension AS dimensional_date_bldat
  ON likp.bldat = dimensional_date_bldat.date
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["likp"])
])}
`
);