/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const date = require("includes/date.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "billing_document_vbeln",
    "item_posnr"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH 
  date_dimension AS (
    ${date.getDateDimension()}
  ),
  currency_decimal AS (
    ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
  )
SELECT
  vbrp.mandt AS client_mandt,
  vbrp.vbeln AS billing_document_vbeln,
  vbrp.posnr AS item_posnr,
  vbrp.uepos AS higher_level_item_uepos,
  vbrp.fkimg AS billed_quantity_fkimg,
  vbrp.vrkme AS sales_unit_vrkme,
  vbrp.umvkz AS numerator_umvkz,
  vbrp.umvkn AS denominator_umvkn,
  vbrp.meins AS base_unit_of_measure_meins,
  vbrp.smeng AS scale_quantity_smeng,
  vbrp.fklmg AS billing_qty_in_sku_fklmg,
  vbrp.lmeng AS required_quantity_lmeng,
  vbrp.ntgew AS net_weight_ntgew,
  vbrp.brgew AS gross_weight_brgew,
  vbrp.gewei AS weight_unit_gewei,
  vbrp.volum AS volume_volum,
  vbrp.voleh AS volume_unit_voleh,
  vbrp.gsber AS business_area_gsber,
  vbrp.prsdt AS pricing_date_prsdt,
  vbrp.fbuda AS serv_rendered_date_fbuda,
  vbrp.kursk AS exchange_rate_kursk,
  ${currency.amountWithDecimalShift("vbrp.netwr", "currency_decimal")} AS net_value_netwr,
  vbrp.vbelv AS originating_document_vbelv,
  vbrp.posnv AS item_posnv,
  vbrp.vgbel AS reference_document_vgbel,
  vbrp.vgpos AS reference_item_vgpos,
  vbrp.vgtyp AS preceding_doc_categ_vgtyp,
  vbrp.aubel AS sales_document_aubel,
  vbrp.aupos AS sales_document_item_aupos,
  vbrp.auref AS referenced_sales_document_auref,
  vbrp.matnr AS material_matnr,
  vbrp.arktx AS description_arktx,
  vbrp.pmatn AS pricing_ref_matl_pmatn,
  vbrp.charg AS batch_charg,
  vbrp.matkl AS material_group_matkl,
  vbrp.pstyv AS item_category_pstyv,
  vbrp.posar AS item_type_posar,
  vbrp.prodh AS product_hierarchy_prodh,
  vbrp.vstel AS shipping_point_receiving_pt_vstel,
  vbrp.atpkz AS replacement_part_atpkz,
  vbrp.spart AS division_spart,
  vbrp.pospa AS partner_item_pospa,
  vbrp.werks AS plant_werks,
  vbrp.aland AS country_aland,
  vbrp.wkreg AS region_of_dlv_plant_wkreg,
  vbrp.wkcou AS county_of_dlv_plant_wkcou,
  vbrp.wkcty AS city_of_deliv_plant_wkcty,
  vbrp.taxm1 AS tax_class_material_taxm1,
  vbrp.taxm2 AS taxclass2_matl_taxm2,
  vbrp.taxm3 AS taxclass3_matl_taxm3,
  vbrp.taxm4 AS taxclass4_matl_taxm4,
  vbrp.taxm5 AS taxclass5_matl_taxm5,
  vbrp.taxm6 AS taxclass6_matl_taxm6,
  vbrp.taxm7 AS taxclass7_matl_taxm7,
  vbrp.taxm8 AS taxclass8_matl_taxm8,
  vbrp.taxm9 AS taxclass9_matl_taxm9,
  vbrp.kowrr AS statistical_value_kowrr,
  vbrp.prsfd AS pricing_prsfd,
  vbrp.sktof AS cash_discount_sktof,
  vbrp.skfbp AS cash_disc_basis_skfbp,
  vbrp.kondm AS material_pricing_grp_kondm,
  vbrp.ktgrm AS acct_assignment_grp_ktgrm,
  vbrp.kostl AS cost_center_kostl,
  vbrp.bonus AS volume_rebate_group_bonus,
  vbrp.provg AS commission_group_provg,
  vbrp.eannr AS ean_number_eannr,
  vbrp.vkgrp AS sales_group_vkgrp,
  vbrp.vkbur AS sales_office_vkbur,
  vbrp.spara AS division_spara,
  vbrp.shkzg AS returns_shkzg,
  vbrp.ernam AS created_by_ernam,
  vbrp.erdat AS created_on_erdat,
  vbrp.erzet AS time_erzet,
  vbrp.bwtar AS valuation_type_bwtar,
  vbrp.lgort AS storage_location_lgort,
  vbrp.stafo AS update_group_stats_stafo,
  ${currency.amountWithDecimalShift("vbrp.wavwr", "currency_decimal")} AS cost_wavwr,
  vbrp.kzwi1 AS subtotal_1_kzwi1,
  vbrp.kzwi2 AS subtotal_2_kzwi2,
  vbrp.kzwi3 AS subtotal_3_kzwi3,
  vbrp.kzwi4 AS subtotal_4_kzwi4,
  vbrp.kzwi5 AS subtotal_5_kzwi5,
  vbrp.kzwi6 AS subtotal_6_kzwi6,
  vbrp.stcur AS exchange_rate_stats_stcur,
  vbrp.uvprs AS pricing_uvprs,
  vbrp.uvall AS general_uvall,
  vbrp.ean11 AS ean_upc_ean11,
  vbrp.prctr AS profit_center_prctr,
  vbrp.kvgr1 AS customer_group_1_kvgr1,
  vbrp.kvgr2 AS customer_group_2_kvgr2,
  vbrp.kvgr3 AS customer_group_3_kvgr3,
  vbrp.kvgr4 AS customer_group_4_kvgr4,
  vbrp.kvgr5 AS customer_group_5_kvgr5,
  vbrp.mvgr1 AS material_group_1_mvgr1,
  vbrp.mvgr2 AS material_group_2_mvgr2,
  vbrp.mvgr3 AS material_group_3_mvgr3,
  vbrp.mvgr4 AS material_group_4_mvgr4,
  vbrp.mvgr5 AS material_group_5_mvgr5,
  vbrp.matwa AS material_entered_matwa,
  vbrp.bonba AS rebate_basis_bonba,
  vbrp.kokrs AS controlling_area_kokrs,
  vbrp.paobjnr AS profitab_segmt_no_paobjnr,
  vbrp.ps_psp_pnr AS wbs_element_ps_psp_pnr,
  vbrp.aufnr AS order_aufnr,
  vbrp.txjcd AS tax_jurisdiction_txjcd,
  vbrp.cmpre AS credit_price_cmpre,
  vbrp.cmpnt AS credit_funct_active_cmpnt,
  vbrp.cuobj AS configuration_cuobj,
  vbrp.cuobj_ch AS internal_object_no_cuobj_ch,
  vbrp.koupd AS condition_update_koupd,
  vbrp.uecha AS higherlevelitembatch_uecha,
  vbrp.xchar AS batch_management_xchar,
  vbrp.abrvw AS usage_abrvw,
  vbrp.sernr AS bom_explosion_number_sernr,
  vbrp.bzirk_auft AS sales_distr_order_bzirk_auft,
  vbrp.kdgrp_auft AS customergroupslsord_kdgrp_auft,
  vbrp.konda_auft AS price_group_of_order_konda_auft,
  vbrp.lland_auft AS destinctry_of_order_lland_auft,
  vbrp.mprok AS manual_price_mprok,
  vbrp.pltyp_auft AS price_list_order_pltyp_auft,
  vbrp.regio_auft AS region_order_regio_auft,
  vbrp.vkorg_auft AS sales_org_of_order_vkorg_auft,
  vbrp.vtweg_auft AS distribchannelorder_vtweg_auft,
  vbrp.abrbg AS acctsettlementstart_abrbg,
  vbrp.prosa AS mat_determ_active_prosa,
  vbrp.uepvw AS usage_of_hl_item_uepvw,
  vbrp.autyp AS sd_document_categ_autyp,
  vbrp.stadat AS statistics_date_stadat,
  vbrp.fplnr AS billing_plan_number_fplnr,
  vbrp.fpltr AS item_fpltr,
  vbrp.aktnr AS promotion_aktnr,
  vbrp.knuma_pi AS promotion_knuma_pi,
  vbrp.knuma_ag AS sales_deal_knuma_ag,
  vbrp.prefe AS eligible_for_pref_prefe,
  ${currency.amountWithDecimalShift("vbrp.mwsbp", "currency_decimal")} AS tax_amount_mwsbp,
  vbrp.augru_auft AS order_reason_augru_auft,
  vbrp.fareg AS billing_rule_fareg,
  vbrp.upmat AS mnitm_prcrefmatl_upmat,
  vbrp.ukonm AS mnitem_matpricinggrp_ukonm,
  vbrp.cmpre_flt AS credit_price_cmpre_flt,
  vbrp.abfor AS paymt_guarantee_form_abfor,
  vbrp.abges AS guaranteed_abges,
  vbrp.j_1arfz AS reason_0_vat_j_1arfz,
  vbrp.j_1aregio AS region_j_1aregio,
  vbrp.j_1agicd AS activity_code_gi_tax_j_1agicd,
  vbrp.j_1adtyp AS distribution_type_j_1adtyp,
  vbrp.j_1atxrel AS tax_rel_classif_j_1atxrel,
  vbrp.j_1bcfop AS cfop_j_1bcfop,
  vbrp.j_1btaxlw1 AS icms_law_j_1btaxlw1,
  vbrp.j_1btaxlw2 AS ipi_law_j_1btaxlw2,
  vbrp.j_1btxsdc AS tax_code_j_1btxsdc,
  vbrp.brtwr AS gross_value_brtwr,
  vbrp.wktnr AS value_contract_no_wktnr,
  vbrp.wktps AS value_contract_item_wktps,
  vbrp.rplnr AS paym_ca_pl_no_sales_rplnr,
  vbrp.kursk_dat AS translation_date_kursk_dat,
  vbrp.wgru1 AS material_group_1_wgru1,
  vbrp.wgru2 AS material_group_2_wgru2,
  vbrp.kdkg1 AS condition_group_1_kdkg1,
  vbrp.kdkg2 AS condition_group_2_kdkg2,
  vbrp.kdkg3 AS condition_group_3_kdkg3,
  vbrp.kdkg4 AS condition_group_4_kdkg4,
  vbrp.kdkg5 AS condition_group_5_kdkg5,
  vbrp.vkaus AS usage_vkaus,
  vbrp.j_1aindxp AS inflation_index_j_1aindxp,
  vbrp.j_1aidatep AS indexing_base_date_j_1aidatep,
  vbrp.kzfme AS leading_uom_kzfme,
  vbrp.mwskz AS tax_code_mwskz,
  vbrp.vertt AS contract_type_vertt,
  vbrp.vertn AS contract_number_vertn,
  vbrp.sgtxt AS text_sgtxt,
  vbrp.delco AS delivery_time_delco,
  vbrp.bemot AS accounting_indicator_bemot,
  vbrp.rrrel AS rev_recognition_cat_rrrel,
  vbrp.akkur AS ex_rate_lettofcredit_akkur,
  vbrp.wminr AS catalog_wminr,
  vbrp.vgbel_ex AS reference_document_vgbel_ex,
  vbrp.vgpos_ex AS reference_item_vgpos_ex,
  vbrp.logsys AS logical_system_logsys,
  vbrp.vgtyp_ex AS category_vgtyp_ex,
  vbrp.j_1btaxlw3 AS iss_law_j_1btaxlw3,
  vbrp.j_1btaxlw4 AS cofins_law_j_1btaxlw4,
  vbrp.j_1btaxlw5 AS pis_law_j_1btaxlw5,
  vbrp.msr_id AS process_id_no_msr_id,
  vbrp.msr_refund_code AS refund_code_msr_refund_code,
  vbrp.msr_ret_reason AS return_reason_msr_ret_reason,
  vbrp.nrab_knumh AS condition_record_no_nrab_knumh,
  vbrp.nrab_value AS condition_value_nrab_value,
  vbrp.dispute_case AS dispute_case_dispute_case,
  vbrp.fund_usage_item AS fund_usage_item_fund_usage_item,
  vbrp.farr_reltype AS rev_accounting_type_farr_reltype,
  vbrp.claims_taxation AS claims_taxation_claims_taxation,
  vbrp.kurrf_dat_orig AS translation_date_kurrf_dat_orig,
  vbrp.sgt_rcat AS requirement_segment_sgt_rcat,
  vbrp.sgt_scat AS stock_segment_sgt_scat,
  vbrp.glo_log_ref1_it AS country_specific_reference_1_glo_log_ref1_it,
  vbrp.aufpl AS opertn_task_list_no_aufpl,
  vbrp.aplzl AS counter_aplzl,
  vbrp.dpcnr AS down_payment_chain_number_dpcnr,
  vbrp.dcpnr AS transaction_number_dcpnr,
  vbrp.dpnrb AS document_seq_no_dpnrb,
  vbrp.perop_beg AS period_of_performance_start_date_perop_beg,
  vbrp.perop_end AS period_of_performance_end_date_perop_end,
  vbrp.fmfgus_key AS us_government_fields_fmfgus_key,
  vbrp.fsh_season_year AS season_year_fsh_season_year,
  vbrp.fsh_season AS season_fsh_season,
  vbrp.fsh_collection AS collection_fsh_collection,
  vbrp.fsh_theme AS theme_fsh_theme,
  vbrp.fonds AS fund_fonds,
  vbrp.fistl AS funds_center_fistl,
  vbrp.fkber AS functional_area_fkber,
  vbrp.grant_nbr AS grant_grant_nbr,
  vbrp.budget_pd AS budget_period_budget_pd,
  vbrp.prs_work_period AS work_period_prs_work_period,
  vbrp.pprctr AS partner_profit_ctr_pprctr,
  vbrp.pargb AS trading_part_ba_pargb,
  vbrp.aufpl_oaa AS opertn_task_list_no_aufpl_oaa,
  vbrp.aplzl_oaa AS counter_aplzl_oaa,
  vbrp.campaign AS cgpl_guid_campaign,
  vbrp.compreas AS abb_complaints_reason_compreas,
  vbrp.wrf_charstc1 AS characteristic_value_1_wrf_charstc1,
  vbrp.wrf_charstc2 AS characteristic_value_2_wrf_charstc2,
  vbrp.wrf_charstc3 AS characteristic_value_3_wrf_charstc3,
  dimensional_date_erdat.cal_year AS year_of_creation_date_erdat,
  dimensional_date_erdat.cal_month AS month_of_creation_date_erdat,
  dimensional_date_erdat.cal_quarter AS quarter_of_creation_date_erdat,
  dimensional_date_erdat.cal_week AS week_of_creation_date_erdat,
  IFNULL(
    vbrp.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "vbrp")} AS vbrp
LEFT JOIN ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "vbrk")} AS vbrk
  ON vbrp.mandt = vbrk.mandt
  AND vbrp.vbeln = vbrk.vbeln
LEFT JOIN currency_decimal
  ON vbrk.waerk = currency_decimal.currkey
LEFT JOIN date_dimension AS dimensional_date_erdat
  ON vbrp.erdat = dimensional_date_erdat.date
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["vbrp"])
])}
`,
);
