ecc:
  nota_fiscal_items:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    bigquery:
      iceberg:
        connection: tra-prd-cortex-aecorsoft.US.cortex_iceberg_conn
        bucketName: tra-cortex-iceberg-dev
        fileFormat: PARQUET
    dataformTags: [sap, sales, sap_sd, custom_tramontina, transactional, hourly]
    partitionDetails:
      partitionType: DATE
      timeGrain: DAY
      column: docnum_date_docnum_date
    clusterDetails:
      columns:
        - nota_fiscal_document_docnum
s4:
  nota_fiscal_items:
    materializationType: incremental
    bigQueryLabels:
    - key: line_of_business
      value: sales
    - key: sap_module
      value: sap_sd
    - key: data_class
      value: transactional
    dataformTags: [sap, sales, sap_sd, custom_tramontina, transactional, hourly]
    partitionDetails:
      partitionType: DATE
      timeGrain: DAY
      column: docnum_date_docnum_date
    clusterDetails:
      columns:
        - nota_fiscal_document_docnum
    bigquery:
      iceberg:
        connection: tra-prd-cortex-aecorsoft.US.cortex_iceberg_conn
        bucketName: tra-cortex-iceberg-dev
        fileFormat: PARQUET
