/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const publish_config = require("includes/publish_config.js");
const currencyHelper = require("includes/cortex_v6_compatibility_currency.js");

const materializationType = tableConfig.materializationType || "table";
const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  []
);

publish("delivery_line_items", { ...publishConfig, name: "DeliveryLineItems" }).query(
  (ctx) => `
WITH currency_decimal AS (
  ${currencyHelper.getCurrencyDecimalCTE(ctx, moduleConfig.sources.sapModule.datasetId)}
)
(SELECT
  LIPS.MANDT AS Client_MANDT,
  LIPS.VBELN AS Delivery_VBELN,
  LIPS.POSNR AS DeliveryItem_POSNR,
  LIPS.PSTYV AS DeliveryItemCategory_PSTYV,
  LIPS.ERNAM AS NameOfPersonWhoCreatedTheObject_ERNAM,
  LIPS.ERZET AS EntryTime_ERZET,
  LIPS.ERDAT AS DateOnWhichRecordWasCreated_ERDAT,
  LIPS.MATNR AS MaterialNumber_MATNR,
  LIPS.MATWA AS MaterialEntered_MATWA,
  LIPS.MATKL AS MaterialGroup_MATKL,
  LIPS.WERKS AS Plant_WERKS,
  LIPS.LGORT AS StorageLocation_LGORT,
  LIPS.CHARG AS BatchNumber_CHARG,
  LIPS.LICHN AS VendorBatchNumber_LICHN,
  LIPS.KDMAT AS MaterialBelongingToTheCustomer_KDMAT,
  LIPS.PRODH AS ProductHierarchy_PRODH,
  LIPS.LFIMG AS ActualQuantityDelivered_InSalesUnits_LFIMG,
  LIPS.MEINS AS BaseUnitOfMeasure_MEINS,
  LIPS.VRKME AS SalesUnit_VRKME,
  LIPS.UMVKZ AS Numerator_Factor_ForConversionOfSalesQuantityIntoSku_UMVKZ,
  LIPS.UMVKN AS Denominator_Divisor_ForConversionOfSalesQtyIntoSku_UMVKN,
  LIPS.GEWEI AS WeightUnit_GEWEI,
  LIPS.VOLEH AS VolumeUnit_VOLEH,
  LIPS.KZTLF AS PartialDeliveryAtItemLevel_KZTLF,
  LIPS.UEBTK AS Indicator_UnlimitedOverdeliveryAllowed_UEBTK,
  LIPS.UEBTO AS OverdeliveryToleranceLimit_UEBTO,
  LIPS.UNTTO AS UnderdeliveryToleranceLimit_UNTTO,
  LIPS.CHSPL AS BatchSplitAllowed_CHSPL,
  LIPS.FAKSP AS BillingBlock_FAKSP,
  LIPS.MBDAT AS MaterialAvailabilityDate_MBDAT,
  LIPS.LGMNG AS ActualQuantityDeliveredInStockKeepingUnits_LGMNG,
  LIPS.ARKTX AS ShortTextForSalesOrderItem_ARKTX,
  LIPS.LGPBE AS StorageBin_LGPBE,
  LIPS.VBELV AS OriginatingDocument_VBELV,
  LIPS.POSNV AS OriginatingItem_POSNV,
  LIPS.VBTYV AS SdDocumentCategory_VBTYV,
  LIPS.VGSYS AS LogicalSystemInThePrecedingDocument_VGSYS,
  LIPS.VGBEL AS SalesOrderNumber_VGBEL,
  LIPS.VGPOS AS SalesOrderItem_VGPOS,
  LIPS.VGBEL AS InternalReferenceDocumentNumber_VGBEL,
  LIPS.VGPOS AS InternalReferenceDocumentItem_VGPOS,
  LIPS.UPFLU AS UpdateIndicatorForDeliveryDocumentFlow_UPFLU,
  LIPS.UEPOS AS HigherLevelItemInBOM_UEPOS,
  LIPS.FKREL AS RelevantForBilling_FKREL,
  LIPS.LADGR AS LoadingGroup_LADGR,
  LIPS.TRAGR AS TransportationGroup_TRAGR,
  LIPS.KOMKZ AS IndicatorForPickingControl_KOMKZ,
  LIPS.LGNUM AS WarehouseNumber_LGNUM,
  LIPS.LISPL AS SplitToWarehouseNumberRequired_LISPL,
  LIPS.LGTYP AS StorageType_LGTYP,
  LIPS.LGPLA AS StorageBin_LGPLA,
  LIPS.BWTEX AS Indicator_SeparateValuation_BWTEX,
  LIPS.BWART AS MovementType_InventoryManagement_BWART,
  LIPS.BWLVS AS MovementTypeForWarehouseManagement_BWLVS,
  LIPS.KZDLG AS Indicator_DynamicStorageBinInWarehouseManagement_KZDLG,
  LIPS.BDART AS RequirementType_BDART,
  LIPS.PLART AS PlanningType_PLART,
  LIPS.MTART AS MaterialType_MTART,
  LIPS.XCHPF AS BatchManagementRequirementIndicator_XCHPF,
  LIPS.XCHAR AS BatchManagementIndicator_Internal_XCHAR,
  LIPS.VGREF AS PrecedingDocumentHasResultedFromReference_VGREF,
  LIPS.POSAR AS ItemType_POSAR,
  LIPS.BWTAR AS ValuationType_BWTAR,
  LIPS.SUMBD AS SummingUpOfRequirements_SUMBD,
  LIPS.MTVFP AS CheckingGroupForAvailability_MTVFP,
  LIPS.GSBER AS BusinessArea_GSBER,
  LIPS.VKBUR AS SalesOffice_VKBUR,
  LIPS.VKGRP AS SalesGroup_VKGRP,
  LIPS.VTWEG AS DistributionChannel_VTWEG,
  LIPS.SPART AS Division_SPART,
  LIPS.GRKOR AS DeliveryGroup_ItemsAreDeliveredTogether_GRKOR,
  LIPS.FMENG AS QuantityIsFixed_FMENG,
  LIPS.ANTLF AS MaximumNumberOfPartialDeliveriesAllowedPerItem_ANTLF,
  LIPS.VBEAF AS FixedShippingProcessingTimeInDays_VBEAF,
  LIPS.VBEAV AS VariableShippingProcessingTimeInDays_VBEAV,
  LIPS.STAFO AS UpdateGroupForStatisticsUpdate_STAFO,
  LIPS.KZWI1 AS Subtotal1FromPricingProcedureForCondition_KZWI1,
  LIPS.KZWI2 AS Subtotal2FromPricingProcedureForCondition_KZWI2,
  LIPS.KZWI3 AS Subtotal3FromPricingProcedureForCondition_KZWI3,
  LIPS.KZWI4 AS Subtotal4FromPricingProcedureForCondition_KZWI4,
  LIPS.KZWI5 AS Subtotal5FromPricingProcedureForCondition_KZWI5,
  LIPS.KZWI6 AS Subtotal6FromPricingProcedureForCondition_KZWI6,
  LIPS.SOBKZ AS SpecialStockIndicator_SOBKZ,
  LIPS.AEDAT AS DateOfLastChange_AEDAT,
  LIPS.EAN11 AS InternationalArticleNumber_eanupc_EAN11,
  LIPS.KVGR1 AS CustomerGroup1_KVGR1,
  LIPS.KVGR2 AS CustomerGroup2_KVGR2,
  LIPS.KVGR3 AS CustomerGroup3_KVGR3,
  LIPS.KVGR4 AS CustomerGroup4_KVGR4,
  LIPS.KVGR5 AS CustomerGroup5_KVGR5,
  LIPS.MVGR1 AS MaterialGroup1_MVGR1,
  LIPS.MVGR2 AS MaterialGroup2_MVGR2,
  LIPS.MVGR3 AS MaterialGroup3_MVGR3,
  LIPS.MVGR4 AS MaterialGroup4_MVGR4,
  LIPS.MVGR5 AS MaterialGroup5_MVGR5,
  LIPS.VPZUO AS AllocationIndicator_VPZUO,
  LIPS.VGTYP AS SdDocumentCategory_VGTYP,
  LIPS.RFVGTYP AS TypeOfPrecedingDocumentInCentralSystem_RFVGTYP,
  LIPS.KOSTL AS CostCenter_KOSTL,
  LIPS.KOKRS AS ControllingArea_KOKRS,
  LIPS.PAOBJNR AS ProfitabilitySegmentNumber_PAOBJNR,
  LIPS.PRCTR AS ProfitCenter_PRCTR,
  LIPS.PS_PSP_PNR AS WorkBreakdownStructureElement_wbsElement_PS_PSP_PNR,
  LIPS.AUFNR AS OrderNumber_AUFNR,
  LIPS.POSNR_PP AS OrderItemNumber_POSNR_PP,
  LIPS.KDAUF AS SalesOrderNumber_KDAUF,
  LIPS.KDPOS AS ItemNumberInSalesOrder_KDPOS,
  LIPS.VPMAT AS PlanningMaterial_VPMAT,
  LIPS.VPWRK AS PlanningPlant_VPWRK,
  LIPS.PRBME AS BaseUnitOfMeasureForProductGroup_PRBME,
  LIPS.UMREF AS ConversionFactor_Quantities_UMREF,
  LIPS.KNTTP AS AccountAssignmentCategory_KNTTP,
  LIPS.KZVBR AS ConsumptionPosting_KZVBR,
  LIPS.FIPOS AS CommitmentItem_FIPOS,
  LIPS.FISTL AS FundsCenter_FISTL,
  LIPS.GEBER AS Fund_GEBER,
  LIPS.PCKPF AS PackingControl_PCKPF,
  LIPS.BEDAR_LF AS RequirementsClass_BEDAR_LF,
  LIPS.CMPNT AS Id_ItemWithActiveCreditFunctionRelevantForCredit_CMPNT,
  LIPS.KCMENG AS CumulativeBatchQuantityOfAllSplitItems_InStckunit_KCMENG,
  LIPS.KCBRGEW AS CumulativeGrossWeightOfAllBatchSplitItems_KCBRGEW,
  LIPS.KCNTGEW AS CumulativeNetWeightOfAllBatchSplitItems_KCNTGEW,
  LIPS.KCVOLUM AS CumulativeVolumeOfAllBatchSplitItems_KCVOLUM,
  LIPS.UECHA AS HigherLevelItemOfBatchSplitItem_UECHA,
  LIPS.CUOBJ AS Configuration_CUOBJ,
  LIPS.CUOBJ_CH AS InternalObjectNumberOfTheBatchClassification_CUOBJ_CH,
  LIPS.ANZSN AS NumberOfSerialNumbers_ANZSN,
  LIPS.SERAIL AS SerialNumberProfile_SERAIL,
  LIPS.KCGEWEI AS WeightUnit_KCGEWEI,
  LIPS.KCVOLEH AS VolumeUnit_KCVOLEH,
  LIPS.SERNR AS BomExplosionNumber_SERNR,
  LIPS.ABRLI AS InternalDeliveryScheduleNumber_ABRLI,
  LIPS.ABART AS RelType_ABART,
  LIPS.ABRVW AS UsageIndicator_ABRVW,
  LIPS.QPLOS AS InspectionLotNumber_QPLOS,
  LIPS.QTLOS AS PartialLotNumber_QTLOS,
  LIPS.NACHL AS CustomerHasNotPostedGoodsReceipt_NACHL,
  LIPS.MAGRV AS MaterialGroup_PackagingMaterials_MAGRV,
  LIPS.OBJKO AS ObjectNumberAtHeaderLevel_OBJKO,
  LIPS.OBJPO AS ObjectNumberAtItemLevel_OBJPO,
  LIPS.AESKD AS CustomerEngineeringChangeStatus_AESKD,
  LIPS.SHKZG AS ReturnsItem_SHKZG,
  LIPS.PROSA AS IdForMaterialDetermination_PROSA,
  LIPS.UEPVW AS HigherLevelItemUsage_UEPVW,
  LIPS.EMPST AS ReceivingPoint_EMPST,
  LIPS.ABTNR AS DepartmentNumber_ABTNR,
  LIPS.KOQUI AS PickingIsSubjectToConfirmation_KOQUI,
  LIPS.STADAT AS StatisticsDate_STADAT,
  LIPS.AKTNR AS Promotion_AKTNR,
  LIPS.KNUMH_CH AS NumberOfConditionRecordFromBatchDetermination_KNUMH_CH,
  LIPS.PREFE AS PreferenceIndicatorInExportimport_PREFE,
  LIPS.EXART AS BusinessTransactionTypeForForeignTrade_EXART,
  LIPS.CLINT AS InternalClassNumber_CLINT,
  LIPS.CHMVS AS Batches_ExitToQuantityProposal_CHMVS,
  LIPS.ABELN AS AllocationTableNumber_ABELN,
  LIPS.ABELP AS ItemNumberOfAllocationTable_ABELP,
  LIPS.LFIMG_FLO AS InternalFieldDoNotUseLfimgInFloatMum_LFIMG_FLO,
  LIPS.LGMNG_FLO AS InternalFieldDoNotUseLgmngInFloatMum_LGMNG_FLO,
  LIPS.KCMENG_FLO AS InternalFieldDoNotUseKcmengInFloatMum_KCMENG_FLO,
  LIPS.KZUMW AS EnvironmentallyRelevant_KZUMW,
  LIPS.KMPMG AS ComponentQuantity_KMPMG,
  LIPS.AUREL AS RelevantToAllocationTable_AUREL,
  LIPS.KPEIN AS ConditionPricingUnit_KPEIN,
  LIPS.KMEIN AS ConditionUnit_KMEIN,
  COALESCE(LIPS.NETPR * currency_decimal.CURRFIX, LIPS.NETPR) AS NetPrice_NETPR,
  LIPS.KOWRR AS StatisticalValues_KOWRR,
  LIPS.KZBEW AS MovementIndicator_KZBEW,
  LIPS.MFRGR AS MaterialFreightGroup_MFRGR,
  LIPS.CHHPV AS PackAccumulatedBatchesMovementTypeItem_CHHPV,
  LIPS.ABFOR AS FormOfPaymentGuarantee_ABFOR,
  LIPS.ABGES AS Guaranteed_FactorBetween0And1_ABGES,
  LIPS.MBUHR AS MaterialStagingTime_MBUHR,
  LIPS.WKTNR AS ValueContractNo_WKTNR,
  LIPS.WKTPS AS ValueContractItem_WKTPS,
  LIPS.J_1BCFOP AS CfopCodeAndExtension_J_1BCFOP,
  LIPS.J_1BTAXLW1 AS TaxLaw_Icms_J_1BTAXLW1,
  LIPS.J_1BTAXLW2 AS TaxLaw_Ipi_J_1BTAXLW2,
  LIPS.J_1BTXSDC AS SdTaxCode_J_1BTXSDC,
  LIPS.SITUA AS IndicatorForSituation_SITUA,
  LIPS.RSNUM AS NumberOfReservationdependentRequirements_RSNUM,
  LIPS.RSPOS AS ItemNumberOfReservationDependentRequirements_RSPOS,
  LIPS.RSART AS RecordType_RSART,
  LIPS.KANNR AS KanbansequenceNumber_KANNR,
  LIPS.KZFME AS Id_LeadingUnitOfMeasureForCompletingATransaction_KZFME,
  LIPS.PROFL AS DangerousGoodsIndicatorProfile_PROFL,
  LIPS.KCMENGVME AS CumulativeBatchQuantityOfAllSplitItemsInSalesUnits_KCMENGVME,
  LIPS.KCMENGVMEF AS CumulatedBatchSplitQuantityInVrkmeAndFloat_KCMENGVMEF,
  LIPS.KZBWS AS ValuationOfSpecialStock_KZBWS,
  LIPS.PSPNR AS ProjectDefinition_Internal_PSPNR,
  LIPS.EPRIO AS WithdrawalSequenceGroupForStocks_EPRIO,
  LIPS.RULES AS StockDeterminationRule_RULES,
  LIPS.KZBEF AS IndicatorInventoryManagementActive_KZBEF,
  LIPS.MPROF AS MfrPartProfile_MPROF,
  LIPS.EMATN AS MaterialNumberCorrespondingToManufacturerPartNumber_EMATN,
  LIPS.LGBZO AS StagingAreaForWarehouseComplex_LGBZO,
  LIPS.HANDLE AS WorldwideUniqueKeyForLips_HANDLE,
  LIPS.VERURPOS AS DistributionDelivery_OriginalItem_VERURPOS,
  LIPS.LIFEXPOS AS ExternalItemNumber_LIFEXPOS,
  LIPS.NOATP AS Indicator_DeactivateAvailabilityCheck_NOATP,
  LIPS.NOPCK AS Indicator_NotRelevantForPicking_NOPCK,
  LIPS.RBLVS AS ReferenceMovementTypeForWmFromMaterialMovements_RBLVS,
  LIPS.BERID AS MrpArea_BERID,
  LIPS.BESTQ AS StockCategoryInTheWarehouseManagementSystem_BESTQ,
  LIPS.UMBSQ AS StockCategoryInTheWarehouseManagementSystem_UMBSQ,
  LIPS.UMMAT AS ReceivingIssuingMaterial_UMMAT,
  LIPS.UMWRK AS ReceivingPlantIssuingPlant_UMWRK,
  LIPS.UMLGO AS ReceivingIssuingStorageLocation_UMLGO,
  LIPS.UMCHA AS ReceivingIssuingBatch_UMCHA,
  LIPS.UMBAR AS ValuationTypeOfTransferBatch_UMBAR,
  LIPS.UMSOK AS SpecialStockIndicatorForPhysicalStockTransfer_UMSOK,
  LIPS.SONUM AS SpecialStockNumber_SONUM,
  LIPS.USONU AS SpecialStockNumber_USONU,
  LIPS.AKKUR AS ExchangeRateForLetterForeignTrade_AKKUR,
  LIPS.AKMNG AS CurrentQtyFieldForArithmeticOperations_AKMNG,
  LIPS.VKGRU AS RepairProcessing_ClassificationOfItems_VKGRU,
  LIPS.SHKZG_UM AS Indicator_UnmatInMainPosting_SHKZG_UM,
  LIPS.INSMK AS StockType_INSMK,
  LIPS.KZECH AS DeterminationOfBatchEntryInTheProductionprocessOrder_KZECH,
  LIPS.FLGWM AS DestStorageDataFromPrecedingDocument_FLGWM,
  LIPS.BERKZ AS MaterialStagingIndicatorForProductionSupply_BERKZ,
  LIPS.HUPOS AS Indicator_DeliveryItemIsAHuItem_HUPOS,
  LIPS.NOWAB AS Indicator_ItemNotRelevantForGoodsMovements_NOWAB,
  LIPS.KONTO AS GlAccountNumber_KONTO,
  LIPS.KZEAR AS FinalIssueForThisReservation_KZEAR,
  LIPS.HSDAT AS DateOfManufacture_HSDAT,
  LIPS.VFDAT AS BestBeforeDate_VFDAT,
  LIPS.LFGJA AS FiscalYearOfCurrentPeriod_LFGJA,
  LIPS.LFBNR AS AReferenceDocument_LFBNR,
  LIPS.LFPOS AS ItemOfAReferenceDocument_LFPOS,
  LIPS.GRUND AS ReasonForGoodsMovment_GRUND,
  LIPS.FOBWA AS SubsequentMovementType_FOBWA,
  LIPS.DLVTP AS DeliveryCategory_DLVTP,
  COALESCE(LIPS.EXBWR * currency_decimal.CURRFIX, LIPS.EXBWR) AS ExternallyEnteredPostingAmountInLocalCurrency_EXBWR,
  LIPS.BPMNG AS QuantityInPurchaseOrderPriceUnit_BPMNG,
  COALESCE(LIPS.EXVKW * currency_decimal.CURRFIX, LIPS.EXVKW) AS ExternallyEnteredSalesValueInLocalCurrency_EXVKW,
  LIPS.CMPRE_FLT AS ItemCreditPrice_CMPRE_FLT,
  LIPS.KZPOD AS PodIndicator_KZPOD,
  LIPS.LFDEZ AS NotRelevantForDistributionForWms_LFDEZ,
  LIPS.UMREV AS ConversionFactorOfDeliveryQuantityVrkmeForMeins_UMREV,
  LIPS.PODREL AS PodControl_ProofOfDelivery_PODREL,
  LIPS.KZUML AS StockTransfertransferPosting_KZUML,
  LIPS.FKBER AS FunctionalArea_FKBER,
  LIPS.GRANT_NBR AS Grant_GRANT_NBR,
  LIPS.KZWSO AS UnitsOfMeasureUsage_KZWSO,
  LIPS.GMCONTROL AS GoodsMovementControl_GMCONTROL,
  LIPS.POSTING_CHANGE AS GoodsMovementControl_Hu_POSTING_CHANGE,
  LIPS.UM_PS_PSP_PNR AS Receivingissuing_wbsElement_UM_PS_PSP_PNR,
  LIPS.PRE_VL_ETENS AS SequentialNumberOfVendorConfirmation_PRE_VL_ETENS,
  LIPS.SPE_GEN_ELIKZ AS deliveryCompleted_SPE_GEN_ELIKZ,
  LIPS.SPE_SCRAP_IND AS ScrapIndicatorForEwmProcessing_SPE_SCRAP_IND,
  LIPS.SPE_AUTH_NUMBER AS ReturnMaterialAuthorizationNumber_SPE_AUTH_NUMBER,
  LIPS.SPE_INSPOUT_GUID AS Inspections_InspectionOutcomeGuidSetByEwm_SPE_INSPOUT_GUID,
  LIPS.SPE_FOLLOW_UP AS DefaultFollow_SPE_FOLLOW_UP,
  LIPS.SPE_EXP_DATE_EXT AS EndDateOfValidityPeriodOfReturnsDelivery_SPE_EXP_DATE_EXT,
  LIPS.SPE_EXP_DATE_INT AS EndDateOfInternalValidityPeriodOfReturnsDelivery_SPE_EXP_DATE_INT,
  LIPS.SPE_AUTH_COMPLET AS RmaCompletionIndicator_SPE_AUTH_COMPLET,
  LIPS.ORMNG AS OriginalQuantityOfDeliveryItem_ORMNG,
  LIPS.SPE_ATP_TMSTMP AS AtpTimeStamp_SPE_ATP_TMSTMP,
  LIPS.SPE_ORIG_SYS AS OriginalSystemTypeItm_SPE_ORIG_SYS,
  LIPS.SPE_LIEFFZ AS CumulativeQtyForSchedagrVendorPOV_SPE_LIEFFZ,
  LIPS.SPE_IMWRK AS InboundDeliveryItemHasStatusinPlant_SPE_IMWRK,
  LIPS.SPE_LIFEXPOS2 AS ExternalItemIdentifier_SPE_LIFEXPOS2,
  LIPS.SPE_EXCEPT_CODE AS ExceptionCodeWarehouseForQuantityDifference_SPE_EXCEPT_CODE,
  LIPS.SPE_KEEP_QTY AS RetentionQuantityForScrap_SPE_KEEP_QTY,
  LIPS.SPE_ALTERNATE AS AlternateProductNumber_SPE_ALTERNATE,
  LIPS.SPE_MAT_SUBST AS ReasonForMaterialSubstitution_SPE_MAT_SUBST,
  LIPS.SPE_STRUC AS StructureOfItemsThatAreDeliveredTogether_SPE_STRUC,
  LIPS.SPE_APO_QNTYFAC AS NumeratorOfQuotientForUnitOfMeasureConversion_SPE_APO_QNTYFAC,
  LIPS.SPE_APO_QNTYDIV AS DenominatorOfQuotientForUnitOfMeasureConversion_SPE_APO_QNTYDIV,
  LIPS.SPE_HERKL AS NonPreferentialOrigin_SPE_HERKL,
  LIPS.SPE_BXP_DATE_EXT AS BeginDateOfValidityPeriodOfReturnsDelivery_SPE_BXP_DATE_EXT,
  LIPS.SPE_VERSION AS DeliveryVersionAtConfirmation_SPE_VERSION,
  LIPS.SPE_COMPL_MVT AS CompletionOfGoodsMovementsAfterDifferencePostings_SPE_COMPL_MVT,
  LIPS.J_1BTAXLW4 AS CofinsTaxLaw_J_1BTAXLW4,
  LIPS.J_1BTAXLW5 AS PisTaxLaw_J_1BTAXLW5,
  LIPS.J_1BTAXLW3 AS IssTaxLaw_J_1BTAXLW3,
  LIPS.BUDGET_PD AS Fm_BudgetPeriod_BUDGET_PD,
  LIPS.KBNKZ AS KanbanIndicator_KBNKZ,
  LIPS.FARR_RELTYPE AS RevenueAccountingType_FARR_RELTYPE,
  LIPS.SITKZ AS SpecificationForIssuingValuatedStockInTransit_SITKZ,
  LIPS.SGT_RCAT AS RequirementSegment_SGT_RCAT,
  LIPS.SGT_SCAT AS StockSegment_SGT_SCAT,
  LIPS.FSH_SEASON_YEAR AS SeasonYear_FSH_SEASON_YEAR,
  LIPS.FSH_SEASON AS Season_FSH_SEASON,
  LIPS.FSH_COLLECTION AS FashionCollection_FSH_COLLECTION,
  LIPS.FSH_THEME AS FashionTheme_FSH_THEME,
  LIPS.FSH_KVGR6 AS CustomerGroup6_FSH_KVGR6,
  LIPS.FSH_KVGR7 AS CustomerGroup7_FSH_KVGR7,
  LIPS.FSH_KVGR8 AS CustomerGroup8_FSH_KVGR8,
  LIPS.FSH_KVGR9 AS CustomerGroup9_FSH_KVGR9,
  LIPS.FSH_KVGR10 AS CustomerGroup10_FSH_KVGR10,
  LIPS.FSH_VAS_REL AS VasRelevant_FSH_VAS_REL,
  LIPS.FSH_VAS_PRNT_ID AS DeliveryItem_FSH_VAS_PRNT_ID,
  LIPS.FSH_TRANSACTION AS TransactionNumber_FSH_TRANSACTION,
  LIPS.FSH_ITEM_GROUP AS ItemGroup_FSH_ITEM_GROUP,
  LIPS.FSH_ITEM AS ItemNumber_FSH_ITEM,
  LIPS.FSH_RSNUM AS NumberOfReservationdependentRequirements_FSH_RSNUM,
  LIPS.FSH_RSPOS AS ItemNumberOfReservationDependentRequirements_FSH_RSPOS,
  LIPS.CONS_ORDER AS PurchaseOrderForConsignment_CONS_ORDER,
  LIPS.WRF_CHARSTC1 AS CharacteristicValue1_WRF_CHARSTC1,
  LIPS.WRF_CHARSTC2 AS CharacteristicValue2_WRF_CHARSTC2,
  LIPS.WRF_CHARSTC3 AS CharacteristicValue3_WRF_CHARSTC3,
  IF(LIPS.SHKZG IN ('B', 'S', 'X'), (LIPS.NTGEW * -1), LIPS.NTGEW) AS NetWeight_NTGEW,
  IF(LIPS.SHKZG IN ('B', 'S', 'X'), (LIPS.BRGEW * -1), LIPS.BRGEW) AS GrossWeight_BRGEW,
  IF(LIPS.SHKZG IN ('B', 'S', 'X'), (LIPS.VOLUM * -1), LIPS.VOLUM) AS Volume_VOLUM,
  COALESCE(LIPS.WAVWR * currency_decimal.CURRFIX, LIPS.WAVWR) AS CostInDocumentCurrency_WAVWR,
  COALESCE(LIPS.NETWR * currency_decimal.CURRFIX, LIPS.NETWR) AS NetValueInDocumentCurrency_NETWR,
  COALESCE(
    LIPS.LFIMG * LIPS.NETPR * currency_decimal.CURRFIX, LIPS.LFIMG * LIPS.NETPR
  ) AS DeliveredNetValue
FROM ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'lips')} AS LIPS
LEFT JOIN ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'likp')} AS LIKP
  ON LIKP.VBELN = LIPS.VBELN
  AND LIKP.MANDT = LIPS.MANDT
LEFT JOIN currency_decimal
  ON LIKP.WAERK = currency_decimal.CURRKEY)
`
);
