/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "ledger_lednr",
    "object_number_objnr",
    "fiscal_year_gjahr",
    "value_type_wrttp",
    "version_versn",
    "cost_element_kstar",
    "controlling_subkey_hrkft",
    "business_transaction_vrgng",
    "partner_object_parob",
    "source_object_uspob",
    "debit_credit_indicator_beknz",
    "transaction_currency_twaer",
    "period_block_perbl",
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
SELECT
  coss.mandt AS client_mandt,
  coss.lednr AS ledger_lednr,
  coss.objnr AS object_number_objnr,
  coss.gjahr AS fiscal_year_gjahr,
  coss.wrttp AS value_type_wrttp,
  coss.versn AS version_versn,
  coss.kstar AS cost_element_kstar,
  coss.hrkft AS controlling_subkey_hrkft,
  coss.vrgng AS business_transaction_vrgng,
  coss.parob AS partner_object_parob,
  coss.uspob AS source_object_uspob,
  coss.beknz AS debit_credit_indicator_beknz,
  coss.twaer AS transaction_currency_twaer,
  coss.perbl AS period_block_perbl,
  coss.meinh AS unit_of_measure_meinh,
  coss.wtg001 AS value_transaction_currency_wtg001,
  coss.wtg002 AS value_transaction_currency_wtg002,
  coss.wtg003 AS value_transaction_currency_wtg003,
  coss.wtg004 AS value_transaction_currency_wtg004,
  coss.wtg005 AS value_transaction_currency_wtg005,
  coss.wtg006 AS value_transaction_currency_wtg006,
  coss.wtg007 AS value_transaction_currency_wtg007,
  coss.wtg008 AS value_transaction_currency_wtg008,
  coss.wtg009 AS value_transaction_currency_wtg009,
  coss.wtg010 AS value_transaction_currency_wtg010,
  coss.wtg011 AS value_transaction_currency_wtg011,
  coss.wtg012 AS value_transaction_currency_wtg012,
  coss.wtg013 AS value_transaction_currency_wtg013,
  coss.wtg014 AS value_transaction_currency_wtg014,
  coss.wtg015 AS value_transaction_currency_wtg015,
  coss.wtg016 AS value_transaction_currency_wtg016,
  coss.wog001 AS value_in_object_currency_wog001,
  coss.wog002 AS value_in_object_currency_wog002,
  coss.wog003 AS value_in_object_currency_wog003,
  coss.wog004 AS value_in_object_currency_wog004,
  coss.wog005 AS value_in_object_currency_wog005,
  coss.wog006 AS value_in_object_currency_wog006,
  coss.wog007 AS value_in_object_currency_wog007,
  coss.wog008 AS value_in_object_currency_wog008,
  coss.wog009 AS value_in_object_currency_wog009,
  coss.wog010 AS value_in_object_currency_wog010,
  coss.wog011 AS value_in_object_currency_wog011,
  coss.wog012 AS value_in_object_currency_wog012,
  coss.wog013 AS value_in_object_currency_wog013,
  coss.wog014 AS value_in_object_currency_wog014,
  coss.wog015 AS value_in_object_currency_wog015,
  coss.wog016 AS value_in_object_currency_wog016,
  coss.wkg001 AS value_controlling_area_currency_wkg001,
  coss.wkg002 AS value_controlling_area_currency_wkg002,
  coss.wkg003 AS value_controlling_area_currency_wkg003,
  coss.wkg004 AS value_controlling_area_currency_wkg004,
  coss.wkg005 AS value_controlling_area_currency_wkg005,
  coss.wkg006 AS value_controlling_area_currency_wkg006,
  coss.wkg007 AS value_controlling_area_currency_wkg007,
  coss.wkg008 AS value_controlling_area_currency_wkg008,
  coss.wkg009 AS value_controlling_area_currency_wkg009,
  coss.wkg010 AS value_controlling_area_currency_wkg010,
  coss.wkg011 AS value_controlling_area_currency_wkg011,
  coss.wkg012 AS value_controlling_area_currency_wkg012,
  coss.wkg013 AS value_controlling_area_currency_wkg013,
  coss.wkg014 AS value_controlling_area_currency_wkg014,
  coss.wkg015 AS value_controlling_area_currency_wkg015,
  coss.wkg016 AS value_controlling_area_currency_wkg016,
  coss.wkf001 AS fixvalue_controlling_area_currency_wkf001,
  coss.wkf002 AS fixvalue_controlling_area_currency_wkf002,
  coss.wkf003 AS fixvalue_controlling_area_currency_wkf003,
  coss.wkf004 AS fixvalue_controlling_area_currency_wkf004,
  coss.wkf005 AS fixvalue_controlling_area_currency_wkf005,
  coss.wkf006 AS fixvalue_controlling_area_currency_wkf006,
  coss.wkf007 AS fixvalue_controlling_area_currency_wkf007,
  coss.wkf008 AS fixvalue_controlling_area_currency_wkf008,
  coss.wkf009 AS fixvalue_controlling_area_currency_wkf009,
  coss.wkf010 AS fixvalue_controlling_area_currency_wkf010,
  coss.wkf011 AS fixvalue_controlling_area_currency_wkf011,
  coss.wkf012 AS fixvalue_controlling_area_currency_wkf012,
  coss.wkf013 AS fixvalue_controlling_area_currency_wkf013,
  coss.wkf014 AS fixvalue_controlling_area_currency_wkf014,
  coss.wkf015 AS fixvalue_controlling_area_currency_wkf015,
  coss.wkf016 AS fixvalue_controlling_area_currency_wkf016,
  coss.pag001 AS price_variance_pag001,
  coss.pag002 AS price_variance_pag002,
  coss.pag003 AS price_variance_pag003,
  coss.pag004 AS price_variance_pag004,
  coss.pag005 AS price_variance_pag005,
  coss.pag006 AS price_variance_pag006,
  coss.pag007 AS price_variance_pag007,
  coss.pag008 AS price_variance_pag008,
  coss.pag009 AS price_variance_pag009,
  coss.pag010 AS price_variance_pag010,
  coss.pag011 AS price_variance_pag011,
  coss.pag012 AS price_variance_pag012,
  coss.pag013 AS price_variance_pag013,
  coss.pag014 AS price_variance_pag014,
  coss.pag015 AS price_variance_pag015,
  coss.pag016 AS price_variance_pag016,
  coss.paf001 AS price_variance_fixed_paf001,
  coss.paf002 AS price_variance_fixed_paf002,
  coss.paf003 AS price_variance_fixed_paf003,
  coss.paf004 AS price_variance_fixed_paf004,
  coss.paf005 AS price_variance_fixed_paf005,
  coss.paf006 AS price_variance_fixed_paf006,
  coss.paf007 AS price_variance_fixed_paf007,
  coss.paf008 AS price_variance_fixed_paf008,
  coss.paf009 AS price_variance_fixed_paf009,
  coss.paf010 AS price_variance_fixed_paf010,
  coss.paf011 AS price_variance_fixed_paf011,
  coss.paf012 AS price_variance_fixed_paf012,
  coss.paf013 AS price_variance_fixed_paf013,
  coss.paf014 AS price_variance_fixed_paf014,
  coss.paf015 AS price_variance_fixed_paf015,
  coss.paf016 AS price_variance_fixed_paf016,
  coss.meg001 AS total_quantity_meg001,
  coss.meg002 AS total_quantity_meg002,
  coss.meg003 AS total_quantity_meg003,
  coss.meg004 AS total_quantity_meg004,
  coss.meg005 AS total_quantity_meg005,
  coss.meg006 AS total_quantity_meg006,
  coss.meg007 AS total_quantity_meg007,
  coss.meg008 AS total_quantity_meg008,
  coss.meg009 AS total_quantity_meg009,
  coss.meg010 AS total_quantity_meg010,
  coss.meg011 AS total_quantity_meg011,
  coss.meg012 AS total_quantity_meg012,
  coss.meg013 AS total_quantity_meg013,
  coss.meg014 AS total_quantity_meg014,
  coss.meg015 AS total_quantity_meg015,
  coss.meg016 AS total_quantity_meg016,
  coss.mef001 AS fixed_quantity_mef001,
  coss.mef002 AS fixed_quantity_mef002,
  coss.mef003 AS fixed_quantity_mef003,
  coss.mef004 AS fixed_quantity_mef004,
  coss.mef005 AS fixed_quantity_mef005,
  coss.mef006 AS fixed_quantity_mef006,
  coss.mef007 AS fixed_quantity_mef007,
  coss.mef008 AS fixed_quantity_mef008,
  coss.mef009 AS fixed_quantity_mef009,
  coss.mef010 AS fixed_quantity_mef010,
  coss.mef011 AS fixed_quantity_mef011,
  coss.mef012 AS fixed_quantity_mef012,
  coss.mef013 AS fixed_quantity_mef013,
  coss.mef014 AS fixed_quantity_mef014,
  coss.mef015 AS fixed_quantity_mef015,
  coss.mef016 AS fixed_quantity_mef016,
  coss.muv001 AS quantity_incomplete_muv001,
  coss.muv002 AS quantity_incomplete_muv002,
  coss.muv003 AS quantity_incomplete_muv003,
  coss.muv004 AS quantity_incomplete_muv004,
  coss.muv005 AS quantity_incomplete_muv005,
  coss.muv006 AS quantity_incomplete_muv006,
  coss.muv007 AS quantity_incomplete_muv007,
  coss.muv008 AS quantity_incomplete_muv008,
  coss.muv009 AS quantity_incomplete_muv009,
  coss.muv010 AS quantity_incomplete_muv010,
  coss.muv011 AS quantity_incomplete_muv011,
  coss.muv012 AS quantity_incomplete_muv012,
  coss.muv013 AS quantity_incomplete_muv013,
  coss.muv014 AS quantity_incomplete_muv014,
  coss.muv015 AS quantity_incomplete_muv015,
  coss.muv016 AS quantity_incomplete_muv016,
  coss.beltp AS debit_credit_type_beltp,
  coss.timestmp AS time_created_timestmp,
  coss.bukrs AS company_code_bukrs,
  coss.fkber AS functional_area_fkber,
  coss.segment AS segment,
  coss.geber AS fund_geber,
  coss.grant_nbr AS grant_grant_nbr,
  coss.budget_pd AS budget_period_budget_pd,
  IFNULL(coss.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "coss")} AS coss
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["coss"])
])}
`
);
