# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

description: "Asset Values: Planned Values and Revaluations"
fields:
- name: "mandt"
  description: "Client, PK"
- name: "bukrs"
  description: "Company Code, PK"
- name: "anln1"
  description: "Main Asset Number, PK"
- name: "anln2"
  description: "Asset Subnumber, PK"
- name: "gjahr"
  description: "Fiscal Year, PK"
- name: "afabe"
  description: "Depreciation Area, PK"
- name: "poper"
  description: "Posting Period, PK"
- name: "slalittype"
  description: "Subledger Accounting Line Item Type, PK"
- name: "ldgrp"
  description: "Ledger Group"
- name: "anlgr"
  description: "Group Asset"
- name: "anlgr2"
  description: "Group Asset Subnumber"
- name: "movcat"
  description: "Transaction Type Category"
- name: "hsl"
  description: "Amount in Company Code Currency"
- name: "ksl"
  description: "Amount in Global Currency"
- name: "osl"
  description: "Amount in Freely Defined Currency 1"
- name: "vsl"
  description: "Amount in Freely Defined Currency 2"
- name: "bsl"
  description: "Amount in Freely Defined Currency 3"
- name: "csl"
  description: "Amount in Freely Defined Currency 4"
- name: "dsl"
  description: "Amount in Freely Defined Currency 5"
- name: "esl"
  description: "Amount in Freely Defined Currency 6"
- name: "fsl"
  description: "Amount in Freely Defined Currency 7"
- name: "gsl"
  description: "Amount in Freely Defined Currency 8"
- name: "rhcur"
  description: "Company Code Currency"
- name: "rkcur"
  description: "Global Currency"
- name: "rocur"
  description: "Freely Defined Currency 1"
- name: "rvcur"
  description: "Freely Defined Currency 2"
- name: "rbcur"
  description: "Freely Defined Currency 3"
- name: "rccur"
  description: "Freely Defined Currency 4"
- name: "rdcur"
  description: "Freely Defined Currency 5"
- name: "recur"
  description: "Freely Defined Currency 6"
- name: "rfcur"
  description: "Freely Defined Currency 7"
- name: "rgcur"
  description: "Freely Defined Currency 8"
- name: "anlkl"
  description: "Asset Class"
- name: "ktogr"
  description: "Account Determination"
- name: "xanlgr"
  description: "Indicator: Group Asset"
- name: "xunull"
  description: "Indicator: Below-Zero Account"
- name: "xpost"
  description: "Indicator: to Be Posted"
- name: "poper_shifted"
  description: "Non-Calendar Posting Period"
- name: "recid"
  description: "Recovery Indicator"
- name: "mig_source"
  description: "Migration Source"
- name: "sdm_status"
  description: "Silent Data Migration Status"
- name: "operation_flag"
  description: "Operation Flag"
- name: "is_deleted"
  description: "Is Deleted"
- name: "recordstamp"
  description: "Recordstamp"
