/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ___MODULE_CONTEXT___
// ___TABLE_CONFIG___

const moduleConfig = config.product[moduleContext.moduleId];
const materializationType = tableConfig.materializationType || "incremental";
const currency = require("includes/currency.js");
const incremental = require("includes/incremental.js");
const publish_config = require("includes/publish_config.js");
const sql_helper = require("includes/sql_helper.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "purchasing_document_number_ebeln",
    "item_number_of_purchasing_document_ebelp"
  ]
);

publish(moduleContext.moduleId + "_" + tableConfig.tableName, publishConfig).query(
  (ctx) => `
WITH currency_decimal as (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  ekpo.mandt as client_mandt,
  ekpo.ebeln as purchasing_document_number_ebeln,
  ekpo.ebelp as item_number_of_purchasing_document_ebelp,
  ekpo.loekz as deletion_flag_loekz,
  ekpo.statu as rfq_status_statu,
  ekpo.aedat as change_date_aedat,
  ekpo.txz01 as short_text_txz01,
  ekpo.matnr as material_number_matnr,
  ekpo.ematn as material_number_ematn,
  ekpo.bukrs as company_code_bukrs,
  ekpo.werks as plant_werks,
  ekpo.lgort as storage_location_lgort,
  ekpo.bednr as requirement_tracking_number_bednr,
  ekpo.matkl as material_group_matkl,
  ekpo.infnr as number_of_purchasing_info_record_infnr,
  ekpo.idnlf as material_number_vendor_idnlf,
  ekpo.ktmng as target_quantity_ktmng,
  ekpo.menge as po_quantity_menge,
  ekpo.meins as uo_m_meins,
  ekpo.bprme as order_price_unit_bprme,
  ekpo.bpumz as order_unit_numerator_bpumz,
  ekpo.bpumn as order_unit_denominator_bpumn,
  ekpo.umrez as numerator_for_conversion_of_order_unit_to_base_unit_umrez,
  ekpo.umren as denominator_for_conversion_of_order_unit_to_base_unit_umren,
  ekpo.peinh as price_unit_peinh,
  ekpo.agdat as deadline_for_submission_of_bid_agdat,
  ekpo.webaz as goods_receipt_processing_time_in_days_webaz,
  ekpo.mwskz as taxcode_mwskz,
  ekpo.bonus as settlement_group1_bonus,
  ekpo.insmk as stock_type_insmk,
  ekpo.spinf as update_info_record_flag_spinf,
  ekpo.prsdr as price_printout_prsdr,
  ekpo.schpr as estimated_price_flag_schpr,
  ekpo.mahnz as number_of_reminders_mahnz,
  ekpo.mahn1 as number_of_days_for_first_reminder_mahn1,
  ekpo.mahn2 as number_of_days_for_second_reminder_mahn2,
  ekpo.mahn3 as number_of_days_for_third_reminder_mahn3,
  ekpo.uebto as overdelivery_tolerance_limit_uebto,
  ekpo.uebtk as unlimited_overdelivery_allowed_uebtk,
  ekpo.untto as underdelivery_tolerance_limit_untto,
  ekpo.bwtar as valuation_type_bwtar,
  ekpo.bwtty as valuation_category_bwtty,
  ekpo.abskz as rejection_flag_abskz,
  ekpo.agmem as internal_comment_on_quotation_agmem,
  ekpo.elikz as delivery_completed_flag_elikz,
  ekpo.erekz as final_invoice_flag_erekz,
  ekpo.pstyp as item_categoryin_purchasing_document_pstyp,
  ekpo.knttp as account_assignment_category_knttp,
  ekpo.kzvbr as consumption_posting_kzvbr,
  ekpo.vrtkz as distribution_flag_for_multiple_account_assignment_vrtkz,
  ekpo.twrkz as partial_invoice_flag_twrkz,
  ekpo.wepos as goods_receipt_flag_wepos,
  ekpo.weunb as goods_receipt_non_valuated_weunb,
  ekpo.repos as invoice_receipt_flag_repos,
  ekpo.webre as flag_gr_based_invoice_verification_webre,
  ekpo.kzabs as order_acknowledgment_requirement_kzabs,
  ekpo.labnr as order_acknowledgment_number_labnr,
  ekpo.konnr as number_of_principal_purchase_agreement_konnr,
  ekpo.ktpnr as item_number_of_principal_purchase_agreement_ktpnr,
  ekpo.abdat as reconciliation_date_for_agreed_cumulative_quantity_abdat,
  ekpo.abftz as agreed_cumulative_quantity_abftz,
  ekpo.etfz1 as firm_zone_etfz1,
  ekpo.etfz2 as trade_off_zone_etfz2,
  ekpo.kzstu as firm_trade_off_zones_kzstu,
  ekpo.notkz as exclusion_in_outline_agreement_item_with_material_class_notkz,
  ekpo.lmein as base_unit_of_measure_lmein,
  ekpo.evers as shipping_instructions_evers,
  ekpo.navnw as non_deductible_input_tax_navnw,
  ekpo.abmng as standard_release_order_quantity_abmng,
  ekpo.prdat as date_of_price_determination_prdat,
  ekpo.bstyp as purchasing_document_category_bstyp,
  ekpo.xoblr as item_affects_commitments_xoblr,
  ekpo.adrnr as manual_address_number_in_purchasing_document_item_adrnr,
  ekpo.ekkol as condition_group_with_vendor_ekkol,
  ekpo.sktof as item_does_not_qualify_for_cash_discount_sktof,
  ekpo.stafo as update_group_for_statistics_update_stafo,
  ekpo.plifz as planned_delivery_time_in_days_plifz,
  ekpo.ntgew as net_weight_ntgew,
  ekpo.gewei as unit_of_weight_gewei,
  ekpo.txjcd as tax_jurisdiction_txjcd,
  ekpo.etdrk as flag_print_relevant_schedule_lines_exist_etdrk,
  ekpo.sobkz as special_stock_flag_sobkz,
  ekpo.arsnr as settlement_reservation_number_arsnr,
  ekpo.arsps as item_number_of_the_settlement_reservation_arsps,
  ekpo.insnc as quality_inspection_flag_cannot_be_changed_insnc,
  ekpo.ssqss as control_key_for_quality_management_in_procurement_ssqss,
  ekpo.zgtyp as certificate_type_zgtyp,
  ekpo.ean11 as international_article_number_ean11,
  ekpo.bstae as confirmation_control_key_bstae,
  ekpo.revlv as revision_level_revlv,
  ekpo.geber as fund_geber,
  ekpo.fistl as funds_center_fistl,
  ekpo.fipos as commitment_item_fipos,
  ekpo.ko_gsber as business_area_reported_to_the_partner_ko_gsber,
  ekpo.ko_pargb as assumed_business_area_of_the_business_partner_ko_pargb,
  ekpo.ko_prctr as profit_center_ko_prctr,
  ekpo.ko_pprctr as partner_profit_center_ko_pprctr,
  ekpo.meprf as pricing_date_control_meprf,
  ekpo.brgew as gross_weight_brgew,
  ekpo.volum as volume_volum,
  ekpo.voleh as volume_unit_voleh,
  ekpo.inco1 as incoterms1_inco1,
  ekpo.inco2 as incoterms2_inco2,
  ekpo.vorab as advance_procurement_vorab,
  ekpo.kolif as prior_vendor_kolif,
  ekpo.ltsnr as vendor_subrange_ltsnr,
  ekpo.packno as package_number_packno,
  ekpo.fplnr as invoicing_plan_number_fplnr,
  ekpo.stapo as item_is_statistical_stapo,
  ekpo.uebpo as higher_level_item_in_purchasing_documents_uebpo,
  ekpo.lewed as latest_possible_goods_receipt_lewed,
  ekpo.emlif as vendor_to_be_supplied_emlif,
  ekpo.lblkz as subcontracting_vendor_lblkz,
  ekpo.satnr as cross_plant_configurable_material_satnr,
  ekpo.attyp as material_category_attyp,
  ekpo.vsart as shipping_type_vsart,
  ekpo.handoverloc as location_for_a_physical_handover_of_goods_handoverloc,
  ekpo.kanba as kanban_flag_kanba,
  ekpo.adrn2 as number_of_delivery_address_adrn2,
  ekpo.cuobj as internal_object_number_cuobj,
  ekpo.xersy as evaluated_receipt_settlement_xersy,
  ekpo.eildt as start_date_for_gr_based_settlement_eildt,
  ekpo.drdat as last_transmission_drdat,
  ekpo.druhr as time_druhr,
  ekpo.drunr as sequential_number_drunr,
  ekpo.aktnr as promotion_aktnr,
  ekpo.abeln as allocation_table_number_abeln,
  ekpo.abelp as item_number_of_allocation_table_abelp,
  ekpo.anzpu as number_of_points_anzpu,
  ekpo.punei as points_unit_punei,
  ekpo.saiso as season_category_saiso,
  ekpo.saisj as season_year_saisj,
  ekpo.ebon2 as settlement_group2_ebon2,
  ekpo.ebon3 as settlement_group3_ebon3,
  ekpo.ebonf as item_relevant_to_subsequent_settlement_ebonf,
  ekpo.mlmaa as material_ledger_activated_at_material_level_mlmaa,
  ekpo.mhdrz as minimum_remaining_shelf_life_mhdrz,
  ekpo.anfnr as rfq_number_anfnr,
  ekpo.anfps as item_number_of_rfq_anfps,
  ekpo.kzkfg as origin_of_configuration_kzkfg,
  ekpo.usequ as quota_arrangement_usage_usequ,
  ekpo.umsok as special_stock_flag_for_physical_stock_transfer_umsok,
  ekpo.banfn as purchase_requisition_number_banfn,
  ekpo.bnfpo as item_number_of_purchase_requisition_bnfpo,
  ekpo.mtart as material_type_mtart,
  ekpo.uptyp as subitem_category_uptyp,
  ekpo.upvor as subitems_exist_upvor,
  ekpo.kzwi1 as subtotal1_from_pricing_procedure_for_condition_kzwi1,
  ekpo.kzwi2 as subtotal2_from_pricing_procedure_for_condition_kzwi2,
  ekpo.kzwi3 as subtotal3_from_pricing_procedure_for_condition_kzwi3,
  ekpo.kzwi4 as subtotal4_from_pricing_procedure_for_condition_kzwi4,
  ekpo.kzwi5 as subtotal5_from_pricing_procedure_for_condition_kzwi5,
  ekpo.kzwi6 as subtotal6_from_pricing_procedure_for_condition_kzwi6,
  ekpo.sikgr as processing_key_for_subitems_sikgr,
  ekpo.mfzhi as maximum_cumulative_material_go_ahead_quantity_mfzhi,
  ekpo.ffzhi as maximum_cumulative_production_go_ahead_quantity_ffzhi,
  ekpo.retpo as returns_item_retpo,
  ekpo.aurel as relevant_to_allocation_table_aurel,
  ekpo.bsgru as reason_for_ordering_bsgru,
  ekpo.lfret as delivery_type_for_returns_to_vendors_lfret,
  ekpo.mfrgr as material_freight_group_mfrgr,
  ekpo.nrfhg as material_qualifies_for_discount_in_kind_nrfhg,
  ekpo.abueb as release_creation_profile_abueb,
  ekpo.nlabd as next_forecast_delivery_schedule_transmission_nlabd,
  ekpo.nfabd as next_jit_delivery_schedule_transmission_nfabd,
  ekpo.kzbws as valuation_of_special_stock_kzbws,
  ekpo.fabkz as flag_item_relevant_to_jit_delivery_schedules_fabkz,
  ekpo.j_1aindxp as inflation_index_j_1_aindxp,
  ekpo.j_1aidatep as inflation_index_date_j_1_aidatep,
  ekpo.mprof as manufacturer_part_profile_mprof,
  ekpo.eglkz as outward_delivery_completed_flag_eglkz,
  ekpo.kztlf as stock_transfer_kztlf,
  ekpo.kzfme as unit_of_measure_usage_kzfme,
  ekpo.rdprf as rounding_profile_rdprf,
  ekpo.techs as standard_variant_techs,
  ekpo.chg_srv as configuration_changed_chg_srv,
  ekpo.chg_fplnr as no_invoice_for_item_although_not_free_of_charge_chg_fplnr,
  ekpo.mfrpn as manufacturer_part_number_mfrpn,
  ekpo.mfrnr as number_of_a_manufacturer_mfrnr,
  ekpo.emnfr as external_manufacturer_codename_or_number_emnfr,
  ekpo.novet as item_blocked_for_sd_delivery_novet,
  ekpo.afnam as name_of_requester_afnam,
  ekpo.tzonrc as timezone_of_recipient_location_tzonrc,
  ekpo.iprkz as period_flag_for_shelf_life_expiration_date_iprkz,
  ekpo.lebre as flag_for_service_based_invoice_verification_lebre,
  ekpo.berid as mrp_area_berid,
  ekpo.xconditions as conditions_for_item_although_no_invoice_xconditions,
  ekpo.apoms as ap_oas_planning_system_apoms,
  ekpo.ccomp as posting_logic_in_the_case_of_stock_transfers_ccomp,
  ekpo.grant_nbr as grant_grant_nbr,
  ekpo.fkber as functional_area_fkber,
  ekpo.status as status_of_purchasing_document_item_status,
  ekpo.reslo as issuing_storage_location_for_stock_transport_order_reslo,
  ekpo.kblnr as document_number_for_earmarked_funds_kblnr,
  ekpo.kblpos as earmarked_funds_document_item_kblpos,
  ekpo.weora as acceptance_at_origin_weora,
  ekpo.srv_bas_com as service_based_commitment_srv_bas_com,
  ekpo.prio_urg as requirement_urgency_prio_urg,
  ekpo.prio_req as requirement_priority_prio_req,
  ekpo.empst as receiving_point_empst,
  ekpo.diff_invoice as differential_invoicing_diff_invoice,
  ekpo.trmrisk_relevant as risk_relevancyin_purchasing_trmrisk_relevant,
  ekpo.spe_abgru as reason_for_rejection_of_quotations_and_sales_orders_spe_abgru,
  ekpo.spe_crm_so as crm_sales_order_number_for_tpop_spe_crm_so,
  ekpo.spe_crm_so_item as crm_sales_order_item_number_in_tpop_spe_crm_so_item,
  ekpo.spe_crm_ref_so as crm_reference_order_number_for_tpop_spe_crm_ref_so,
  ekpo.spe_crm_ref_item as crm_reference_sales_order_item_number_in_tpop_spe_crm_ref_item,
  ekpo.spe_crm_fkrel as billing_relevance_crm_spe_crm_fkrel,
  ekpo.spe_chng_sys as last_changer_system_type_spe_chng_sys,
  ekpo.spe_insmk_src as stock_typeof_source_storage_location_in_sto_spe_insmk_src,
  ekpo.spe_cq_ctrltype as cq_control_type_spe_cq_ctrltype,
  ekpo.spe_cq_nocq as no_transmission_of_cumulative_quantities_in_sa_release_spe_cq_nocq,
  ekpo.reason_code as goods_receipt_reason_code_reason_code,
  ekpo.cqu_sar as cumulative_goods_receipts_cqu_sar,
  ekpo.anzsn as number_of_serial_numbers_anzsn,
  ekpo.spe_ewm_dtc as ewm_delivery_based_tolerance_check_spe_ewm_dtc,
  ekpo.exlin as item_number_length_exlin,
  ekpo.exsnr as external_sorting_exsnr,
  ekpo.ehtyp as external_hierarchy_category_ehtyp,
  ekpo.retpc as retention_in_percent_retpc,
  ekpo.dptyp as down_payment_flag_dptyp,
  ekpo.dppct as down_payment_percentage_dppct,
  ekpo.dpamt as down_payment_in_document_currency_dpamt,
  ekpo.dpdat as due_date_for_down_payment_dpdat,
  ekpo.fls_rsto as store_return_with_inbound_and_outbound_delivery_fls_rsto,
  ekpo.ext_rfx_number as document_number_of_external_document_ext_rfx_number,
  ekpo.ext_rfx_item as item_number_of_external_document_ext_rfx_item,
  ekpo.ext_rfx_system as logical_system_ext_rfx_system,
  ekpo.srm_contract_id as central_contract_srm_contract_id,
  ekpo.srm_contract_itm as central_contract_item_number_srm_contract_itm,
  ekpo.blk_reason_id as blocking_reason_id_blk_reason_id,
  ekpo.blk_reason_txt as blocking_reason_text_blk_reason_txt,
  ekpo.itcons as real_time_consumption_posting_of_subcontracting_components_itcons,
  ekpo.fixmg as delivery_date_and_quantity_fixed_fixmg,
  ekpo.wabwe as flag_for_gi_based_goods_receipt_wabwe,
  ekpo.tc_aut_det as tax_code_automatically_determined_tc_aut_det,
  ekpo.manual_tc_reason as manual_tax_code_reason_manual_tc_reason,
  ekpo.fiscal_incentive as tax_incentive_type_fiscal_incentive,
  ekpo.tax_subject_st as tax_subject_tax_subject_st,
  ekpo.fiscal_incentive_id as incentive_id_fiscal_incentive_id,
  ekpo.advcode as advice_code_advcode,
  ekpo.budget_pd as fm_budget_period_budget_pd,
  ekpo.excpe as acceptance_period_excpe,
  ekpo.iuid_relevant as iuid_relevant_iuid_relevant,
  ekpo.mrpind as retail_price_relevant_mrpind,
  ekpo.refsite as reference_site_for_purchasing_refsite,
  ekpo.serru as type_of_subcontracting_serru,
  ekpo.sernp as serial_number_profile_sernp,
  ekpo.disub_sobkz as special_stock_flag_subcontracting_disub_sobkz,
  ekpo.disub_pspnr as wbs_element_disub_pspnr,
  ekpo.disub_kunnr as customer_number_disub_kunnr,
  ekpo.disub_vbeln as sales_and_distribution_document_number_disub_vbeln,
  ekpo.disub_posnr as item_number_of_the_sd_document_disub_posnr,
  ekpo.disub_owner as owner_of_stock_disub_owner,
  ekpo.ref_item as reference_item_for_remaining_qty_cancellation_ref_item,
  ekpo.source_id as origin_profile_source_id,
  ekpo.source_key as keyin_source_system_source_key,
  ekpo.put_back as flag_for_putting_back_from_grouped_po_document_put_back,
  ekpo.pol_id as order_list_item_number_pol_id,
  ekpo.cons_order as purchase_order_for_consignment_cons_order,
  ekko.waers as currency_key_waers,
  ${currency.amountWithDecimalShift("ekpo.netpr", "currency_decimal")} as net_price_netpr,
  ${currency.amountWithDecimalShift("ekpo.netwr", "currency_decimal")} as net_order_value_in_po_currency_netwr,
  ${currency.amountWithDecimalShift("ekpo.brtwr", "currency_decimal")} as gross_order_value_in_po_currency_brtwr,
  ${currency.amountWithDecimalShift("ekpo.zwert", "currency_decimal")} as target_value_for_outline_agreement_in_document_currency_zwert,
  ${currency.amountWithDecimalShift("ekpo.effwr", "currency_decimal")} as effective_value_of_item_effwr,
  ${currency.amountWithDecimalShift("ekpo.bonba", "currency_decimal")} as rebate_basis1_bonba,
  GREATEST(
    IFNULL(ekpo.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
    IFNULL(ekko.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00'))
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'ekpo')} as ekpo
LEFT JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'ekko')} as ekko
  ON ekpo.mandt = ekko.mandt
  AND ekpo.ebeln = ekko.ebeln
LEFT JOIN currency_decimal
  ON ekko.waers = currency_decimal.currkey
${sql_helper.buildDynamicWhere([
  incremental.getFilter(ctx, ["ekpo", "ekko"])
])}
`,
);
